#!/usr/bin/env python3
"""Emit tools/ou_gloss_<k>.py from ou_chunk_<k>.json plus a list of Chinese.

Pairing by index rather than by retyping the English key means the keys are
exact. These glosses carry Wiktionary typos ("doctine", "worrdly"), astral-plane
punctuation characters (U+10F86–10F89), a literal \\n and Tibetan runs — any of
which a hand-retyped key would quietly corrupt, leaving the gloss untranslated
with no error to notice.

Used by tools/ou_zh_<k>.py, one per chunk; those are the files to edit.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))


def emit(k, zh, note):
    src = os.path.join(HERE, f"ou_chunk_{k}.json")
    en = json.load(open(src, encoding="utf-8"))
    if len(en) != len(zh):
        sys.exit(f"chunk {k}: {len(en)} glosses but {len(zh)} translations")
    bad = [i for i, z in enumerate(zh) if not z or not z.strip()]
    if bad:
        sys.exit(f"chunk {k}: empty translation at index {bad}")
    dst = os.path.join(HERE, f"ou_gloss_{k}.py")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("#!/usr/bin/env python3\n")
        f.write(f'"""Chinese for the Old Uyghur glosses, part {k.upper()} — {note}.\n\n')
        f.write("Generated by tools/emit_ou_gloss.py from tools/ou_zh_%s.py; edit that.\n\"\"\"\n" % k)
        f.write("G = {\n")
        for e, z in zip(en, zh):
            f.write(f"{e!r}:\n    {z!r},\n")
        f.write("}\n")
    print(f"  ou_gloss_{k}.py  {len(en)} 条")
