#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part B (G–S of the short list)."""
G = {
"(⁓ хөгжим) quartet":"（⁓ хөгжим）四重奏","ace":"尖子、A（牌）","banner":"旗；旗（行政区）",
"beam, ridgepole":"梁、栋","brand new, fresh":"崭新的","chest (body part)":"胸",
"earring":"耳环","girl":"女孩","give! bring!":"给！拿来！","glacier":"冰川","gland":"腺",
"glass":"玻璃、杯","glove":"手套","glue":"胶","goal, aim":"目标","goal, intention":"意图",
"goat":"山羊","god":"神","gold":"金","good morning":"早安","goods, property":"财物",
"gorge, cavity":"沟壑、空腔","gorge, ravine":"峡谷","gourd, melon":"葫芦、瓜",
"government":"政府","grain":"谷粒","grain, cereal":"谷物","grammar":"语法",
"grandmother":"祖母","grandson":"孙子","grass":"草","grasshopper":"蚱蜢","grave":"墓",
"green":"绿","greeting":"问候","grid; mesh":"网格","grief; sorrow":"悲伤","ground":"地面",
"group":"群、组","grown, mature":"成年的","gruel, porridge":"粥","guest; visitor":"客人",
"guide (person)":"向导","guide; cicerone":"导游","gunpowder":"火药","guy, chap":"家伙",
"gyrfalcon":"矛隼","hair salon":"发廊","half":"一半","hand":"手","hand-held":"手持的",
"hand-held scales":"手秤","handmade":"手工的","happiness":"幸福","hard time":"艰难时期",
"hardly":"几乎不","hare, rabbit":"兔","harm":"危害","harmony, concord":"和睦",
"harmony, peace":"和平","harrow":"耙","hat":"帽","haughty, arrogant":"傲慢的",
"hay":"干草","haystack":"草垛","he, she, it":"他、她、它","headline":"标题",
"headstone":"墓碑","heart":"心","hedgehog":"刺猬","helicopter":"直升机","hell":"地狱",
"hello, how are you":"你好","helmet":"头盔","hemp, rope, chain":"麻、绳、链","herb":"草药",
"herdsman":"牧民","hereof, thereof":"于此、于彼","heretic":"异端","hero":"英雄",
"high":"高","high, tall":"高的","high-quality":"优质的","hill":"丘","hind, back, rear":"后部",
"hip":"髋","his, hers, its":"他的、她的、它的","hobby":"爱好","hole":"洞","holiday":"假日",
"homosexual":"同性恋的","honest":"诚实的","hoof":"蹄","hoopoe":"戴胜","horde":"部众、汗庭",
"horn":"角","horse":"马","hospital":"医院","hot spring":"温泉","hotel":"旅馆",
"house":"房屋","how":"如何","how much, how many":"多少","human, human being":"人",
"hump, humpback":"驼峰、驼背","hundred":"百","hunger":"饥饿","hungry":"饥饿的",
"husband":"丈夫","hyphen":"连字符","ice cream":"冰淇淋","idiom":"成语","idiot":"白痴",
"image, form, mien":"形象、仪态","important":"重要的","imprint":"印记","improvised":"即兴的",
"in (in a language)":"用（某语言）","in that way":"那样","in the morning":"早晨",
"in, inside":"在……内","industrialization":"工业化","industry":"工业","influence":"影响",
"informatics":"信息学","inheritance":"继承","injection":"注射","ink":"墨","inkpot":"墨盒",
"inner ear, eardrum":"内耳、鼓膜","insane, crazy":"疯狂的","insect, bug":"昆虫",
"inside, interior":"内部","instrument":"器械、乐器","insufficient":"不足的","insurance":"保险",
"intellect":"智力","intelligence":"才智；情报","intelligent":"聪明的","intelligentsia":"知识阶层",
"intentionally":"故意地","internal":"内部的","invocation":"祝祷","irate":"愤怒的",
"isthmus":"地峡","item":"项目","jacket":"外衣","jagged":"锯齿状的","jail":"监狱",
"jail, prison":"监狱","jam":"果酱","jataka":"本生（佛教）","jaw":"颌","joint, node":"关节、节",
"journalist":"记者","joy, happiness":"欢乐","juice":"汁","juicy, sappy":"多汁的",
"juniper":"桧、刺柏","just one, sole":"仅一个","kangaroo":"袋鼠","kettle, teapot":"水壶、茶壶",
"keyboard":"键盘","khan, emperor":"汗、皇帝","khan’s son-in-law":"驸马","kidney":"肾",
"king":"国王","kingdom":"王国","kingdom, realm":"王国、疆域","knee":"膝","knife":"刀",
"knight":"骑士","knitted":"针织的","knot":"结","known (not secret)":"公开的",
"laborer":"劳工","lacking, absent":"缺少的","lake":"湖","lama":"喇嘛","lamp, torch":"灯、炬",
"language, tongue":"语言","lantern":"灯笼","larch (Larix)":"落叶松","large":"大的",
"lasso pole; lasso":"套马杆、套索","last year":"去年","last year's":"去年的","law":"法律",
"lawyer":"律师","layer, stratum":"层","layer; stratum":"层","leather":"皮革","ledge":"壁架",
"left":"左","leftist":"左翼的","let's, let me":"让我们、让我","liar":"说谎者",
"lichen, moss":"地衣、苔藓","lie (falsehood)":"谎言","life":"生命","ligament":"韧带",
"light":"光；轻","light blue":"浅蓝","lime":"石灰","line":"线","line, dash":"线、破折号",
"line, stanza":"诗行、诗节","linguistics":"语言学","lion":"狮","lip":"唇","liquid":"液体",
"liquor brewer":"酿酒者","little, small":"小","liver (organ)":"肝","livestock, cattle":"牲畜",
"lizard":"蜥蜴","lobster":"龙虾","lock, latch, bolt":"锁、闩","log, logbook":"日志",
"loin":"腰","long":"长","louse":"虱","low":"低","luggage":"行李","lumber carrier":"运木车",
"lunch meat":"午餐肉","lungs":"肺","lynx":"猞猁","machine, machinery":"机器",
"madam; lady; Mrs":"夫人","magazine":"杂志","magma":"岩浆","magnifying glass":"放大镜",
"mail; post":"邮件","majestic, sacred":"庄严、神圣的","makeup, texture":"构造、质地",
"male":"男性的、雄的","malice, evil":"恶意","man (a grown man)":"成年男子",
"mane (of a horse)":"马鬃","manliness, power":"雄健、威力","manner, way, means":"方式、手段",
"mantic":"占卜的","manul (wildcat)":"兔狲","map":"地图","mark, trace":"痕迹",
"market, bazaar":"市集","marmot, tarbagan":"旱獭","massage":"按摩","master":"主人、师傅",
"matter, substance":"物质","mattress":"褥垫","mausoleum":"陵墓","meager, emaciated":"瘦削的",
"meal":"餐","meaning, sense":"意义","measure":"尺度","meat":"肉","melody":"曲调",
"member":"成员","membrane":"膜","menthol":"薄荷脑","merchandise":"商品",
"merchant; trader":"商人","metal":"金属","method":"方法","microbiology":"微生物学",
"middle":"中间","mileage":"里程","milk":"奶","mine":"矿；我的","mink":"貂","mint":"薄荷",
"minute":"分钟","missile":"导弹","mistake":"错误","mobile phone":"手机",
"mockery, derision":"嘲弄","molar":"臼齿","mold, mildew":"霉","molten":"熔融的",
"mom":"妈妈","monastery":"寺院","money (China)":"钱（汉语借词）","monk, bhikkhu":"僧、比丘",
"monkey":"猴","monument":"纪念碑","mood":"心情","morning":"早晨","morrow":"次日",
"mortar":"臼；砂浆","mosquito":"蚊","mother":"母亲","motherland":"祖国","mountain":"山",
"mountain goat":"山羊","mountain range":"山脉","mountain ridge":"山脊","mouse":"鼠",
"moustache":"髭","mucus":"黏液","mud":"泥","mug":"杯","mule":"骡","mush":"糊",
"mushroom, fungus":"蘑菇、真菌","music":"音乐","musical bow":"乐弓","musician":"乐师",
"musk deer":"麝","musk gland":"麝香腺","my":"我的","nails":"指甲","narrow":"窄",
"nation":"民族、国家","naval":"海军的","nearby":"附近","neat, clear":"整洁、清晰",
"necktie":"领带","need (necessity)":"需要","need, requirement":"需求","needle":"针",
"needlecase":"针筒","neighbour":"邻居","nest":"巢","net":"网","never":"从不","new":"新",
"newly-born, infant":"新生儿","news":"消息","news, rumours":"消息、传闻","newspaper":"报纸",
"next year":"明年","nickname":"绰号","nightingale":"夜莺","nineteen":"十九","nipple":"乳头",
"nirvana":"涅槃","nomad":"游牧民","noodles, pasta":"面条","norm":"规范","north":"北",
"northern":"北方的","northward":"向北","nose":"鼻","nostril":"鼻孔","note message":"便条",
"now":"现在","nuisance, menace":"祸患","nun, bhikkhuni":"尼、比丘尼","oak":"橡",
"obstacle":"障碍","occasion":"场合","occasion, time":"时机","ocean":"大洋","ocean, sea":"海洋",
"octopus":"章鱼","off":"离、关","office; bureau":"机关、办公室","official, noyan":"官员、那颜",
"often":"常常","oil; petroleum":"油、石油","okay; alright":"好的","old, middle-aged":"年长的",
"on":"在……上","on this side of":"在……这一侧","one's own":"自己的","open":"打开的",
"opera":"歌剧","operation":"手术、行动","opinion":"意见","opponent":"对手",
"orange (fruit)":"橙","orchard":"果园","organ; limb":"器官、肢体","origin":"起源",
"origin, source":"渊源","origin; source":"本源","orphan":"孤儿","ostrich":"鸵鸟",
"other":"其他的","our":"我们的","our, ours":"我们的","ours":"我们的","outing":"郊游",
"outside (position)":"外面","owner, master":"主人","paintbrush":"画笔","pair":"一对",
"palace; mansion":"宫殿、府邸","pap":"糊食","paper":"纸","parachute":"降落伞",
"paradise":"乐园","paralysis, palsy":"瘫痪","park":"公园","park; garden":"园囿",
"parking lot":"停车场","parliament":"议会","parrot":"鹦鹉","part, portion":"部分",
"part, share, lot":"份额","passport":"护照","password":"密码","past tense":"过去时",
"pasture":"牧场","paternal uncle":"叔伯","path, route":"路径","patience":"耐心",
"patrol guard":"巡守","pauldron":"肩甲","pawn shop":"当铺","pay (wage)":"工资","peace":"和平",
"peacock":"孔雀","peak":"峰","peanut":"花生","pear":"梨","peel, shell":"皮、壳",
"pelvis, hip, thigh":"骨盆、髋、股","pencil":"铅笔","pencil case":"笔盒","peninsula":"半岛",
"penis":"阴茎","penis.":"阴茎。","pension":"养老金","people":"人民","perfume; cologne":"香水",
"period":"时期","permission":"许可","perruquier":"假发匠","person, man":"人",
"perspiration":"汗","pestle":"杵","photograph":"照片","photographer":"摄影师","phrase":"短语",
"phylum":"门（生物）","pickled":"腌渍的","picture":"图画","piercing":"穿刺",
"pigeon":"鸽","pile, heap":"堆","pillow":"枕","pillow, cushion":"枕、垫","pin":"别针",
"pine":"松","pit, hole":"坑","pitchfork":"叉","placenta":"胎盘","plastic":"塑料",
"plateau, hill":"高原、丘","playing card":"纸牌","pleasure":"愉悦","pliers":"钳",
"plug socket":"插座","pocket":"口袋","poet":"诗人","point, tip":"尖端","poison":"毒",
"police":"警察","police officer":"警官","portrait":"肖像","pot, saucepan":"锅",
"potato":"土豆","power":"权力、力量","prayer":"祈祷","prayer beads":"念珠",
"precipitation":"降水","predicate":"谓语","pregnant":"怀孕的","prepared":"备好的",
"preposition":"介词","prescription":"处方","price, value":"价格、价值",
"pride, haughtiness":"骄傲","primal, original":"原初的","primer (ABC book)":"启蒙读本",
"prince":"王子","princess":"公主","prison, jail":"监狱","prison; jail, gaol":"牢狱",
"prize; reward":"奖赏","probably, maybe":"大概","process, course":"过程","proficiency":"熟练",
"profound":"深奥的","promotion":"晋升","pronunciation":"发音","proposal, offer":"提议",
"prostitute, whore":"妓女","protector":"守护者","proud, boastful":"自负的",
"proverb, adage":"谚语","province":"省","pump":"泵","punishment":"惩罚","pupa (insect)":"蛹",
"pure":"纯净的","pyramid":"金字塔","quail":"鹌鹑","quality, stature":"品质、身量",
"quarrel":"争吵","quarrel, fight":"争斗","question":"问题","radish":"萝卜","rage":"暴怒",
"railway":"铁路","rain":"雨","rare, sparse, few":"稀少的","rat":"鼠","rate":"比率",
"raven":"渡鸦","reaction":"反应","reader":"读者","ready, at hand":"现成的",
"reason, cause":"原因","rebel, bandit":"叛匪","receipt":"收据","recipe":"食谱",
"rectum":"直肠","red":"红","reed":"芦苇","refrigerator":"冰箱","rein":"缰",
"reindeer":"驯鹿","republic":"共和国","request":"请求","request, demand":"请求、要求",
"rescuer; saviour":"救者","resembling":"相似的","rest":"休息","restaurant":"餐馆",
"retribution":"报应","return":"归返","rhinoceros":"犀","rib":"肋","rice":"米",
"riches, wealth":"财富","richness":"丰饶","right hand":"右手","right wing":"右翼",
"right, right-hand":"右、右侧的","rightist":"右翼的","ring":"戒指、环","river":"河",
"river bifurcation":"河汊","road, path, way":"道路","rock, stone":"岩石","rodent":"啮齿动物",
"rolling pin":"擀面杖","roof":"屋顶","room":"房间","root":"根","root, base":"根基",
"root, origin":"根源","row (of people)":"行列","rubber":"橡胶","ruble":"卢布","rudder":"舵",
"rudder, wheel":"舵轮","rule, order":"规矩","rule, principle":"法则","ruler (tool)":"尺",
"rum":"朗姆酒","rumors":"传闻","rumour":"传闻","rump":"臀","ruse":"计谋","ruse, scheme":"诡计",
"rush":"急赶","ruthenium":"钌","sable":"黑貂","sabre":"马刀","sacred":"神圣的","sacrum":"骶骨",
"saddle":"鞍","saffron":"藏红花","saiga (antelope)":"赛加羚","sailor, seaman":"水手",
"salami":"萨拉米肠","saliva":"唾液","salt":"盐","salted":"腌的","same":"相同的",
"samsara":"轮回","sand":"沙","sand dune":"沙丘","sap":"树液","sauce":"酱",
"sauce, gravy":"酱汁","savage, barbaric":"野蛮的","saw":"锯","saxaul":"梭梭",
"scalpel":"手术刀","schedule; program":"日程、节目单","science":"科学","scissors":"剪刀",
"scorpion":"蝎","screen, board":"屏、板","scripture":"经典","scripture; sutra":"经、佛经",
"scrofula":"瘰疬","sculpture":"雕塑","sea":"海","seam, stitch":"缝","seat of government":"治所",
"seat, site":"座位、场地","second":"秒；第二","secret":"秘密","sediment":"沉积物","self":"自己",
"sentence":"句子","servant":"仆人","service":"服务","seventeen":"十七","several; few":"若干",
"sewing, stitchery":"缝纫","shadow, shade":"影","shaggy":"蓬乱的","shamaness":"女萨满",
"shape, form":"形状","shark":"鲨","shaver":"剃刀","sheep":"绵羊","shell":"壳",
"shield":"盾","shin, shank":"胫","ship; vessel":"船","shirt":"衬衫","shoe, footwear":"鞋",
"shop":"商店","short":"短","short for ᠴᠢᠰᠤᠨ":"ᠴᠢᠰᠤᠨ 的简写","shoulder":"肩",
"shoulder pad":"垫肩","shovel, spade":"铲","shrimp":"虾","sickle":"镰","side":"侧",
}
