#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part C (nouns S–T and the verb block)."""
G = {
# --- nouns and phrases ---
"A Khori-Buryat clan":"豁里布里亚特一氏族","Caragana leucophloea":"白皮锦鸡儿",
"The roar of a tiger.":"虎啸。","a (political) party":"政党","a religious petition":"祈愿文",
"a submissive person":"顺从者","a two-year-old calf":"两岁犊","aged people, elders":"长者",
"almost, practically":"几乎","anicca, impermanence":"无常","anniversary, jubilee":"周年庆",
"any beaded jewellery":"珠串饰物","apprentice, student":"学徒","arrearage, hangover":"积欠；宿醉",
"board, plank, tablet":"板、牌","bookshop, bookstore":"书店","border, edge, margin":"边缘",
"boulder, rock, crag":"巨石、岩崖","bracelet; wristband":"手镯","branch; of a lineage":"支系",
"breastbone, sternum":"胸骨","carnivore, predator":"食肉兽","cautious, deliberate":"谨慎的",
"clandestine, secret":"秘密的","competition, rivalry":"竞争","completely, totally":"完全地",
"congee (rice gruel)":"粥","contrast, comparison":"对比","cork, stopper, plug":"塞子",
"deadline, time limit":"期限","degree (temperature)":"度（温度）","degree of comparison":"比较级",
"drunkard, alcoholic":"酒徒","dzo (yak–cow hybrid)":"犏牛","elementary, primary":"初级的",
"equipment, supplies":"装备、物资","expert, professional":"专家","eye (organ of sight)":"眼",
"fate, destiny, luck":"命运","fawn (a young deer)":"幼鹿","female, woman, wife":"女子、妻",
"field tent, pavilion":"帐幕","for; for the sake of":"为了","form, figure, shape":"形体",
"fuse, percussion cap":"引信、火帽","gearwheel, cogwheel":"齿轮","genitive of он (on)":"он（年）的属格",
"glasses, spectacles":"眼镜","glimpse, visibility":"视野、能见度","grade, degree, rank":"等级",
"his; her, hers; its":"他的、她的、它的","holiday, celebration":"节庆",
"hot (in temperature)":"热的","important, precious":"贵重的","information, account":"信息、记述",
"intricate, elaborate":"精细的","jack (playing cards)":"J（纸牌）","jacket, smock, shirt":"上衣",
"legend, myth, fable":"传说、寓言","maggot, insect, bug":"蛆、虫","manpower, workforce":"人力",
"mare (female horse)":"牝马","means of production":"生产资料","memory, recollection":"记忆",
"miscellany, mixture":"杂集、混合","moustache, mustache":"髭","navel, belly button":"脐",
"oblique of нэг (neg)":"нэг（一）的斜格","other than, besides":"除……之外",
"passenger; traveller":"旅客","patience, endurance":"忍耐","punishment, sentence":"刑罚",
"record (vinyl disc)":"唱片","resources, reserves":"资源、储备","role; function; duty":"职能",
"rowan, mountain-ash":"花楸","runny, thin, watery":"稀的","scarce, meager, poor":"匮乏的",
"schedule; timetable":"时刻表","shape, form, figure":"形状","side street":"小街",
"side, flank":"侧翼","sigh":"叹息","sign":"符号、标志","significance, role":"意义、作用",
"silk (fabric)":"丝绸","similar":"相似的","simple":"简单的","singer":"歌手","single":"单个的",
"sixteen":"十六","size (of clothing)":"尺码","ski":"滑雪板","skill, art, manner":"技艺",
"skin":"皮肤","skirt":"裙","skull":"头骨","slave":"奴隶","sledge, sleigh, sled":"雪橇",
"sledgehammer":"大锤","sleeve, arm":"袖","slime; mucus":"黏液","slit (on a garment)":"衣衩",
"slogan, buzz word":"口号","slumgullion":"杂烩汤","small":"小","small temple, shrine":"小庙",
"smile":"微笑","smoke":"烟","snarl":"咆哮","snot":"鼻涕","snow":"雪","snow leopard":"雪豹",
"snuffbox":"鼻烟壶","soap":"肥皂","social rank, title":"身份、名号","socialism":"社会主义",
"society":"社会","sock, stocking":"袜","sofa":"沙发","soil":"土壤","soldier":"士兵",
"some, a certain":"某个","song":"歌","sorry, excuse me":"对不起","sort, type":"种类",
"soul":"灵魂","soup":"汤","source":"来源","source, origin":"源头","south":"南",
"southern":"南方的","soviet":"苏维埃","space; outer space":"太空","spaceship":"宇宙飞船",
"spacious":"宽敞的","spaghetti":"意面","spar":"桅杆","spear, lance":"矛",
"spearhead, arrowhead":"矛头、箭镞","speck of dust":"微尘","speech":"言语、演说",
"speleology":"洞穴学","spicy (to the taste)":"辛辣的","spine, back":"脊背","spleen":"脾",
"spoiled (child)":"娇纵的","spoke":"辐条","spoon":"匙","spring (season)":"春",
"spring, mechanism":"弹簧","sprout, germ, braird":"幼芽","square, plaza":"广场",
"squirrel":"松鼠","stamp":"邮票","stamp, seal":"印章","state":"国家、状态",
"statement, document":"文书","station":"车站","stature, height":"身高","steam":"蒸汽",
"steamed":"蒸的","steamed bread":"馒头","steel":"钢","steelyard":"杆秤",
"steering wheel":"方向盘","step":"步","steppe, field":"草原","stern":"船尾；严厉的",
"stick, cane":"棍杖","stingy, miserly":"吝啬的","stirrup, pedal":"马镫、踏板",
"stock, share":"股份","store, shop":"商店","store, storehouse":"仓库","store, supply":"储备",
"storey; floor":"层","story; tale":"故事","straw":"麦秆","street":"街道",
"strength, power":"力量","strike; walkout":"罢工","string, rope, cord":"绳索",
"strip, band":"带","student":"学生","stupa, pagoda":"塔","subject":"主语、科目",
"subject, object":"主体、客体","success":"成功","suction cup":"吸盘","suddenly":"忽然",
"suffering":"痛苦","sugar":"糖","sugar cube":"方糖","summary":"提要","summer":"夏",
"summon, invite":"召请","sun":"太阳","supermarket":"超市","supplement, addition":"补充",
"supreme":"至高的","surge":"涌动","swimming pool":"游泳池","switch":"开关","sword":"剑",
"syllable":"音节","synonym of ᠰᠢᠷ᠎ᠠ":"ᠰᠢᠷ᠎ᠠ 的同义词","syringe":"注射器",
"system, machine":"系统、机器","tabunang (title)":"塔布囊（爵号）","tadpole":"蝌蚪",
"tail, end, final":"尾、末","task, objective, aim":"任务、目标","taste; palate":"味觉",
"tattoo":"文身","taxi; cab":"出租车","tea":"茶","tear":"泪","technology":"技术",
"telephone":"电话","temple":"庙、寺","temple, monastery":"寺院","tempo, flow":"节奏",
"tender, young":"稚嫩的","tent":"帐篷","test; examination":"考试","textile":"纺织品",
"thank you":"谢谢","that":"那","that; that very one":"那个","that’s":"那就是",
"the beyond":"彼岸","the ellipsis":"省略号","the final round":"决赛","theft":"盗窃",
"their; theirs":"他们的","theory":"理论","therapeutic":"治疗的","these":"这些",
"they":"他们","thick":"厚","thick, viscous":"稠的","thief":"贼","thimble":"顶针",
"thin":"薄","thirst":"渴","thirsty":"渴的","thirteen":"十三","this (the same)":"这（同一个）",
"this, that":"这、那","thousand":"千","thread":"线","thread, filament":"丝、纤维",
"threshing floor":"打谷场","throughout, all over":"遍及","thumb":"拇指","thumb ring":"扳指",
"thyroid gland":"甲状腺","tick (bug)":"蜱","ticket":"票","tie rod, truss":"拉杆、桁架",
"tiger":"虎","tight, tight-fitting":"紧身的","tight; dense":"紧密的","timber, lumber":"木材",
"time (an occurrence)":"次","time (duration)":"时间","tinderbox":"火绒盒","tiny":"微小的",
"tiny, little":"细小的","tissue":"组织","title (of a book)":"书名","tobacco":"烟草",
"tobacco pouch":"烟袋","toe":"脚趾","tofu":"豆腐","toilet, outhouse":"厕所",
"tolerance":"宽容","tomato":"番茄","tome":"卷册","tomorrow":"明天","tongue":"舌",
"too (also)":"也","tool, instrument":"工具","tooth":"牙","tooth of a gear":"齿",
"top":"顶","top quality, choice":"上品","top, end":"顶端","tortoise; turtle":"龟",
"towel":"毛巾","tower":"塔楼","town, city":"城镇","tradition":"传统","traditional":"传统的",
"trail, trace":"踪迹","train (vehicle)":"火车","tram, tramway":"有轨电车","translator":"译者",
"transparent":"透明的","treasure":"宝藏","treasury":"府库","treatment":"处理、治疗",
"treatment, therapy":"疗法","tree":"树","tribal":"部落的","tribe":"部落","trigger":"扳机",
"truck, lorry":"卡车",

# --- verbs ---
"to accept":"接受","to accomplish":"完成","to acknowledge":"承认","to act big":"逞能",
"to add":"添加","to add plies to wood":"给木料加层","to add, to append":"附加",
"to agree (to)":"同意","to allocate":"分配","to approve":"批准","to argue":"争辩",
"to ask":"问","to ask for":"请求","to ask, to inquire":"询问","to avoid, to dodge":"躲避",
"to bake":"烘烤","to be":"是","to be discouraged":"气馁","to be hungry":"饥饿",
"to be in charge":"负责","to be infected":"受感染","to be promoted":"晋升",
"to be served":"受奉侍","to be stubborn":"固执","to be subject to":"受制于",
"to beat (a drum)":"击（鼓）","to become accustomed":"习惯","to become blunt":"变钝",
"to become stiff":"变僵","to begin, to arise":"兴起","to begin, to start":"开始",
"to betray":"背叛","to bind, stitch":"装订","to bind, to bundle":"捆扎",
"to bind, to package":"包扎","to bite":"咬","to blow (nose)":"擤（鼻）",
"to braid, to plait":"编辫","to break":"打破","to break down":"损坏","to breathe":"呼吸",
"to bridge":"架桥","to budget":"编列预算","to burn, to sting":"灼痛","to burp; to belch":"打嗝",
"to bury":"埋葬","to buy":"买","to calculate":"计算","to call":"呼叫","to cane":"杖责",
"to catch with lasso":"套住","to charge":"充电；冲锋","to choose":"选择",
"to chop with an axe":"斧劈","to clamp":"夹紧","to clean, to tidy up":"清理",
"to climb":"攀登","to clip (vegetation)":"修剪","to collect":"收集",
"to compare, contrast":"比较","to compel, to coerce":"强迫","to concur":"赞同",
"to consist, have":"包含","to continue":"继续","to cough":"咳嗽","to count":"计数",
"to curry (a horse)":"刷马","to cut (hair)":"剪（发）","to cut with scissors":"剪",
"to dance":"跳舞","to dare, to venture":"敢","to deem, to treat as":"视为",
"to defeat, to beat":"击败","to defeat, to win":"战胜","to defecate":"排便",
"to defend":"防卫","to delay":"延迟","to describe":"描述","to desert":"遗弃",
"to desire, to want":"想要","to determine, to set":"确定","to devour":"吞食",
"to die, pass away":"死去","to differentiate":"区分","to digest":"消化","to discern":"辨别",
"to do":"做","to do quickly":"赶做","to drag":"拖","to draw closer":"靠近","to dream":"做梦",
"to drink":"喝","to drive":"驾驶","to earn":"赚取","to eat":"吃","to elect":"选举",
"to empathize":"共情","to endure":"忍受","to enter a grapple":"入抱（摔跤）","to erupt":"喷发",
"to exchange":"交换","to expect":"期待","to explain":"解释","to explode, blow up":"爆炸",
"to express, create":"表达、创作","to fall":"落下","to fatten (animals)":"催肥",
"to fear":"畏惧","to feel paralyzed":"发麻","to find, to discover":"发现",
"to finish; to end":"结束","to fix, to correct":"修正","to fly":"飞","to fly (a kite)":"放（风筝）",
"to forget":"忘记","to forgive":"宽恕","to freeze up":"冻住","to fry, to broil":"煎烤",
"to gather, to amass":"聚集","to get accustomed":"习惯于","to get away":"脱身",
"to get inflicted":"遭受","to get stuck, to die":"卡住；毙命","to get warmer":"变暖",
"to get, to obtain":"获得","to give":"给","to give, to grant":"授予","to go by, pass by":"经过",
"to go, leave":"离去","to go, to come":"往来","to go, to leave":"离开","to grab":"抓",
"to grab by":"抓住","to graduate":"毕业","to grapple":"扭抱","to greet":"问候",
"to grow bigger":"长大","to guess":"猜","to hail":"下冰雹","to handle":"处理",
"to hang, to suspend":"悬挂","to hate":"憎恨","to hear":"听见","to herd (cattle)":"放牧",
"to hit with":"以……击打","to hitch a ride":"搭车","to hoarsen":"变哑","to hold":"握持",
"to hold with pliers":"钳住","to hunt":"打猎","to increase, augment":"增加","to infect":"传染",
"to intend, to plan":"打算","to intervene":"干预","to invite":"邀请","to issue, publish":"发行",
"to jump":"跳","to keep vigil":"守夜","to kiss":"亲吻","to kneel":"跪","to knit":"编织",
"to lack":"缺少","to languish":"憔悴","to lash out":"猛击","to laugh":"笑",
"to launch (a rocket)":"发射","to leap; to jump":"跃","to learn, to study":"学习",
"to learn; to study":"学","to lick":"舔","to lie down":"躺下","to link, to connect":"连接",
"to listen":"听","to live":"生活","to live, to reside":"居住","to locate, situate":"定位",
"to look for; to seek":"寻找","to lose":"失去","to love":"爱","to make a promise":"许诺",
"to make known":"公布","to make progress":"进步","to make straight":"弄直",
"to make, produce":"制造","to marry off":"嫁娶","to meditate":"冥想",
"to miss, to pine for":"思念","to mount":"骑上","to near":"接近","to nod":"点头",
"to nod off, to doze":"打盹","to oppress":"压迫","to orate, to lecture":"演讲",
"to overcome":"克服","to overtake":"赶超","to pair":"配对","to pass away":"逝世",
"to pay":"支付","to persevere":"坚持","to plant":"种植","to play, act, joke":"玩耍、戏谑",
"to plead guilty":"认罪","to point":"指","to pray":"祈祷","to prepare as boodog":"作石烹",
"to press":"按压","to proclaim":"宣告","to promise":"承诺","to prophesy":"预言",
"to prostrate":"叩拜","to protect":"保护","to push":"推","to push (a product)":"推销",
"to put pressure on":"施压","to quake, to sway":"震动、摇晃","to read":"读","to receive":"接收",
"to reconcile":"和解","to reflect":"反映、反思","to regret, to repent":"悔悟",
"to release":"释放","to repay":"偿还","to repeat":"重复","to report":"报告","to repress":"镇压",
"to rest":"休息","to retch, to burp":"作呕、打嗝","to return":"返回","to ride (a bus)":"乘（车）",
"to ride (a horse)":"骑（马）","to ride a horse":"骑马","to rise":"升起",
"to rise up, to rebel":"起事","to row":"划船","to rule, to govern":"统治","to run":"跑",
"to run away, flee":"逃跑","to rust":"生锈","to sacrifice":"祭献","to saddle":"备鞍",
"to saw":"锯","to say, speak, tell":"说","to scrape":"刮","to screw in":"拧入",
"to search":"搜寻","to see":"看见","to see off":"送别","to segregate":"隔开","to select":"挑选",
"to sell":"卖","to send":"寄送","to set, fade away":"落下、消退","to shave":"剃",
"to shear (wool)":"剪毛","to shiver":"颤抖","to sing":"唱","to sit":"坐","to sleep":"睡",
"to smile":"微笑","to snarl, to growl":"咆哮","to sneeze":"打喷嚏","to snore":"打鼾",
"to sober up":"醒酒","to spin (thread)":"纺","to spread":"散布","to squander":"挥霍",
"to squeeze out":"挤出","to squeeze, to clamp":"挤压","to stand":"站立","to stand up":"起立",
"to startle, run away":"惊逃","to steal; to rob":"偷、抢","to step":"迈步","to step over":"跨过",
"to stop, to obstruct":"阻止","to stop; to halt":"停下","to store, to stow":"贮存",
"to strangle":"勒死","to subjugate":"征服","to succeed":"成功","to suffice":"足够",
"to supervise":"监督","to swallow":"吞咽","to swell":"肿胀","to swindle":"诈骗",
"to swing (limbs)":"摆动","to swing repeatedly":"反复摆动","to teach":"教",
"to tell lies":"说谎","to test":"检验","to test, to try out":"试验","to think":"思考",
"to throw":"投掷","to throw out":"扔掉","to tie":"系","to tie down":"拴住",
"to tolerate":"容忍","to trade":"贸易","to translate":"翻译","to translate into":"译成",
"to travel":"旅行","to try differently":"另试","to try, to attempt":"尝试","to turn":"转",
"to turn grey":"变灰白","to turn out":"结果是","to turn over":"翻转","to understand":"理解",
"to unite":"联合","to urge, to hurry":"催促","to urinate":"排尿","to use":"使用",
"to use, apply":"运用","to verify":"核实","to visit":"拜访","to vomit":"呕吐","to wait":"等待",
"to wake up":"醒来","to wander, to stroll":"漫步","to want":"想要","to wash":"洗",
"to weave":"织","to weigh":"称重","to whisper":"低语","to win":"获胜","to withstand":"抵住",
"to work":"工作","to worship":"崇拜","to wrap, to fold":"包裹、折叠","to wrestle":"摔跤",
"to write":"写",
}
