#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part F (final batch, 2/2)."""
G = {
# --- places, peoples, titles ---
"Greece (a country in Southeastern Europe)":"希腊","Kazakhstan (a country in Asia and Europe)":"哈萨克斯坦",
"Kazakhstan (a country in Central Asia and Eastern Europe)":"哈萨克斯坦",
"Khalkha (a subgroup of the Mongol people)":"喀尔喀（蒙古族支系）",
"Khamnigans (exonym for the Tungus Evenki)":"哈木尼干（对通古斯鄂温克人的他称）",
"Latvia (a country in northeastern Europe)":"拉脱维亚","Nen River (a river in northeastern China)":"嫩江",
"Ulanqab (a city in Inner Mongolia, China)":"乌兰察布","Ulanqab (a city in the Inner Mongolia autonomous region, China)":"乌兰察布",
"Albania (a country in Southeastern Europe)":"阿尔巴尼亚","Jungar (a banner in Inner Mongolia, China)":"准格尔旗",
"Jungar (a banner in Ordos, Inner Mongolia, China)":"准格尔旗（内蒙古鄂尔多斯）",
"Qinghai (a province in northwestern China)":"青海省","Ulaanbaatar (the capital city of Mongolia)":"乌兰巴托（蒙古国首都）",
"Hohhot (the capital city of Inner Mongolia)":"呼和浩特（内蒙古首府）",
"Manzhouli (a city in Inner Mongolia, China)":"满洲里",
"Manzhouli (a county-level city of Hulunbuir, Inner Mongolia autonomous region, China, on the border with Russia)":"满洲里（内蒙古呼伦贝尔县级市，与俄罗斯接壤）",
"Nalaikh (a district of Ulaanbaatar, Mongolia)":"那来哈（乌兰巴托辖区）",
"Bor-Öndör (a city in Khentii Province, Mongolia)":"包尔温都尔（蒙古国肯特省）",
"Iraq (a country in West Asia in the Middle East)":"伊拉克","Syria (a country in West Asia in the Middle East)":"叙利亚",
"China (a region and country in East Asia), Cathay":"中国、契丹（旧称）",
"Züünkharaa (a city in Selenge Province, Mongolia)":"准哈拉（蒙古国色楞格省）",
"Bayats (Oirat-Mongolian tribe, vassal of the Dörbets)":"巴雅特（卫拉特蒙古部，杜尔伯特属部）",
"Kharkhorin (a city in Övörkhangai Province, Mongolia)":"哈拉和林（蒙古国前杭爱省）",
"United States of America (a country in North America)":"美利坚合众国",
"Inner Mongolia (a Mongolian autonomous region of China)":"内蒙古自治区",
"Altay, Altai (a mountain range in Central and East Asia)":"阿尔泰山",
"Hejing (a county of Bayingolin prefecture, Xinjiang, China)":"和静县（新疆巴音郭楞州）",
"Lhasa (the capital city of the Tibet Autonomous Region, China)":"拉萨（西藏自治区首府）",
"Slovenia (a country on the Balkan Peninsula in Central Europe)":"斯洛文尼亚",
"Bulgan (a city, administrative center, and province of Mongolia)":"布尔干（蒙古国省及首府）",
"Andorra (a microstate in Southern Europe, between Spain and France)":"安道尔",
"Qing (Qing dynasty (1644–1912), the last imperial dynasty of China)":"清朝（1644–1912，中国最后一个王朝）",
"Dzungaria (a geographical region [geologically basin] in inner Asia)":"准噶尔（内亚地理区域，地质上为盆地）",
"Russia (a transcontinental country in Eastern Europe and North Asia)":"俄罗斯",
"Beijing (a direct-administered municipality, the capital city of China)":"北京（中国首都、直辖市）",
"Ölgii (a city, the administrative center of Bayan-Ölgii Aimag, Mongolia)":"乌列盖（蒙古国巴彦乌列盖省首府）",
"Spain (a country in Southern Europe, including most of the Iberian peninsula)":"西班牙",
"Qinghai, Qinghai Lake (a large lake in Qinghai province, the largest in China)":"青海湖（中国最大湖泊）",
"Arxan (a county-level city of Hinggan, Inner Mongolia autonomous region, China)":"阿尔山（内蒙古兴安盟县级市）",
"Tibet (a geographic region in Central Asia, the homeland of the Tibetan people)":"吐蕃、西藏（中亚地区，藏人故土）",
"Holingol (a county-level city of Tongliao, Inner Mongolia autonomous region, China)":"霍林郭勒（内蒙古通辽县级市）",
"Hoh Xil (an isolated region in the northwestern part of the Tibetan Plateau in China.)":"可可西里（青藏高原西北部无人区）。",
"Macau (a city, special administrative region, and peninsula in China, west of Hong Kong)":"澳门（中国特别行政区）",
"Denmark (a country in Northern Europe; official name: Данийн Хаант Улс (Daniin Xaant Uls))":"丹麦（正式名 Данийн Хаант Улс）",
"South Korea (a country in East Asia, comprising the southern part of the Korean Peninsula)":"韩国",
"Belgium (a country in Western Europe that has borders with the Netherlands, Germany, Luxembourg and France)":"比利时",
"Georgia (a transcontinental country in the Caucasus region of Europe and Asia, on the coast of the Black Sea)":"格鲁吉亚",
"Armenia (a country in the South Caucasus region of Asia, sometimes considered to belong politically to Europe)":"亚美尼亚",
"Netherlands (the main constituent country of the Kingdom of the Netherlands, located primarily in Western Europe bordering Germany and Belgium)":"荷兰（荷兰王国主体构成国）",
"Netherlands (a country in Western Europe, consisting of four constituent countries: the Netherlands per se, Aruba, Curaçao and Sint Maarten the Kingdom of the Netherlands)":"荷兰王国（由荷兰本土、阿鲁巴、库拉索、圣马丁四个构成国组成）",
"Manchuria (a region of northeastern China comprising the three provinces of Liaoning, Jilin, and Heilongjiang and the northeastern part of Inner Mongolia)":"满洲（辽宁、吉林、黑龙江三省及内蒙古东北部）",
"America, the Americas (a supercontinent consisting of North America, Central America and South America regarded as a whole; in full, the Americas); America, United States of America (a country in North America; in full, United States of America)":"美洲；美国",
"America, the Americas (a supercontinent consisting of North America, Central America and South America regarded as a whole; in full, the Americas); America, the Americas (a supercontinent consisting of North America, Central America and South America regarded as a whole; in full, the Americas)":"美洲",
"Ethnic Russians born in Mongolia, who speak Mongolian as their first language.":"生于蒙古国、以蒙古语为母语的俄罗斯族人。",
"taiji (Mongolian noble title, originally for Genghisids only)":"台吉（蒙古爵号，原限成吉思汗后裔）",
"A noble title given to the commander of a ᠬᠣᠰᠢᠭᠤ (qosiɣu)":"授予旗（ᠬᠣᠰᠢᠭᠤ）统领的爵号",
"a male given name, or honorific title: Genghis":"男子名或尊号：成吉思",
"(⁓ хүн) A member of each three tribes listed above":"（⁓ хүн）上列三部之人",
"(⁓ аймаг) Dörböds, an Oirat-Mongol tribe ruled by Esen’s descendants of the Choros clan":"（⁓ аймаг）杜尔伯特，绰罗斯氏也先后裔所统的卫拉特蒙古部",
"(⁓ аймаг) Dorbods, an Aru-Mongol tribe ruled by Hasar’s descendants of the Borjigit clan":"（⁓ аймаг）杜尔伯特，孛儿只斤氏哈萨尔后裔所统的阿鲁蒙古部",
"(⁓ аймаг) Dorbods, another Aru-Mongol tribe ruled by Hasar’s descendants, which was originally called дөрвөн хүүхдийн аймаг (dörvön xüüxdiin ajmag, literally “tribe of the four sons”)":"（⁓ аймаг）另一支哈萨尔后裔所统的阿鲁蒙古杜尔伯特部，原称 дөрвөн хүүхдийн аймаг（字面义「四子部」）",

# --- grammar ---
"Marks the first person plural possession.":"标记第一人称复数领属。",
"Marks the first person singular possession.":"标记第一人称单数领属。",
"Marks end of a passage, paragraph, or chapter":"标记段落或章节的结束",
"Marks start of a book, chapter, passage, or first line":"标记书、章、段或首行的开始",
"Postconsonantal marker of the instrumental case.":"辅音后的工具格标记。",
"Postconsonantal marker of the definite accusative case.":"辅音后的定指宾格标记。",
"Postvocalic suffix forming the genitive of a substantive.":"元音后构成体词属格的后缀。",
"Forms locational adverbs from spatial roots":"由空间词根构成处所副词",
"Noun-forming suffix of indeterminable meaning":"意义不明的名词后缀",
"Seldom used suffix which forms nouns out of verbs":"少用的动词转名词后缀",
"Forms nouns denoting places or results of an action.":"构成表处所或动作结果的名词。",
"forms action nouns and abstract nouns out of verbs":"由动词构成动作名词与抽象名词",
"Forms mostly adjectives and sometimes nouns denoting result, from verbs.":"由动词构成表结果的形容词，偶亦构成名词。",
"forms adjectives from verbs, denoting most commonly the manner in which a thing has been created.":"由动词构成形容词，多表事物形成的方式。",
"forms adjectives from nouns and verbs, with the meaning of \"with.\" Sometimes referred to as ornative.":"由名词与动词构成形容词，义为「带有」，或称具有格。",
"Forms the cooperative voice, i.e. verbs that indicating taking part in an action or helping it.":"构成共同式，即表示参与或协助某动作的动词。",
"Forms the adversative voice, i.e. verbs that indicate actions happpening against each other, not necessarily negative.":"构成交互式，即表示彼此相向而行的动作，未必含贬义。",
"Dative-locative case marker equating to to, at, or in in English. It is used to show the indirect object of a sentence, or to indicate the time or the place an action will happen.":"与位格标记，相当于英语的 to、at、in，用以表示间接宾语，或动作发生的时间与地点。",
"indicates that the subjects of the main and the subordinate clauses are the same.":"表示主句与从句主语相同。",
"final interrogative particle that creates yes-no questions":"构成是非问句的句末疑问助词",
"every, -ever, any- (after interrogative pronouns)":"每、任（接疑问代词后）",
"no-, any- (after interrogative pronouns, used with a negative verb)":"任何……都不（接疑问代词后，与否定动词连用）",
"in (appearing in writing, recording or other media)":"载于（文献、录音等）",
"to keep doing, denotes continuative aspect":"持续做，表持续体",
"into pieces, denotes a specific grade violence and perfectivity with verbs of breaking.":"成碎片；与破裂类动词连用时表某种程度的猛烈与完成。",
"to possess a quality, to possess a quality to an excessive degree, more than suitable.":"具有某性质，或过度具有某性质。",
"Used only in ᠿᠢ (ři) to transliterate the Mandarin syllables rī and rì.":"仅用于 ᠿᠢ（ři），转写官话音节 rī、rì。",
"Used only in ᡁᠢ (ži) to transliterate the Mandarin syllables zhī, zhí, zhǐ and zhì.":"仅用于 ᡁᠢ（ži），转写官话音节 zhī、zhí、zhǐ、zhì。",
"Used only in ᡂᠢ (č̭i) to transliterate the Mandarin syllables chī, chí, chǐ and chì.":"仅用于 ᡂᠢ（č̭i），转写官话音节 chī、chí、chǐ、chì。",
"Used at the start or end of an isolated lexeme to denote that it is orthographically attached to a stem.":"置于孤立词素首尾，表示其在正字法上附着于词干。",
"Extends the stem between letters.":"在字母间延展词干。",
"a hook-like terminal form of Mongol script ᠢ (i)":"蒙文 ᠢ(i) 的钩状词末形",
"archaic dative–locative of ᠣᠨ (on, “year”)":"ᠣᠨ（on，年）的古体与位格",
"suppletive exclusive genitive of ᠪᠢᠳᠡ (bide, “we”): our":"ᠪᠢᠳᠡ（bide，我们）的补充式排除性属格：我们的",
"him; her; it (genitive of тэр (ter, “he, she, it”))":"他的、她的、它的（тэр 的属格）",
"them (genitive of тэд (ted, “they”), genitive of тэд нар (ted nar, “they”))":"他们的（тэд / тэд нар 的属格）",
"you (subject pronoun: the person being addressed)":"你（主格代词）",
"only used in амь зуух (amʹ zuux, “to make a living”)":"仅用于 амь зуух（谋生）",
"only used in хурал хуй (xural xuj, “meeting, assembly”)":"仅用于 хурал хуй（会议）",
"nonstandard form of уйгуржин (ujguržin, “Uyghurjin script”)":"уйгуржин（回鹘式蒙文）的非规范形",

# --- everything else ---
"a large needle for sewing leather or felt":"缝皮毡用的大针","a small ring used for fastening something":"固定用的小环",
"government; administration, state, regime":"政府、政权","sail (piece of fabric attached to a boat)":"帆",
"to oppress, to suppress, to clamp down on":"压制","to reach, to arrive at; to come to an age":"到达；及龄",
"to slip out, to escape (by going upwards)":"向上脱出","to throw out in sequence, to throw around":"接连抛掷",
"tomb or sepulchre in the shape of a stupa":"塔形墓","be allotted (with the recipient in dative)":"被分予（受者用与格）",
"benevolence; kindness; charity; compassion":"仁慈、悲悯","board, panel; writing board, drawing board":"写字板、画板",
"buuza (Mongolian variant of Chinese baozi)":"包子（蒙古式）","deed, action (action performed by someone)":"行为",
"inscription, engraving, exergue, scripture":"铭文、镌刻","khan, emperor; of a khan, khan’s; imperial":"汗、皇帝；汗的",
"plant (organism capable of photosynthesis)":"植物","to bite, to swallow, to devour in one bite":"一口吞下",
"to know (information, how to do something)":"知道、会","to remember (to keep in memory, to recall)":"记得",
"to sweep (to clean using a broom or brush)":"扫","to twirl between the fingers (hair, paper)":"用手指捻",
"autonomous banner (administrative division)":"自治旗","brand (a mark burned onto an animal's skin)":"烙印",
"grocery store, market, supermarket, grocery":"食杂店","hammer (both hand and mechanically powered)":"锤",
"slag (impurities removed when smelting ore)":"炉渣","step (of stairs), rung (of a ladder), pedal":"台阶、梯级、踏板",
"streetcar, trolley, trolley car, light rail":"有轨电车","to catch with a hook (or a similar utensil)":"用钩钩取",
"to lose (a thing, an ability, a quality...)":"失去","to remember (to commit something to memory)":"记住",
"to streak (draw a line with a sharp object)":"划线","to think (to contemplate, to hold a belief)":"思、认为",
"arm, hand (from the shoulder to the fingers)":"臂、手","breeches, pantaloon, pants, slacks, trousers":"裤",
"formation, construction, building, structure":"构造、建筑","khata (traditional Tibetan ceremonial scarf)":"哈达",
"lack, deficiency, difficulty, hardship, want":"匮乏、艰难","leaf (of a door, window) (the moveable part)":"（门窗的）扇",
"pure, clear, clean, holy, hygienic, sanitary":"洁净、圣洁的","to butt, to bump (with horns, forehead, ...)":"抵撞",
"A mouse (input device to operate a computer).":"鼠标。","any film forming on the surface of a beverage":"饮品表面结的膜",
"body (physical structure, coherent structure)":"体、结构体","motes (particles of dust visible in sunbeams)":"光柱中的尘埃",
"padding put on a back of a load bearing camel":"驮驼背上的垫","to grow indifferent, to stop paying attention":"变得漠然",
"aforementioned, the given, the same, specified":"上述的、该","contrary, stubbornly antagonistic, disobedient":"执拗违逆的",
"doughnut, fritter (fried sweet piece of dough)":"油炸甜面团","fact (something actual as opposed to invented)":"事实",
"material (necessary ingredients for a process)":"原料","space; space (a set with additional structure)":"空间（数学）",
"to open; to commence (a conference, a meeting)":"开（会）","to suddenly let out (a sound, sweat, tears...)":"突然发出（声、汗、泪）",
"claw (a foot or paw equipped with a sharp nail)":"利爪","device, method (rhetorical, social, industrial)":"手法、装置",
"face; image; front; façade, facade; page; title":"面、正面、页、标题","herd, flock, pack (of cattle, birds, wolves...)":"群",
"to lace, to fasten (shoes, wall of a yurt, ...)":"系扎","to miss (an opportunity, a meeting, a deadline)":"错过",
"to understand, to get (an idea, a concept, ...)":"领会","brush (for applying paint, makeup, plaster, ...)":"刷、笔",
"here, herein, herewith, hereinto, there, therein":"于此、于其中","outdoors, outside, al fresco, external, exterior":"户外、外部的",
"sunny, fair, sun-drenched, shiny, bright, sunlit":"晴朗明亮的","to bite (to hold in teeth, to attack with teeth)":"咬",
"to boast of being knowledgeable (when one isn't)":"不懂装懂","to compose, compile, blend, stage, produce, edit":"编撰、编排",
"to enter a state (of fear, illness, laughter...)":"陷入（恐惧、疾病、大笑等）","to place the foundation of, to set, to establish":"奠基、设立",
"clerk, copyist, scribe, scrivener, typist, writer":"书吏、抄手","material (substance out of which a thing is made)":"材料",
"to avoid, to evade (an affair, saying a thing...)":"回避","to grip, to clamp (with pliers or a similar tool)":"钳夹",
"tomb, mausoleum, vault, burial chamber, sepulcher":"陵墓、墓室","\"baavar\" round plates or disks on the saddle cloth":"鞍鞯上的圆片「baavar」",
"container, vessel, vase, receptacle, crockery, bag":"容器、器皿","dye; pigment; colouring, coloring; paint; antimony":"染料、颜料",
"rabid (affected with rabies, pertaining to rabies)":"狂犬病的","sheath, scabbard, holster (for a blade, gun, etc.)":"鞘、枪套",
"suit (suit of clothes, men’s suit or women’s suit)":"套装","to be set off, to be stirred (of emotional states)":"（情绪）被触动",
"part of the arrow directly underneath the arrowhead":"箭镞下方的部分","range, limit, sphere (of influence, knowledge, ...)":"范围、界限",
"stew, huurga (dish prepared by frying or simmering)":"炒炖菜（huurga）","to abandon, to quit (a habit, schooling, work, ...)":"戒除、放弃",
"to enroll in, partake in (a class, a monastery, ...)":"入（学、寺）","crupper (a leather strap looped under a horse's tail)":"鞧带",
"hair (both as a single filament or collectively); fur":"毛、皮毛","hair (both as a single filament or collectively); body hair":"体毛",
"hair (both as a single filament or collectively); scalp hair":"头发","job, work, activity, business, employment, occupation":"工作、职业",
"report (act of presenting oneself to one's superiors)":"禀报","to open; to create, to establish (an account, a mine)":"开设（账户、矿）",
"dear (addressing someone at the beginning of a letter)":"亲爱的（书信抬头）","kind, sort, variety, type, class, item, article, thing":"种类、条目",
"short, small (most commonly in plant and animal names)":"矮小的（多见于动植物名）","the Horse (zodiac, one of the twelve Earthly Branches)":"午（十二地支之一）",
"to scratch; to rub the skin in order to remove itching":"搔痒","business, affairs (dealings and interests of an entity)":"业务、事务",
"thought, thinking, idea, intention, conception, opinion":"思想、意图","to test (to inspect proper functioning or knowledge of)":"测试",
"number, numeral, figure, digit, count, account, quantity":"数、数量","to fasten, sew on or otherwise attach loosely or hastily":"草草缝缀",
"tsuivan (noodle stew with mutton or beef and vegetables)":"炒面片（tsuivan）","A type of song or poem which praises its subject; an ode.":"赞歌、颂诗。",
"bond, rope, binding (that which is used to tie something)":"绳缚之物","order, routine, principle, rules, system, procedure, form":"秩序、规程",
"to patch, act as a substitute, make up for, catch up with":"补缀、顶替、补上","to throw in, to add something to an item offered for sale":"搭头、附赠",
"a person with poor skill (with respect to some discipline)":"某方面手艺欠佳者","saddle-gall (sore on an animals back caused by the saddle)":"鞍疮",
"team, group, mask, cloak, brigade, contingent, gang, troop":"队伍、班组","a long-stemmed Mongolian pipe; pipe (smoking); tobacco pipe":"蒙古长杆烟斗",
"cow, ox (domestic bovine, bovine used as a beast of burden)":"牛（家畜、役畜）","to expect, preconceive (to have a previous apprehension of)":"预料",
"a kind of dessert prepared from sweetened, caramelized cream":"焦糖奶油甜食","order of fixtures in a tournament (chosen by lot), allotment":"抽签定出的赛次",
"to dwell, reside, exist, inhabit, live, abide, be, be inside":"居住、存在","customs, traditions, etiquette, legislation, habit, formality":"习俗、礼法",
"medicine, medication, drug, preparation, remedy, pill, potion":"药物","precipitation (water falling from the atmosphere in any form)":"降水",
"sale, trade, traffic, negotiation, trading, bidding, operation":"买卖、交易","fried dumpling filled with minced meat and seasoning; khuushuur":"馅饼（khuushuur）",
"mouth (the opening of an animal through which food is ingested)":"口","report (a written or spoken account of events or circumstances)":"报告",
"strike plate, keeper (part of the doorjamb which receives bolt)":"门锁扣板","to perform the traditional New Year greeting; to perform Zolgokh":"行拜年礼（Zolgokh）",
"dressed sheep carcass served on special occasions (weddings, ...)":"整羊（婚宴等场合）","opinion, understanding, consciousness (approach to actual events)":"见解、认识",
"thimble (cap for the fingers, used in sewing to push the needle.)":"顶针。","economy (the system of production and distribution and consumption)":"经济",
"to be servile, to run errands, to be spent, selling, to be sold out":"奔走供役；售罄","One of four sides of the ankle bone dice used in Monglian folk games":"蒙古游戏中羊拐骰的四面之一",
"breeching (a part of a harness strapped around a pack animal's rump)":"鞧带（挽具围臀部分）","deel (a traditional Mongolian cloak, traditionally worn with a sash)":"蒙古袍（deel，配腰带）",
"koumiss (a popular Mongolian drink made from fermented mare’s milk).":"马奶酒。","a year of the Ox (the second year under the twelve-year lunar cycle.)":"丑年（十二年周期第二年）。",
"cross-breed, hybrid (organism produced by mating of different breeds)":"杂交种","year of the sheep, the second year under the twelve-year lunar cycle.":"未年（十二年周期第二年）。",
"A kind of smoke ritual in which incense or juniper branches are burnt.":"焚香或柏枝的烟祭。","camp, landing, station, stay, stop, stage, landing stage, rocket stage":"营地、站、级",
"mind, intellect, wits, consciousness, wisdom, knowledge, meaning, idea":"心智、智慧、意涵","offering of the best (first) part of the meal (to gods, to guests,...)":"献给神灵或宾客的头一份",
"desert (an extremely dry area of land hostile to animal and plant life)":"沙漠","party (a group or an individual involved in a transaction or a dispute)":"当事方",
"closed, deaf, dense, impenetrable, impermeable, recondite, solid, stuffy":"闭塞、不透的","affair, case (an event or a set of events taken as an object of interest)":"事件、案件",
"headland, neck (narrow piece of dry land projecting into a body of water)":"岬角","terrestrial, cosmopolite, planetary, secular, worldly, earthen, worldwide":"尘世的、全球的",
"avail, boost, help, helping, adjuvancy, aid, benefit, helping hand, succour":"助益","to gain, to obtain, to accumulate (fat, greys, experience, understanding, ...)":"积累（膘、白发、经验、见识）",
"a ritual vase holding holy water, made of metal with a long neck and no handles":"长颈无耳的金属圣水瓶","declaration, advertisement, notification, announcement, poster, ticket, placard":"公告、广告",
"to compete (in wrestling, horse racing, ...) as a preparation for наадам (naadam)":"为那达慕而赛（摔跤、赛马等）","diminutive, elvish, little, measly, teeny, tiny, wee, miniature, piccaninny, pygmy":"微小的",
"state, country, nation; A syntactic head added to untitled full official state names":"国家；亦作正式国名的句法中心词",
"huitsaa soup (of cabbage, green onions, fried potatoes, carrots, celery and meatballs)":"huitsaa 汤（卷心菜、葱、炸土豆、胡萝卜、芹菜与肉丸）",
"price, cost, estimate, rate, tariff, value, worth, charge, denomination, expense, bill":"价格、费用",
"talent; skill; gift; aptitude; an ability to do something; the capacity to do something":"才能",
"cookie (small, sweet, flat, circular, baked good which is either crisp or soft but firm)":"曲奇",
"short for ᠴᠢᠰᠤᠨ\nᠬᠢᠮ᠎ᠠ (čisun qim-a, “blood sausage”); ᠬᠢᠮ᠎ᠠ (čisun qim-a, “blood sausage”)":"ᠴᠢᠰᠤᠨ ᠬᠢᠮ᠎ᠠ（血肠）的简写",
"reliable, tenacious, hardy, sturdy, tough, steadfast, rooted, strong, powerful, solid, robust":"坚实可靠的",
"subdistrict, bag, bagh (the smallest civil administrative unit in the Mongolian governance system)":"巴格（蒙古国最基层行政单位）",
"external, exterior, foreign, outer, outlying, extrinsic, peripheral, superficial, oversea, overseas":"外部的、对外的",
"light (in weight), easy, airy, wakeful, soft, gentle, frothy, giddy, gossamer, kindly, mild, unsteady":"轻的、轻柔的",
"A Mongolian lute-like traditional musical instrument, similar to Chinese sanxian and Japanese shamisen":"蒙古传统弹拨乐器，类似汉族三弦与日本三味线",
"mine; excavation from which ore is extracted along with buildings and equipment used by the mining crew":"矿山（含井巷与地面设施）",
"orphan (a person or an animal whose parents have died or are otherwise permanently separated from them)":"孤儿、失亲的幼畜",
"yatga, a traditional Mongolian plucked bridge zither (a stringed musical instrument played horizontally)":"雅托噶（蒙古筝）",
"younger sibling or cousin (often used to refer to other blood relatives and acquaintances who are younger)":"弟妹（亦泛称年幼的亲友）",
"a leather bag for holding liquid (usually used for fermenting dairy products) wineskin, waterskin, goatskin":"皮囊（多用于发酵乳制品）",
"giant, gigantic, colossal, enormous, gargantuan, mountainous, prodigious, great, elephantine, huge, titanic":"巨大的",
"bulbous chamber on an arrow directly underneath the arrowhead that produces a whistling sound during flight.":"箭镞下的球形哨腔，飞行时发声（响箭）。",
"Moon (the Earth's moon; the sole natural satellite of the Earth, represented in astronomy and astrology by ☾)":"月球",
"shagai (ankle bone of a sheep or goat which used in traditional Mongolian games and divination practices as a die)":"沙嘎（羊拐，用于蒙古传统游戏与占卜的骰子）",
"sum (sometimes somon, sumon or sumu) (the second-level civil administrative unit in the Mongolian governance system)":"苏木（蒙古国二级行政单位）",
"alimentation, eats, feed, food, foodstuff, mess, meal, meat, nutriment, nourishment, nutrition, provision, ration, victuals":"食物、给养",
"synonym of ᠰᠢᠷ᠎ᠠ\nᠠᠶᠢᠷᠠᠭ (sir-a ayiraɣ, “beer”, literally “yellow koumiss”); ᠠᠶᠢᠷᠠᠭ (sir-a ayiraɣ, “beer”, literally “yellow koumiss”)":"ᠰᠢᠷ᠎ᠠ ᠠᠶᠢᠷᠠᠭ（啤酒，字面义「黄马奶酒」）的同义词",
"consul (official residing in major foreign towns to represent and protect the interests of the merchants and citizens of their country)":"领事",
"five animals (five types of livestock which form the basis of Mongolian traditional nomadic economy: horse, camel, cow, sheep and goat)":"五畜（马、驼、牛、绵羊、山羊）",
}
