#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part A (A–G of the short list).

Scope is the traditional-script core — the 2126 entries that carry an attested
ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ spelling. Merged by merge_mn_glosses.py.
"""
G = {
# --- proper nouns, peoples, religion ---
"Afrikaans language":"南非荷兰语","American":"美国人","Barag (person)":"巴尔虎人",
"Bayat (person)":"巴雅特人","Borjigin":"孛儿只斤","Buddha":"佛","Chinese":"汉人、汉语",
"English":"英语","German":"德语","Genghis Khan":"成吉思汗","ID card":"身份证",
"Irtysh (river)":"额尔齐斯河","Islam":"伊斯兰教","Jurchen (person)":"女真人",
"Jurchens (people)":"女真","Latin alphabet":"拉丁字母","Manchu":"满洲、满语",
"Mongolian":"蒙古语","Muslim":"穆斯林","Muslim peoples":"穆斯林诸族","Roman":"罗马的",
"Russian":"俄罗斯人、俄语","Tartar":"鞑靼","Tatar":"鞑靼","Tibetan script":"藏文",
"Sukhavati":"极乐净土","Tuva, Tyva":"图瓦","Siberian ibex":"北山羊","Strix":"林鸮属",
"a Russian (person)":"俄罗斯人","Friday":"星期五","Sunday":"星期日","SMS":"短信",
"autonomous region":"自治区","embassy":"大使馆","dukkha":"苦（佛教）",

# --- morphology / grammar ---
"-ize, to make into":"使成为……（后缀）","-logy":"……学（后缀）",
"dative of он (on)":"он（年）的与格","agglutinative":"黏着的","adverb":"副词",
"conjugation":"动词变位","aspect":"体（语法）","dialect":"方言","dialectology":"方言学",
"figure of speech":"修辞格","full stop, period":"句号","comma":"逗号",
"alphabet":"字母表","gender; sex":"性别","composite":"复合的","composition":"构成、作文",
"comprehensive":"综合的","doctrine, -ism":"学说、主义",

# --- verbs ---
"To become bright":"变亮","To freeze":"结冰、冻结","To generalize":"概括",
"To legalize":"使合法化","To stay over":"留宿","To stay the night":"过夜",
"A rattling sound.":"咔嗒声。",

# --- people, kinship, society ---
"a male given name":"男子名","a nobleman":"贵族","daughter":"女儿",
"daughter-in-law":"儿媳","dad":"爸爸","father":"父亲","family":"家庭",
"child":"孩子","child; kid (minor)":"儿童","childhood":"童年","childish":"孩子气的",
"boy":"男孩","bride":"新娘","couple":"夫妇","companion":"同伴","comrade":"同志",
"friend":"朋友","friendship":"友谊","friendship, trust":"友谊、信任",
"client":"委托人","client; customer":"顾客","consumer":"消费者","enemy; foe; rival":"敌人、对手",
"beggar":"乞丐","bandit":"匪徒","captive; prisoner":"俘虏","dictator":"独裁者",
"actor; artist":"演员、艺人","artist; painter":"画家","author; writer":"作者",
"archer":"射手","carpenter":"木匠","cook; chef":"厨师","driver":"司机",
"fisherman; fisher":"渔夫","barber, haircutter":"理发师","duke":"公爵",
"elderly man":"老者","general":"将军","ally":"盟友","council; board":"理事会",
"company; firm":"公司","federation":"联邦","election":"选举","court":"法庭",
"affiliation":"隶属","attendance":"出席","biography":"传记",

# --- body ---
"body":"身体","head":"头","brain":"脑","forehead":"额","chin":"下巴","ear":"耳",
"finger":"手指","big toe":"拇趾","fist":"拳","elbow":"肘","ankle":"踝",
"foot":"脚","foot, leg":"脚、腿","breast":"乳房","bosom":"胸怀","blood":"血",
"bone marrow":"骨髓","cartilage":"软骨","fibula (calf bone)":"腓骨","calf (muscle)":"腓肠肌",
"anus":"肛门","earwax":"耳垢","body odour":"体味","dandruff":"头皮屑",
"facial hair, beard":"胡须","claws, talons":"爪","corpse":"尸体","fetus":"胎儿",
"blood relation":"血亲","death":"死亡",

# --- animals ---
"bear":"熊","cow":"母牛","cat":"猫","camel musk":"驼香","deer":"鹿","a male deer":"牡鹿",
"donkey foal":"驴驹","foal (baby horse)":"马驹","calf":"牛犊","billy goat":"公山羊",
"fox":"狐","corsac fox":"沙狐","crow":"乌鸦","crane":"鹤","duck":"鸭",
"eagle":"雕","falcon":"隼","eared owl":"角鸮","black grouse":"黑琴鸡","bird (animal)":"鸟",
"fish":"鱼","frog, toad":"蛙、蟾","crab":"蟹","crayfish":"螯虾","dolphin":"海豚",
"eel":"鳗","ant":"蚂蚁","bedbug, bug":"臭虫","beetle":"甲虫","butterfly":"蝴蝶",
"caterpillar track":"履带","cockroach":"蟑螂","cricket (insect)":"蟋蟀",
"crocodile":"鳄鱼","a female otter":"母水獭","field rat, mouse":"田鼠",
"gazelle":"羚羊","egg":"蛋","feather":"羽毛",

# --- nature, place ---
"air":"空气","earth":"地球、土","earth, land":"土地","east":"东","eastern":"东方的",
"cave":"洞穴","cliff, ravine":"崖、峡","coast":"海岸","beach":"海滩","continent":"大陆",
"country, territory":"国土","county":"县","distance":"距离","depth":"深度",
"climate":"气候","fog, mist":"雾","dew":"露","drought":"旱灾","flood":"洪水",
"dzud":"白灾（蒙古雪灾）","famine":"饥荒","dust":"尘土","dirt, turf":"泥土、草皮",
"clay":"黏土","coal":"煤","chalk":"白垩","amber":"琥珀","emerald":"祖母绿",
"arsenic":"砷","atom":"原子","acid":"酸","brass (metal)":"黄铜","bronze":"青铜",
"deposit (of ore)":"矿床","cosmos, space":"宇宙、太空","galaxy":"星系",
"constellation":"星座","century":"世纪","calendar":"历法","almanac":"历书",
"chronology":"年代学","chronicle":"编年史","autumn, fall":"秋","evening":"傍晚",
"day":"日","future":"未来","forever":"永远","eternal":"永恒的","age":"年龄",
"ago":"以前","after, afterwards":"之后","afterwards":"随后","again":"再",
"birch":"桦","aspen":"山杨","bamboo":"竹","branch":"树枝","branch; of a tree":"树枝",
"dried tree resin":"干树脂","ephedra":"麻黄","field":"田地","farm":"农场",
"furrow":"垄沟","garden":"花园","confluence":"汇流处","dike":"堤",

# --- food ---
"apple":"苹果","almond":"杏仁","banana, plantain":"香蕉","barley":"大麦",
"blackcurrant":"黑加仑","cabbage":"卷心菜","carrot":"胡萝卜","cherry":"樱桃",
"chestnut":"栗","chili pepper":"辣椒","chocolate":"巧克力","coconut":"椰子",
"coffee":"咖啡","cucumber":"黄瓜","cumin":"孜然","ginger":"姜","ginger (plant)":"姜（植物）",
"cheese":"奶酪","butter":"黄油","bread":"面包","flour":"面粉","beer":"啤酒",
"candy":"糖果","cookie":"饼干","chewing gum":"口香糖","boiled dumpling":"水饺",
"barbecue":"烧烤","food, provisions":"食物、口粮","feast":"宴席","banquet, feast":"宴会",
"fat":"脂肪","fat, grease":"油脂","fatty, greasy":"油腻的",

# --- things ---
"abacus":"算盘","album":"相册、专辑","anchor":"锚","arrow notch":"箭括",
"axe, hatchet":"斧","battle axe":"战斧","backpack":"背包","ball":"球",
"bed":"床","bedsheet":"床单","a (thick) mattress":"厚褥","blanket":"毯子",
"bell":"铃","bellows":"风箱","belt":"腰带","bench (set)":"长凳","bicycle":"自行车",
"bomb":"炸弹","bolt":"门闩","book":"书","book binding":"装订","boot":"靴",
"bottle":"瓶","bowstring":"弓弦","bridle":"马笼头","a part of a bridle":"笼头部件",
"broom":"扫帚","brush":"刷子","bucket":"桶","bundle":"捆","bundle, faggot":"柴捆",
"bus, motorbus":"公共汽车","button (fastener)":"纽扣","button (switch)":"按钮",
"cage":"笼","camera":"相机","candle":"蜡烛","cane":"手杖","cane, rod, pole":"杖、杆",
"cane, stick":"手杖","card, map, chart":"卡片、图表","cargo, goods":"货物",
"cauldron":"大锅","chain":"链","chair":"椅子","chess":"棋","chisel":"凿",
"chopstick":"筷子","cigarette":"香烟","cigarette holder":"烟嘴","clothes, clothing":"衣服",
"cloth":"布","cloth; fabric":"织物","fabric, textile":"纺织品","coat of arms":"纹章",
"coin":"硬币","comb":"梳子","computer":"计算机","concrete":"混凝土","condom":"避孕套",
"conveyor":"传送带","cotton":"棉","credit card":"信用卡","die, dice":"骰子",
"doll, puppet":"玩偶","door":"门","drill":"钻","drinking straw":"吸管",
"electric plug":"插头","elevator, lift":"电梯","enamel":"珐琅","engine":"发动机",
"engine, motor":"引擎","eraser":"橡皮","fax":"传真","felt":"毡","fetters":"镣铐",
"file":"锉；文件","film":"影片","firearm":"火器","firecracker":"爆竹","fife":"横笛",
"flag":"旗","fork":"叉","furniture":"家具","game, toy":"玩具","gasoline, petrol":"汽油",
"gate":"门、大门","bass viol":"低音提琴","cello":"大提琴","chord":"和弦",
"breastplate":"胸甲","a small boat":"小船","ferry":"渡船","a lamp offering":"供灯",
"a wrestling move":"摔跤招式","a wrestling title":"摔跤称号","a source":"来源",
"a small monastery":"小寺院","church":"教堂","castle":"城堡","circus":"马戏团",
"ceremony hall":"礼堂","corridor":"走廊","bathroom; toilet":"卫生间","alley":"小巷",
"bridge":"桥","airplane":"飞机","airport":"机场","advertisement":"广告",

# --- abstract ---
"above":"上方","abrasion":"磨损","abstract, summary":"摘要","account book":"账簿",
"acount":"账目","act, deed":"行为","address":"地址","adventure":"冒险",
"advice, suggestion":"建议","agility":"敏捷","all, every":"所有","all, whole":"全部",
"aloof":"疏远的","ambiguity":"歧义","amidst, among":"在……之中","among":"在……之间",
"anger, wrath":"愤怒","angle":"角","angry":"愤怒的","answer, response":"回答",
"any":"任何","apex, top":"顶点","appearance, look":"外貌","archery":"射箭",
"area":"面积、地区","armful, handful":"一抱、一把","army":"军队","army, force, troop":"军队",
"arrogance, vanity":"傲慢、虚荣","art; craft":"技艺","artificial":"人造的",
"ash":"灰","assistance":"援助","asunder":"分开地","at":"在","attack":"攻击",
"away, apart":"离开","barely":"勉强","battle":"战斗","because, for":"因为",
"behaviour":"行为","behind":"在……之后","being, existence":"存在","between":"在……之间",
"biding":"等待","big":"大","big, huge":"巨大","biology":"生物学","blister":"水疱",
"blue":"蓝","black (color)":"黑","brass (color)":"黄铜色","brown, chestnut":"栗色",
"dark brown":"深褐色","deep (of a color)":"（颜色）浓","deep (of a voice)":"（声音）低沉",
"blunt (not sharp)":"钝的","border":"边界","edge; border":"边缘","edge; contour":"轮廓",
"edge; fence":"边、栏","brave, undaunted":"勇敢无畏","brazen":"厚颜的","bribe":"贿赂",
"brine, deep":"卤水；深处","brink":"边缘","buffer":"缓冲","burden, load":"负担",
"burn (injury)":"烧伤","calculus":"微积分","call":"呼叫","called":"称为",
"cancer":"癌症","case":"案例、格","cavity":"腔","change":"变化",
"character, nature":"性格","check/cheque":"支票","circle":"圆","clean":"干净的",
"cliché, platitude":"陈词滥调","close (of friends)":"亲密的","closed, shut":"关闭的",
"clove (of garlic)":"蒜瓣","clumsy":"笨拙的","coarse (of fabric)":"（织物）粗",
"coarse, crude":"粗糙的","coating, crust":"外壳、结壳","comparison":"比较",
"coming, arrival":"到来","conscience":"良心","consciousness":"意识",
"contact, liaison":"联络","contradiction":"矛盾","conversation, talk":"交谈",
"copy, issue":"份、期","corner":"角落","cost":"费用","costume":"服装",
"courage, daring":"勇气","covering":"覆盖物","cowardly":"怯懦的","creation":"创造",
"crime":"罪行","crisis":"危机","criterion":"标准","crude":"粗糙的","cube":"立方",
"custom, habit":"习惯","custom, observance":"习俗","dampness":"潮湿","dance":"舞蹈",
"dancer":"舞者","dark, deep":"深暗的","debt":"债务","decision":"决定","deep":"深",
"dense":"密的","depth":"深度","dereliction":"废弃","desire, longing":"渴望",
"device; tool":"器具","devil, evil spirit":"恶灵","diary":"日记","difference":"差异",
"difficulty":"困难","disinfectant":"消毒剂","distinction":"区别","double":"双倍",
"doubt":"疑虑","downward":"向下","downwards":"向下","draft, manuscript":"草稿",
"dream":"梦","dream (aspiration)":"理想","dried, dry":"干的","dry":"干燥",
"drop":"滴","dumb, slow":"迟钝的","dung, manure":"粪肥","each, every":"每个",
"education":"教育","edict":"敕令","eighteen":"十八","eighty":"八十","eleven":"十一",
"elixir":"灵药","embrace, hug":"拥抱","empathy":"共情","empty":"空的",
"empty, hollow":"空虚的","enclosure; yard":"围院","energy, life force":"元气",
"enthusiasm":"热忱","entity":"实体","equal":"相等","essence":"本质","essence, gist":"要旨",
"even":"甚至；平的","even, equable.":"均等的。","every, each":"每一","evidence":"证据",
"evidence, proof":"凭证","existence":"存在","exit (way out)":"出口",
"expense, cost":"开支","experience":"经验","experiment":"实验","extremity":"末端",
"fact":"事实","faith; belief":"信仰","far":"远","faraway, distant":"遥远的",
"fate, fortune, lot":"命运","fee; levy; duty":"费、税","feminine":"阴性的",
"ferocious":"凶猛的","fierce, ferocious":"凶猛的","few":"少","fibre, bristle":"纤维、鬃",
"fiery":"炽烈的","fifteen":"十五","finance":"财政","fine (penalty)":"罚款",
"fine, delicate":"精细的","fine-grained":"细粒的","fire":"火","first":"第一",
"first aid":"急救","firmness":"坚定","flat, smooth.":"平滑的。","following":"下列的",
"football, soccer":"足球","force":"力","fortune, luck":"运气","foundation":"基础",
"four":"四","fourteen":"十四","friction":"摩擦","front side":"正面","fruit":"果实",
"fund":"基金","general, gross":"总的","generation":"世代","gesture, signal":"手势、信号",
"confusion":"混乱","connection, link":"联系","a bit, slightly":"稍微",
"apple":"苹果","beginning":"开端",
}
