#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part E (final batch, 1/2)."""
G = {
"Khorchin (a Mongolian dialect)":"科尔沁方言","Postconsonantal plural former.":"辅音后的复数构成成分。",
"Zamyn-Üüd (a city in Mongolia)":"扎门乌德（蒙古国城市）","a male given name from Tibetan":"源自藏语的男子名",
"advisor; consultant; counselor":"顾问","backwardness, underdevelopment":"落后、欠发达",
"bite one's tongue, keep silent":"缄口不言","caragana, Caragana arborescens":"树锦鸡儿",
"church assembly, public prayer":"法会、共修","cloud (of dust, of smoke, ...)":"（尘、烟）云团",
"conflagration, wildfire, blaze":"大火、野火","drugstore, pharmacy, chemist's":"药房",
"garbage, rubbish, dust, litter":"垃圾","government; a political system":"政体",
"hard, inflexible, tough, harsh":"坚硬、严苛的","leisure, spare time, free time":"闲暇",
"only used in дэл сул (del sul)":"仅用于 дэл сул","play, performance, show, piece":"戏剧、演出",
"resolution (official decision)":"决议","tie, link, connection, binding":"联结",
"to give a sign, signal, to cue":"示意","to insult, humiliate, belittle":"羞辱、贬低",
"to juice (to drain juice from)":"榨汁","to leave skid marks with a car":"车轮打滑留痕",
"to season, flavor (with sauce)":"调味","Forms the plural form of nouns.":"构成名词复数。",
"Marks the dative-locative case.":"标记与位格。","Marks the plural of some words.":"标记部分词的复数。",
"Sükhbaatar (a city in Mongolia)":"苏赫巴托尔（蒙古国城市）","a small domestic breed of horse":"小型家马",
"argali (Ovis ammon, wild sheep)":"盘羊","big, considerable, grand, great":"宏大的",
"board, panel; wooden book cover":"木质书板","cemetery, churchyard, graveyard":"墓地",
"cream (from raw or boiled milk)":"奶皮、奶油","cruel, brutal, ruthless beastly":"残暴的",
"feeling of aversion, repugnance":"厌恶感","forms action nouns out of verbs":"由动词构成动作名词",
"hairdresser, coiffeur/coiffeuse":"理发师","heretical, heterodox, dissident":"异端的",
"law (both legal and scientific)":"法则、法律","lecture (academic presentation)":"讲座",
"low quality, trash, counterfeit":"劣质、伪劣","notebook, copybook, writing pad":"笔记本",
"production, manufacture, output":"生产、产量","springlet (a small watersource)":"小泉",
"straightforward, direct, honest":"率直的","to almost do, to be about to do":"将要、几乎",
"to ask about (someone's health)":"问安","to ice (with verbs of freezing)":"结冰（与冻结类动词连用）",
"to light (a lamp, a fire, ... )":"点燃","to teach; to train; to instruct":"教导、训练",
"usage (an act or manner of use)":"用法","Used to mark the precative mood.":"标记祈使愿望式。",
"a type of traditional wooden toy":"一种传统木制玩具","circulation, turnover, operation":"周转、运转",
"clotted cream (from boiled milk)":"奶皮子","effect (consequences of actions)":"效果",
"fruit-bearing, abundant in fruit":"多果的","joint (connection between bones)":"关节",
"malleus (bone of the middle ear)":"锤骨","page, sheet of paper, leaf, list":"页、张",
"policy, guidelines, instructions":"方针、指示","possibility, chance, opportunity":"可能、机会",
"pus, blood (from a wound, ulcer)":"脓血","show, entertainment, performance":"表演",
"string (of a musical instrument)":"琴弦","suspenders (to hold up trousers)":"背带",
"to ask for, to bring, to take in":"索取、取来","to bite, to fall for (be fooled)":"咬钩、上当",
"to consider that, to reckon that":"认为","to deceive, to beguile, to cheat":"欺骗",
"to reach, to arrive at; to touch":"到达；触及","to scratch; to attack with claws":"抓挠",
"to serve in an official capacity":"任职","to sit (at an honorary position)":"坐上位",
"to wish, to desire, to yearn for":"渴望","us (genitive of бид (bid, “we”))":"我们的（бид 的属格）",
"vacancy, replacement, substitute":"空缺、替补","while there's life, there's hope":"留得青山在，不怕没柴烧",
"Daur, a Mongolian ethnic identity":"达斡尔","Extends the stem between letters.":"在字母间延展词干。",
"I (first-person singular pronoun)":"我（第一人称单数代词）","Mongolia (a country in East Asia)":"蒙古国",
"Tehran (the capital city of Iran)":"德黑兰（伊朗首都）","abundant in trees, heavily wooded":"林木茂密的",
"bull (an uncastrated male bovine)":"公牛","capital, capital city, metropolis":"首都、大都会",
"chips, French fries, fried potato":"薯条","circle, clique (group of persons)":"圈子",
"edge; brim (of a glass, hat, ...)":"边沿","fitness, convenience (of a thing)":"适用、便利",
"gazelle; Mongolian gazelle, zeren":"黄羊","goo that accumulates inside pipes":"烟油",
"grace, favor, protection, auspice":"恩庇","league (of Inner Mongolia, China)":"盟（内蒙古行政区划）",
"letter (written message); message":"书信、讯息","marking the topic of the sentence":"标记句子话题",
"meat broth (thickened with flour)":"面片肉汤","rein, a thong for leading a horse":"缰绳",
"straight (not curved or sideways)":"笔直的","the Dzungars; the Dzungar Khanate":"准噶尔；准噶尔汗国",
"to classify (divide into classes)":"分类","to do in time, to make it in time":"赶上、来得及",
"to exchange snuff (as a greeting)":"互递鼻烟壶（问候礼）","to look after, to rear (children)":"抚养",
"to mix, shuffle, stir, adulterate":"搅混","to peel, to hull, to crack (nuts)":"去壳",
"A Chingissid Mongolian noble title":"成吉思汗系蒙古贵族爵号",
"Dzungaria (a region in Inner Asia)":"准噶尔（内亚地区）","Tolui (fourth son of Genghis Khan)":"拖雷（成吉思汗第四子）",
"authority (power to enforce rules)":"权威","coupling, hyphen, joining, linking":"连接、连字符",
"equipment, paraphernalia, utensils":"器具","fortune, misfortune, destiny, fate":"命运、祸福",
"fragrant, sweet-smelling, redolent":"芬芳的","head (the topmost part of a thing)":"顶端",
"hearty, jolly, prodigious, umpteen":"畅快、众多的","iterative verbal noun of гэх (gex)":"гэх 的反复体动名词",
"murmur, noise (of wind, of crowds)":"（风、人群的）喧声","neck (of a person, of a bottle...)":"颈、瓶颈",
"only used in тоор тоор (toor toor)":"仅用于 тоор тоор","position in a sequence, ordinality":"次第、序数",
"province (subdivision of Mongolia)":"省（蒙古国行政区划）","role; part (in a theater or movie)":"角色",
"shoot, sprout (young plant growth)":"新芽","stair, stairs, staircase, stairway":"楼梯",
"to be quarrelsome, to be irascible":"好争易怒","to conduct (a musical performance)":"指挥（演奏）",
"to display, lay, open wide, unfold":"铺展、展开","to open; to crack open, to open up":"开启",
"to serve a meal (to honor a guest)":"设宴款客","to understand (someone, something)":"理解",
"toe (front part of a boot or shoe)":"鞋头","Sükhbaatar (a province of Mongolia)":"苏赫巴托尔省",
"Used to mark the desiderative mood.":"标记愿望式。","a fork used for collecting dry dung":"拾粪叉",
"blunt side (of a knife, hatchet...)":"刀背、斧背","camp, settlement; quarter, district":"营盘、街区",
"delicate, fine, exquisite, precious":"精致贵重的","flesh (of a human, animal or fruit)":"肉、果肉",
"half-breed (a person of mixed race)":"混血者","mouthpiece (part of a tobacco pipe)":"烟嘴",
"smooth, slippery, shiny, glistening":"光滑发亮的","sunny, sun-drenched, bright, sunlit":"阳光充足的",
"to assume a position (of authority)":"就位、履职","to move, to shift (change position)":"移动",
"to project, to estimate, to presume":"估计、推断","vegetable soup, porridge, herb soup":"菜汤、羹",
"Poland (a country in Central Europe)":"波兰","a unit of length equal to 250 meters":"长度单位，合 250 米",
"champion, record holder, titleholder":"冠军、纪录保持者","form, figure, character, personality":"形貌、性格",
"grain (of cereals), piece (of paper)":"（谷）粒、（纸）张","mine; the site containing ore itself":"矿、矿址",
"noodles (long thin strands of dough)":"面条","northern, north, hyperborean, nordic":"北方的",
"proof of reality, trace of existence":"存在的凭证","score (measure of success in a game)":"得分",
"shoulders (of a bottle, of clothing)":"瓶肩、衣肩","slut, manslut (a promiscuous person)":"淫乱者",
"to achieve, attain, end in, overtake":"达成、赶上","to bring a decision, make a solution":"作出决定",
"to discuss together, to hold counsel":"商议","to emit, take out, move away, reveal":"发出、取出、显露",
"to empathize, to sympathize, to pity":"同情","to reach, to arrive at; to amount to":"到达；达到（数量）",
"Austria (a country in Central Europe)":"奥地利","application, request, claim, petition":"申请、请求",
"business, commerce, market, marketing":"商业、市场","common bistort (Bistorta officinalis)":"拳参",
"iron stove padded with brick, furnace":"砖衬铁炉","pile, nap (fuzzy surface of a fabric)":"绒面",
"plectrum used for playing шанз (šanz)":"弹三弦用的拨子","right (that which is due to a person)":"权利",
"to deviate, to digress, to wander off":"偏离","to inherit, to accede (to a position)":"承袭",
"to stir, to budge (to be in movement)":"挪动","to struggle, fight, compete, scramble":"争斗",
"to verify (to ascertain the truth of)":"核实","unsociable, withdrawn, arrogant, cold":"孤僻冷傲的",
"Forms agentive participles from verbs.":"由动词构成施事分词。","Siberia (the region of Russia in Asia)":"西伯利亚",
"cheque, check; ticket; coupon; receipt":"支票、票券、收据","conjunction, joint, junction, ligament":"接合、韧带",
"frank, direct, straightforward, candid":"坦率的","league (subdivision of Inner Mongolia)":"盟（内蒙古行政区划）",
"profit, use, utility, advantage, favor":"利益、益处","program (set of structured activities)":"计划、程序",
"sister-in-law (younger brother's wife)":"弟媳","to advance (literally or figuratively)":"前进、推进",
"to bring out (display inner qualities)":"显露（内在品质）","to climb, ascend, clamber up, scramble":"攀登",
"to fasten something down, to hold back":"扣紧、拉住","to leak, pour out, drip, stream, sweat":"渗漏、流出",
"to restock, to refill (a meal, a fire)":"续添","to stick (of an emotion, thought, ...)":"（情绪、念头）萦绕",
"tool, means, resource (something used)":"工具、手段","trolleybus, trolley bus, trolley coach":"无轨电车",
"A former palace and temple near Baotou.":"包头附近的旧宫庙。","Forms agent nouns from nouns and verbs.":"由名词与动词构成施事名词。",
"Postvocalic definite accusative marker.":"元音后的定指宾格标记。","beise (noble title of the Qing dynasty)":"贝子（清代爵号）",
"blunt side (of a hatchet or other tool)":"斧背（及类似工具的钝面）","chain (series of interconnected things)":"链条、系列",
"how, wherefore, why, how come, what for":"为何、怎么","one of the titles among Mongol nobility":"蒙古贵族爵号之一",
"people (as a nation or an ethnic group)":"民族","pepper, pimento, hot pepper, red pepper":"辣椒",
"rule, charter, regulations, law, regime":"章程、法规","to circumambulate (a stupa or a temple)":"绕塔、绕寺",
"to fine (to issue a fine as punishment)":"罚款","to lie (to be in a horizontal position)":"躺卧",
"to make, to build (objects, food, ... )":"制作","to stand (of a winged animal), to perch":"栖止",
"weak, feeble, lax, poor, underdeveloped":"孱弱的","work, action, accomplishment, deed, act":"工作、功业",
"Manchuria (a geographic region of China)":"满洲（中国地理区域）","a castrated camel of five years or older":"五岁以上的骟驼",
"an action of тогтоох (togtoox), settling":"тогтоох 的动作，安定","having bloated cheeks, having a fat head":"面颊臃肿的",
"house centipede (Scutigera coleoptrata)\\":"蚰蜒","leuconychia (white spots on fingernails)":"甲白斑",
"miscellaneous, otherwise, another, other":"其余的、别的","organisation; establishment; institution":"机构、团体",
"out in the open (not hidden; not inside)":"露天、在外","root, cause (that which causes an event)":"根由",
"shoulder sling (for rifles, swords, ...)":"背带（枪、刀）","speech (a talk delivered to an audience)":"演讲",
"to be afflicted, to get (a disease, ...)":"患（病）","to possess, gain the admiration, conquer":"折服、赢得",
"to put pressure on, to compel, to insist":"施压、坚持","us (genitive of бид нар (bid nar, “we”))":"我们的（бид нар 的属格）",
"young of a (wild) animal, cub, fledgling":"幼兽、雏",
}
