#!/usr/bin/env python3
"""Chinese for the Mongolian glosses, part D (tail of the alphabet + compounds)."""
G = {
# --- single words, U–Z ---
"we":"我们","tub":"盆","two":"二","wax":"蜡","wet":"湿","who":"谁","yak":"牦牛",
"yes":"是","you":"你","zoo":"动物园","tusk":"獠牙","twin":"孪生","user":"用户",
"very":"很","visa":"签证","wall":"墙","wave":"波","week":"周","west":"西",
"when":"何时","wife":"妻子","wing":"翅","wood":"木","wool":"羊毛","word":"词",
"work":"工作","year":"年","zero":"零","zinc":"锌","zone":"地带","udder":"乳房（畜）",
"until":"直到","upper":"上部的","video":"影像","vivid":"鲜明的","vodka":"伏特加",
"voice":"声音","vomit":"呕吐","waist":"腰","water":"水","wheat":"小麦","wheel":"轮",
"where":"何处","white":"白","world":"世界","wound":"伤口","wrist":"腕","wrong":"错的",
"young":"年轻的","yours":"你的","youth":"青年","turkey":"火鸡","twelve":"十二",
"twenty":"二十","vagina":"阴道","valley":"山谷","violet":"紫罗兰","vision":"视力",
"vulgar":"粗俗的","wallet":"钱包","walnut":"核桃","weight":"重量","wicker":"柳条",
"willow":"柳","window":"窗","winter":"冬","zodiac":"黄道十二宫","upriver":"上游",
"version":"版本","vinegar":"醋","volcano":"火山","weather":"天气","wedding":"婚礼",
"welcome":"欢迎","writing":"书写","umbrella":"伞","uprising":"起义","vertebra":"椎骨",
"very rare":"极罕见","violinist":"小提琴手","voodooism":"巫毒教","waterfall":"瀑布",
"way, road":"道路","whirlwind":"旋风","wood-like":"木质的","yesterday":"昨天",
"yurt, ger":"蒙古包","watermelon":"西瓜","wet; moist":"湿润的","woodpecker":"啄木鸟",
"up, upwards":"向上","usual state":"常态","violoncello":"大提琴","voice, vote":"声音；选票",
"wide, broad":"宽阔的","wire, cable":"电线、缆","your, yours":"你的",
"water stream":"水流","will, desire":"意愿","worm, maggot":"蠕虫、蛆",
"young, small":"幼小的","Ölöt, Eleuth":"厄鲁特","west, western":"西方的",
"whole, entire":"整个的","zither player":"筝手","vacuum cleaner":"吸尘器",
"violin, fiddle":"小提琴","wild (untamed)":"野生的","urgency, demand":"紧迫、需求",
"use (expediency)":"用处","weapon, armament":"兵器","uneven (of teeth)":"（牙）参差",
"uniform, regular.":"整齐划一的。","wrestling costume":"摔跤服",
"twine, convolution":"缠绕","union, association":"联合会","vagrant, wandering":"流浪的",
"vase; jar; pitcher":"瓶、罐、壶","violence, coercion":"暴力、强迫",
"wilful, capricious":"任性的","verse, alliteration":"诗句、头韵",

# --- multi-word ---
"Arab, Arabic, Arabian":"阿拉伯（人、语、的）","Heilongjiang Province":"黑龙江省",
"The sound of a cough.":"咳嗽声。","a part of a bird-trap":"捕鸟器部件",
"academic; academician":"院士","aid, help, assistance":"援助",
"binoculars; telescope":"望远镜","capital; capital city":"首都",
"car, auto, automobile":"汽车","celebration, festival":"庆典",
"chamber (of a device)":"腔室","character, reputation":"品格、声誉",
"chessboard, gameboard":"棋盘","cinema, movie theatre":"电影院",
"compact, close-packed":"紧实的","conjunction (grammar)":"连词",
"contraption (machine)":"装置","dirty, untidy, filthy":"肮脏的",
"draughts (board game)":"西洋跳棋","edges of a bow handle":"弓把边缘",
"few (small in number)":"少数","fibrocartilage callus":"纤维软骨痂",
"flow, current, stream":"水流","former name of Hejing":"和静旧称",
"front, female (vowel)":"前元音、阴性元音","government, authority":"政府、当局",
"hearth, oven, furnace":"炉灶","long johns, longjohns":"衬裤",
"loquacious, garrulous":"多话的","marker after ᠊ᠨ (-n).":"用于 ᠊ᠨ(-n) 之后的标记。",
"marrowbone, long bone":"长骨、髓骨","minute (unit of time)":"分钟",
"nucleus; kernel; core":"核心","old, aged (of people)":"年老的",
"preparation; training":"准备、训练","representative; agent":"代表、代理人",
"slogan, rallying call":"口号","steamed meat dumpling":"包子",
"straight (not curved)":"笔直的","to be stingy, thrifty":"吝惜、节省",
"to change, to replace":"更换","to encroach, infringe":"侵犯",
"to fatten (an animal)":"催肥","to gesture, to beckon":"招手示意",
"to hesitate, to waver":"犹豫","to lose oneself doing":"沉迷于",
"to manage, to be able":"办得到","to meet, to encounter":"遇见",
"to mention, to allude":"提及","to receive, to attain":"获得",
"to slide, glide, slip":"滑动","to slip, glide, slide":"滑","to stop, cease action":"停止",
"to wait for, to await":"等候","to wake up, to get up":"起身",
"velvet; velour; plush":"天鹅绒","wilderness, wasteland":"荒野",
"wrathful (of deities)":"忿怒（尊）","Ölöt, Eleuth (person)":"厄鲁特人",
"a (small) river, brook":"小河、溪","a cruel person, sadist":"残忍之人",
"anachronism, mustiness":"陈腐、不合时宜","border, boundary, edge":"边界",
"burning ashes, cinders":"余烬","cake, equivalent to 蛋糕":"蛋糕",
"care, aid, benevolence":"眷顾、恩惠","character, temperament":"性情",
"chimney, whistle, horn":"烟囱；哨；号","foot-and-mouth disease":"口蹄疫",
"golden, (made) of gold":"金的","goods, stock, shipment":"货物",
"high-class woman, lady":"贵妇","honeyed, honey-bearing":"含蜜的",
"incomplete, unfinished":"未完成的","mother-of-pearl; nacre":"珍珠母",
"narrow-minded, limited":"狭隘的","numerative, arithmetic":"计数的、算术的",
"order, queue, sentence":"次序、行列、句","paw, sole (of animals)":"爪、掌",
"porch, stoop, platform":"门廊、台","profession, occupation":"职业",
"progress (improvement)":"进步","province (of Mongolia)":"省（蒙古国）",
"reform; reconstruction":"改革、重建","regarding, in terms of":"就……而言",
"right hand, right wing":"右手、右翼","snail, slug, gastropod":"蜗牛、蛞蝓",
"spring, origin, source":"泉源","state, country, nation":"国家",
"steer (castrated bull)":"阉牛","third generation slave":"三世家奴",
"to achieve, to succeed":"达成","to alter, to transform":"改变",
"to ask for, to beg for":"乞求","to betray, to sell out":"出卖",
"to break wind; to fart":"放屁","to burn, to catch fire":"着火",
"to coerce, to dominate":"胁迫、压制","to devote, to dedicate":"奉献",
"to give birth, be born":"生育、出生","to insult, to put down":"侮辱",
"to manipulate (people)":"操纵","to nurture, to protect":"养护",
"to stop; to stop doing":"停下","to strive, to try hard":"努力",
"together; along (with)":"一同","Ölöts, Eleuths (tribe)":"厄鲁特部",
"A person from the tribe":"该部之人","Forms nouns from verbs.":"由动词构成名词。",
"I don’t speak Mongolian":"我不会说蒙古语","archduke; princely khan":"大公、王汗",
"board, panel; billboard":"板、告示牌","cane, rod (for hitting)":"责杖",
"cheekbone, cheek region":"颧、面颊","child (one's offspring)":"子女",
"competition; tournament":"竞赛","dirty, tasteless, muddy":"污浊无味的",
"dock (root of the tail)":"尾根","excrement, manure, shit":"粪",
"government; rule, power":"统治、政权","hit (a successful shot)":"命中",
"line, queue (of people)":"队列","mansion; castle; palace":"府邸、宫堡",
"mind, intellect, memory":"心智、记性","mind, intellect, spirit":"心智、精神",
"motive, reason, pretext":"动机、由头","musk (odour, secretion)":"麝香",
"passive forming suffix.":"构成被动式的后缀。","point (unit of scoring)":"分（计分）",
"power, intensity, might":"力量、强度","race (contest of speed)":"赛跑",
"reason, pretext, excuse":"理由、借口","sex; sexual intercourse":"性、性交",
"sole (bottom of a shoe)":"鞋底","starter (yeast culture)":"引子、酵头",
"the Great Wall of China":"长城","to be careful, vigilant":"谨慎、警觉",
"to burn; to set fire to":"焚烧","to mix, blend, be mixed":"混合",
"to scatter, to disperse":"驱散","to shine (in one's eye)":"（在眼中）闪耀",
"voter; elector; chooser":"选举人","wild (not domesticated)":"未驯化的",
"Chinese character, Hanzi":"汉字","Marks the ablative case.":"标记从格。",
"Monday (day of the week)":"星期一","Prince of the First Rank":"亲王",
"Prince of the Third Rank":"贝勒","The conditional converb.":"条件副动词。",
"The punctuation mark (᠀)":"标点符号（᠀）","To disinfect, asepticize":"消毒",
"To enlighten, illuminate":"启迪、照亮","ability; capacity; power":"能力",
"bobtailed (short-tailed)":"秃尾的","created through grafting":"嫁接而成的",
"crevice, incision, crack":"裂隙","distortion (of a mirror)":"（镜的）变形",
"fat, grease, oil, butter":"油脂","fork, prong, bifurcation":"叉、分岔",
"handicraft, skill, craft":"手艺","handle, haft, hilt, grip":"柄",
"heat, warmth (of a fire)":"火的热度","herbs, grass, vegetables":"草木蔬菜",
"hubris, contemptuousness":"傲慢","interface, station, apex":"界面、站点、顶点",
"lammergeier, lammergeyer":"胡兀鹫","letter (written message)":"书信",
"material, real, concrete":"实在的、具体的","mobile phone; cell phone":"手机",
"obstruction, encumbrance":"阻碍","patch, substitute, piece":"补丁、替代物",
"precise, exact, punctual":"精确、准时的","provincial (of Mongolia)":"省的",
"right (opposite of left)":"右","silk-like, soft and thin":"如丝般柔薄的",
"some of (after genitive)":"其中一些（接属格后）","structure; frame; system":"结构、体系",
"studies (field of study)":"学科","table of contents, index":"目录、索引",
"temperament, disposition":"性情","throat, pharynx, gizzard":"咽喉、砂囊",
"to adapt, to acclimatize":"适应","to be necessary, be used":"需用",
"to be unable to continue":"无以为继","to circle (to go around)":"绕行",
"to cling to, to latch on":"攀附","to consider (to view as)":"视作",
"to divide into that many":"分成那么多份","to fear, to be afraid of":"害怕",
"to help, assist, succour":"援助","to load, burden, pile up":"装载、堆积",
"to mean to, to intend to":"打算","to miscarry (of animals)":"（牲畜）流产",
"to mix, mingle, scramble":"混杂","to occur that many times":"发生那么多次",
"to peel off, to tear off":"剥落","to sponsor, to patronize":"赞助",
"to surround, to encircle":"围绕","to thirst, to be thirsty":"口渴",
"Baikal (a lake in Russia)":"贝加尔湖（俄罗斯）","Mongol (person or people)":"蒙古人",
"age (a period in history)":"时代","all, everything, everyone":"一切、人人",
"arrow, projectile, bullet":"箭、弹丸","artist, craftsman, genius":"匠人、能手",
"bandage, bonding, bracing":"绷带、缚扎","bold, tenacious, resolute":"果毅的",
"causative forming suffix.":"构成使动式的后缀。","codex (ancient book form)":"抄本",
"consumption, usage, needs":"消耗、用度","contemplation, meditation":"观想",
"contract; treaty; bargain":"契约、条约","factory, enterprise, shop":"工厂、企业",
"fin (appendage of a fish)":"鳍","fleet; pool (of vehicles)":"车队",
"fortune, luck, providence":"福运、天意","gums (flesh around teeth)":"牙龈",
"houve (close fitting cap)":"紧帽","key (for use with a lock)":"钥匙",
"man-eater, cannibal, ogre":"食人者、恶鬼","object (thing acted upon)":"客体、宾语",
"president (head of state)":"总统","rust (corrosion of metal)":"锈",
"springwater, spring water":"泉水","stray, feral (of animals)":"走失、野化的",
"string (of an instrument)":"琴弦","to answer, to reciprocate":"应答、回报",
"to be at a loss for words":"语塞","to close, block, obstruct":"堵塞",
"to do for other's benefit":"为他人而做","to doubt, to second-guess":"怀疑",
"to entwine, to interweave":"交织","to experience, to undergo":"经历",
"to fire (bricks, ceramic)":"烧制","to lead cattle to pasture":"赶牲口上草场",
"to make a mistake, to err":"出错","to play a wind instrument":"吹奏管乐",
"to reflect (light, image)":"反射","to suppose, to conjecture":"推测",
"to sweat, chafe, perspire":"出汗、磨伤","to tack a horse up gently":"缓缓备马",
"to twist (become twisted)":"扭曲","trace, imprint, footprint":"痕迹、足印",
"very important, essential":"至关重要的","you (genitive of та (ta))":"你的（та 的属格）",
"youngster, kid, boy, girl":"少年、孩子","Hui (nationality of China)":"回族",
"Mongolian wild ass, khulan":"蒙古野驴","Zakhchin (Mongolian tribe)":"扎哈沁部",
"bay, chestnut (of animals)":"赤褐色（毛色）","bird cherry (Prunus padus)":"稠李",
"board, panel; notice board":"告示板","camp, settlement; barracks":"营盘、兵营",
"cigarette lighter, lighter":"打火机","column, pillar, post, pole":"柱、杆",
"compulsive, uncontrollable":"难以自制的","decisive, daring, resolute":"果断的",
"equal, level, even, smooth":"平齐的","foam, lather, suds, bubble":"泡沫",
"gelding (castrated animal)":"骟马","greetings, congratulations":"祝贺",
"honk (sound of a car horn)":"喇叭声","interest (price of credit)":"利息",
"itinerant (person, animal)":"游走的","magnolia (tree and flower)":"木兰",
"obligation, responsibility":"义务、责任","piece, cut, slice, segment":"块、段",
"shape, form, figure, build":"体态","sister or daughter's child":"甥、外孙",
"tea house; café; cafeteria":"茶馆、咖啡馆","to be taken, to be carried":"被带走",
"to be thrifty (with money)":"节俭","to be unable, to barely do":"勉强不能",
"to become crooked, to bend":"弯曲","to blow (of persons, wind)":"吹",
"to blow up, burst, explode":"爆裂","to chide in a raised voice":"高声呵斥",
"to clench (teeth, lips...)":"咬紧、抿紧","to crash into, to run into":"撞上",
"to haul off with a vehicle":"用车拉走","to inspect, to investigate":"察看、调查",
"to join in doing something":"参与","to order someone to follow":"命人随行",
"to produce, to manufacture":"生产","to sit, repose, stand, lie":"坐卧起居",
"to speed up, to accelerate":"加速","to stop; to stop happening":"停息",
"to throw away (to discard)":"丢弃","to train horses for a race":"调驯赛马",
"to wear, put on (clothes).":"穿（衣）。","will, volition, will-power":"意志",
"Belgutei, a male given name":"别勒古台（男子名）","Khoton people (of Mongolia)":"霍屯人（蒙古国）",
"Marks the directional case.":"标记方向格。","a person of inferior status":"下人",
"abdomen, stomach, intestine":"腹、胃肠","barn, warehouse, storehouse":"仓房",
"camp, settlement; monastery":"营盘、寺院","class, category, sort, kind":"类别",
"clear, obvious, perceptible":"明显的","color of (an animal's) coat":"毛色",
"condition, state of affairs":"情形","fox; red fox, Vulpes vulpes":"赤狐",
"homely; liking to stay home":"恋家的","indirect, implicit, devious":"迂回的",
"kite (flying toy on string)":"风筝","needle used for making nets":"结网针",
"one's own business, privacy":"私事","organization, establishment":"机构",
"peach (both tree and fruit)":"桃","petty, vulgar, contemptible":"卑俗的",
"quite clear, rather obvious":"相当明显","roll (of silk, paper, etc.)":"卷",
"round (stage of difficulty)":"轮次","roundabout, indirect (road)":"迂回的路",
"shell, skin, membrane, peel":"壳、皮、膜","stoutness, fat (of animals)":"膘肥",
"term, period (span of time)":"期限","to draw (produce a picture)":"画",
"to drizzle, to fall lightly":"细落","to gallop (to ride swiftly)":"疾驰",
"to hit upon, strike, be hit":"击中","to spare (objects, animals)":"留情、放过",
"tribe (social and ethnical)":"部族","what kind, what, which, how":"何种、怎样",
"Eurasian magpie, (Pica pica)":"喜鹊","Golmud (town, county, river)":"格尔木（镇、县、河）",
"Khorchin (a Mongolian tribe)":"科尔沁部","Tuvan, Tuva, Tuvin, Tuvinian":"图瓦（人、语）",
"a flat surface; an even area":"平面、平地","abrasion (superficial wound)":"擦伤",
"air, gas, atmosphere, bubble":"气、气泡","bank (financial institution)":"银行",
"bar (drinking establishment)":"酒吧","braincase (top of the skull)":"颅顶",
"comitative case of төс (tös)":"төс 的共同格","complexion (color of a face)":"面色",
"contour, outline, silhouette":"轮廓","creation, product, invention":"创造物",
"enclosure; pen (for animals)":"畜栏","hair (of a horse, of a tail)":"马鬃、尾毛",
"hind, doe, doe of a red deer":"牝鹿","hip, thigh, side, joint, ham":"髋股",
"history (historical writing)":"史书","humiliation, outrage, insult":"羞辱",
"khural, assembly, parliament":"呼拉尔、议会","make a makeshift replacement":"临时替代",
"much, a lot, very, extremely":"很多、极","one's own (reflexive suffix)":"自己的（反身后缀）",
"open, loose, bare, uncovered":"敞开的","plain, simple, unembellished":"朴素的",
"pomegranate, Punica granatum":"石榴","sometimes, from time to time":"有时",
"space; room, physical extent":"空间","to ask for, to beg, to plead":"恳求",
"to become familiar, attached":"熟络、依恋","to cross (a river, a desert)":"横渡、穿越",
"to drop, to let go, to throw":"放开、抛下","to swim (of animals, humans)":"游泳",
"to throw down, to bring down":"摔下、击倒","to twist, to splice (a rope)":"搓绳、接绳",
"to use (a tool, a substance)":"使用","to use up, exhaust, squander":"耗尽",
"to wander (around something)":"绕行游荡","to worship, to bring an idol":"供奉",
"toes, front part of the foot":"脚前掌","abbot; prior (of a monastery)":"住持",
"around, about (approximately)":"大约","calm, quiet, peaceful, gentle":"安详的",
"competitor, rival, contestant":"竞争者","compliment, praise, adoration":"赞美",
"degree (academic achievement)":"学位","department store; supermarket":"百货商店",
"edge; frame (of glasses, ...)":"镜框","exercise (mental or physical)":"练习",
"fighter, contestant, champion":"斗士、冠军","floor (bottom part of a room)":"地板",
"having a stocky snout or beak":"钝喙的","intersection, crossroads, hub":"路口、枢纽",
"magazine, periodical, journal":"期刊","mountain pass, mountain range":"山口、山脉",
"occasion, event, circumstance":"场合、情形","original, fundamental, primal":"本原的",
"temperament, behavior, morals":"品行","to attach, to graft, to unite":"接合",
"to bear (fruit, a fetus, ...)":"结（果）、怀（胎）","to contemplate, to reflect on":"沉思",
"to cruelly punish, to torture":"酷刑折磨","to direct, to steer, to drive":"驾驭",
"to earn, to merit, to deserve":"应得","to give praise to; to applaud":"称扬",
"to haul using a carrying pole":"用扁担挑","to invite, to call, to summon":"召请",
"to rejoice, be happy, delight":"欣喜","Barag (Buryat-Mongolian tribe)":"巴尔虎部",
"China (a country in East Asia)":"中国","Forms the adjectival locative.":"构成形容词性位格。",
"Han Chinese (people or person)":"汉人","Khamnigans (Mongolised Evenks)":"哈木尼干（蒙古化的鄂温克人）",
}
