#!/usr/bin/env python3
"""Chinese for the Mongolian usage examples (part G)."""
G = {
"navy":"海军","neck":"脖子","rock":"石头","China":"中国","market":"市场","Ukraine":"乌克兰",
"pigtail":"辫子","to rain":"下雨","tonight":"今晚","Mongolia":"蒙古国","fine sand":"细沙",
"in Tehran":"在德黑兰","post card":"明信片","World Bank":"世界银行","crime rate":"犯罪率",
"golden axe":"金斧","pasta dish":"面食","soap opera":"肥皂剧","to massage":"按摩",
"late summer":"夏末","please wash":"请洗一下","How are you?":"你好吗？","I am hungry.":"我饿了。",
"I drink tea.":"我喝茶。","My team won.":"我队赢了。","Who is this?":"这是谁？",
"all the time":"一直","bird of prey":"猛禽","cold weather":"寒冷天气","fine leather":"上等皮革",
"movie screen":"银幕","the Russians":"俄罗斯人","Arab (person)":"阿拉伯人",
"Chinese paper":"宣纸","I am thirsty.":"我渴了。","I have a car.":"我有一辆车。",
"Roman numeral":"罗马数字","grocery store":"食杂店","opencast mine":"露天矿",
"to impregnate":"使受孕","to play cards":"打牌","tractor fleet":"拖拉机队",
"Mongolian post":"蒙古邮政","Roman (person)":"罗马人","divide equally":"平分",
"life insurance":"人寿保险","pregnant woman":"孕妇","to go straight":"直行",
"to have a baby":"生孩子","to hurl a rock":"掷石","to slip on ice":"在冰上滑倒",
"to take a pill":"服药","American person":"美国人","Arabic language":"阿拉伯语",
"German language":"德语","To beg for help":"求助","a pair of shoes":"一双鞋",
"elite bodyguard":"怯薛、精锐护卫","mining industry":"矿业","nobody is there":"没有人在那里",
"to grab by neck":"揪住脖子","to grow a beard":"蓄须","to wag the tail":"摇尾",
"year of fortune":"吉年","Chinese (person)":"中国人","Chinese language":"汉语",
"English language":"英语","a Russian person":"一个俄罗斯人","department store":"百货商店",
"nuclear reaction":"核反应","to beg for money":"讨钱","to earn a reward":"获得奖赏",
"to give a signal":"发出信号","to shave a beard":"刮胡子","uniformly moving":"匀速运动的",
"Year of the Horse":"午年","chess competition":"棋赛","he reads the book":"他读那本书",
"railway timetable":"铁路时刻表","the supreme court":"最高法院","the whole village":"全村",
"timetable; roster":"时刻表、值班表","to be (too) small":"（太）小","to let out a sigh":"叹了口气",
"to receive praise":"受到称赞","to train soldiers":"练兵","underwater museum":"水下博物馆",
"I am called David.":"我叫大卫。","Mongolian language":"蒙古语","Russian Federation":"俄罗斯联邦",
"a pair of earrings":"一对耳环","a republican party":"共和党","an imperial throne":"帝位",
"the Russian people":"俄罗斯民族","to become a prince":"成为王子","to become pregnant":"怀孕",
"to blow one's nose":"擤鼻涕","to listen to music":"听音乐","to sweep the floor":"扫地",
"Ode to Genghis Khan":"成吉思汗颂","an imperial dynasty":"帝国王朝",
"joint stock company":"股份公司","to erect a monument":"立碑","to paint a portrait":"画像",
"to stand in a queue":"排队","(I) go at 5 o’clock.":"（我）五点走。",
"How was your dinner?":"晚饭吃得怎么样？","Where is the toilet?":"厕所在哪里？",
"member of parliament":"议员","the Russian language":"俄语","to say to one’s face":"当面说",
"to smear with grease":"抹油","to stand up straight":"站直","We are eating fruits.":"我们在吃水果。",
"What day is it today?":"今天星期几？","a threatening gesture":"威胁的手势",
"Three times in a week!":"一周三次！","Where is the bathroom?":"卫生间在哪里？",
"bowl of a tobacco pipe":"烟斗锅","zoo; zoological garden":"动物园",
"I will read a new book.":"我要读一本新书。","the Republic of Austria":"奥地利共和国",
"to defend one's country":"保卫国家","to overthrow government":"推翻政府",
"to take over government":"接管政权","He sees/will see a film.":"他看／将看一部电影。",
"State Emblem of Mongolia":"蒙古国国徽","under the auspices of...":"在……的主持下",
"your brother lives here.":"你兄弟住在这里。","Chinese characters; Hanzi":"汉字",
"He/she is a good student.":"他／她是个好学生。","Please close your window.":"请关上窗户。",
"This person is my friend.":"这个人是我的朋友。","pronunciation of the word":"该词的读音",
"to receive government aid":"领取政府补助","Englishman, English person":"英国人",
"King of the United Kingdom":"英国国王","a television advertisement":"电视广告",
"for a disease to be stable":"病情稳定","the Republic of Kazakhstan":"哈萨克斯坦共和国",
"to study at the university":"在大学读书","I will see the English film":"我要看那部英国电影",
"Mongolian People's Republic":"蒙古人民共和国","what is your name (called)?":"你叫什么名字？",
"Russia (as country or state)":"俄罗斯（国家）","to land, to touch the ground":"着陆",
"He/she is learning Mongolian.":"他／她在学蒙古语。","What kind of a plant is this?":"这是什么植物？",
"[I] have to go to the library":"（我）得去图书馆","origin of the word; etymology":"词的来源；词源",
"sense of the word; definition":"词义；释义","His work is not far from here.":"他的工作地点离这儿不远。",
"How much is a kilo of cabbage?":"卷心菜一公斤多少钱？","Will you be there when I come?":"我来的时候你在吗？",
"people's government, democracy":"人民政权、民主","to be in somebody's good grace":"得某人青眼",
"to receive government benefits":"领取政府福利","Have you even been to Mongolia?":"你去过蒙古国吗？",
"I wish/if only he/she would go.":"但愿他／她能去。","Please give me a cup of coffee.":"请给我一杯咖啡。",
"Russia (as geographical region)":"俄罗斯（地理区域）","Inner Mongolia Autonomous Region":"内蒙古自治区",
"to put the tail between the legs":"夹起尾巴","to ram the tobacco into the pipe":"把烟丝塞进烟斗",
"Don't point your finger at people!":"不要用手指着别人！","to be straightforward, to be direct":"直截了当",
"I thought I'd visit you this evening.":"我想今晚去看你。","If father comes we will eat together.":"父亲来了我们就一起吃。",
"His birthplace is Ögöörmör subdistrict.":"他的出生地是乌格尔莫尔巴格。",
"to translate from English into Mongolian":"从英语译成蒙古语",
"When the electricity is cut, the candle is lit.":"停电时点起蜡烛。",
"to give a presentation, lecture; to make a speech":"作报告、演讲",
"My younger sibling is studying English in America.":"我弟弟（妹妹）在美国学英语。",
"There are over 70,000 species of mushrooms in nature.":"自然界中蘑菇有七万余种。",
"That person is my sister (or my brother in a case of male person).":"那个人是我姐妹（若为男性则是我兄弟）。",
"(I) requested immediate assistance and fortunately it arrived quickly.":"（我）请求立即支援，所幸很快就到了。",
"the Mongolian \"bavar\" (the expression contains all Mongolian vocalised consonants)":"蒙古语的「bavar」（此语含全部蒙古语浊辅音）",
"Then a tall gaunt boy in snow-white clothes goes out of the ger and going by Ms. Daram he quivers and halts.":"随后，一个身着雪白衣裳的瘦高少年走出蒙古包，路过达拉木女士身旁时颤了一下，停住了脚步。",
"Mongolians have been making snuff from jade since ancient times, and snuff made from this stone is considered very expensive.":"蒙古人自古以玉制鼻烟，用此石所制的鼻烟被视为极其贵重。",
"Mongols have been making snuffboxes from jade since ancient times, and snuffboxes made from this stone are considered very expensive.":"蒙古人自古以玉制鼻烟壶，用此石所制的鼻烟壶被视为极其贵重。",
}
