#!/usr/bin/env python3
"""Chinese for the short Old Turkic glosses (part A). Merged by merge_glosses.py."""
G = {
# --- letters: Semitic and Greek names keep their conventional Chinese forms ---
"aleph":"阿列夫","beth":"贝特","daleth":"达列特","waw":"瓦夫","zayn":"扎因","heth":"赫特",
"teth":"泰特","yodh":"尤德","kaph":"卡夫","lamed":"拉梅德","mem":"梅姆","nun":"农",
"samekh":"萨梅赫","pe":"佩","sadhe":"察狄","resh":"雷什","shin":"申","taw":"陶",
"alpha":"阿尔法","beta":"贝塔","gamma":"伽马","delta":"德尔塔","zeta":"泽塔","iota":"约塔",
"kappa":"卡帕","lambda":"拉姆达","nu":"纽","rho":"罗","sigma":"西格马","upsilon":"宇普西龙","chi":"希",
"minuscule":"小写体",

# --- grammar / function ---
"-less":"无……的","?":"未详","or":"或","with":"与、同","and, on top of that":"并且、此外",
"emphatic particle":"强调语气词","interrogative particle":"疑问语气词",
"causative suffix":"使动后缀","superlative suffix":"最高级后缀","comitative case":"共同格",
"Forms conditional mood":"构成条件式","Forms desiderative mood":"构成愿望式",
"Forms equative case":"构成比较格","Forms genitive case":"构成属格",
"Forms instrumental case":"构成工具格","Forms the ablative case":"构成从格",
"Forms the allative case":"构成向格","romanization of 𐰘𐰏𐰼𐰢𐰃":"𐰘𐰏𐰼𐰢𐰃 的拉丁转写",
"step-":"继……、异父母的",

# --- pronouns / deixis ---
"I":"我","we":"我们","thou":"你","you":"你们","he/she/it/that":"他／她／它／那",
"this":"这","who":"谁","what":"什么","self":"自己","every, all":"每一、全部",
"all, everything":"一切、万物","there is":"有","there is not, no":"没有、无",
"above":"上方","below":"下方","exterior":"外部","interior, insides, core":"内部、核心",
"middle":"中","middle, central":"中间的","middle, midpoint":"中点","among, between":"在……之间",
"hither, hitherward":"向此处","hitherward":"向此处","upwards":"向上","now":"现在",
"once":"一次","one, once":"一、一次","times":"次、倍",

# --- numbers ---
"one":"一","two":"二","three":"三","four":"四","five":"五","six":"六","seven":"七",
"eight":"八","nine":"九","ten":"十","fifty":"五十","sixty":"六十","hundred":"百",
"thousand":"千","ten thousand":"万","myriad":"万、无数","number":"数目",
"a half":"一半","innumerable, countless":"无数、不可胜数",

# --- peoples, places, titles ---
"Turk":"突厥人","Uyghurs":"回鹘人","Khitans":"契丹人","Tangut people":"党项人",
"Tocharian people":"吐火罗人","Yenisei Kyrgyz":"叶尼塞黠戛斯","Hui people":"回人",
"Goguryeo Empire":"高句丽","China":"中国","Tibet":"吐蕃","Syr Darya":"锡尔河",
"Taurus":"金牛座","the Altai Mountains":"阿尔泰山","the Hetao Region":"河套地区",
"the Iron Gate defile":"铁门关","the Irtysh river":"额尔齐斯河",
"the Tannu-Ola Mountains":"唐努乌拉山","the Yin Mountains":"阴山",
"a Tibetan minister":"一位吐蕃大臣","Son of Heaven":"天子","Chor, a title":"啜（官号）",
"a title":"官号","a male given name":"男子名","name":"名","name, title":"名号",
"yabghu":"叶护","shah":"沙（波斯君主号）","king":"王","king, khan":"王、汗",
"male ruler, khagan, king":"可汗、君王","male ruler, khan":"可汗","having a khagan":"有可汗的",
"queen, lady":"可敦、夫人","princess":"公主","dame, princess":"贵妇、公主",
"lord":"主君","mister, gentleman; lord":"先生、主君","mister, sir, gentleman":"先生、阁下",
"minister":"大臣","commander":"统帅","general":"将军","governor-general":"都督",
"district magistrate":"刺史","envoy":"使者","ruler":"统治者","prophet":"先知",
"people, nation":"民、部众","person, people":"人","tribe":"部落","tribe, clan":"部族",
"clan, tribe, kin":"氏族、亲族","family":"家族","relative":"亲属","ancestor":"祖先",
"heathen":"异教徒","stranger, enemy":"外人、敌人","giant":"巨人",

# --- kinship / persons ---
"father":"父","father, bear":"父；熊","mother":"母","child":"子女","child, offspring":"子嗣",
"daughter-in-law":"儿媳","daughter-in-law, bride":"儿媳、新妇","paternal uncle":"叔伯",
"half brother":"异母（父）兄弟","step-father":"继父","nibling":"侄甥",
"nibling; nephew or niece":"侄甥（侄或甥）","widow":"寡妇","motherless; orphan":"失恃、孤儿",
"orphan":"孤儿","man":"人、男子","man, human male":"男子","male":"雄、男",
"chief, a woman's husband":"首领；丈夫","friend":"朋友","friend, comrade":"朋友、同伴",
"servant":"仆从","slave, servant":"奴仆","a male slave, servant":"男奴、仆人",
"hero":"英雄","hero, warrior":"英雄、勇士","warrior":"武士","brave":"勇敢的","bravery":"勇武",
"foot soldier":"步卒","foot soldier; on foot":"步卒；徒步","pedestrian":"行人",
"army":"军队","enemy":"敌人","enemy, hostile":"敌对的","enemy, war":"敌、战",
"wise, counselor, advisor":"贤者、谋臣","miser":"吝啬者","disturber":"扰乱者",
"vulgar, plebeian":"平庶的",

# --- body ---
"eye":"眼","face":"面","head":"头","hair":"毛发","hair (on head)":"头发","ear":"耳",
"mouth":"口","tongue":"舌","throat":"喉","hand":"手","foot":"足","foot, leg":"足、腿",
"leg, foot":"腿、足","knee":"膝","bone":"骨","bile, gall":"胆汁","mind":"心智",
"white headed":"白头的","having a white forehead":"白额的",

# --- animals ---
"horse":"马","horse, mare":"马、牝马","mare":"牝马","stallion":"种马","colt or gelded camel":"驹；骟驼",
"feral horse":"野马","camel":"骆驼","she-camel":"牝驼","female camel":"牝驼",
"cow":"牛","cow, female cattle":"牝牛","bull":"公牛","ox (with reddish-brown)":"赤褐色牛",
"sheep":"羊","ram":"公羊","pig":"猪","swine, pig":"豕、猪","pigsty":"猪圈",
"dragon":"龙","bear":"熊","wolf":"狼","fox":"狐","hare":"兔","squirrel":"松鼠",
"monkey":"猴","bird":"鸟","deer":"鹿","a kind of deer":"一种鹿","stag":"牡鹿",
"buck":"牡兽","elk, moose":"驼鹿","moose":"驼鹿","maral":"马鹿",
"leopard, panther":"豹","a large feline":"大型猫科兽","viper; tiger, panther":"蝰蛇；虎、豹",
"stray animal":"走失的牲畜",

# --- nature ---
"sky":"天","heaven":"天、上天","god":"神","moon":"月","moon, month":"月亮、月份",
"month":"月份","water":"水","river":"河","lake":"湖","salt lake":"盐湖","sea, ocean":"海",
"ocean":"大洋","mountain":"山","wooded mountain":"林山","hill, peak":"丘、峰",
"hill, top":"丘、顶","top, summit":"顶、巅","glen, mountain-cleft":"山谷、山隙",
"stone":"石","gravel, pebble":"砾石","dry land":"陆地","mud":"泥","grass":"草",
"tree":"树","bush, tree":"灌木、树","leaf":"叶","dawn":"黎明","dawn, dusk":"晨昏",
"daytime, morning":"白昼、早晨","daytime, morning; noon":"白昼、早晨；正午","noon":"正午",
"night":"夜","yesterday":"昨日","time":"时","age":"年岁","beginning":"开端",
"spring":"春","spring; summer":"春；夏","summer":"夏","summer; spring":"夏；春",
"autumn":"秋","autumn, fall":"秋","winter":"冬","eternal":"永恒的",

# --- colours / qualities ---
"white":"白","black":"黑","red":"红","crimson":"绛红","green":"绿","blue, green":"青、绿",
"yellow":"黄","yellow; white":"黄；白","green, yellow":"绿、黄",
"bay reddish-brown":"赤褐色","bay, reddish-brown":"赤褐色",
"big":"大","big, powerful, great":"大、强盛","great, grand":"宏大","small":"小",
"small, little, young":"小、幼","narrow":"窄","thick":"厚","dense, thick, tough":"稠密、坚韧",
"stout":"粗壮","heavy":"重","soft":"软","sweet":"甜","good":"好","good, better":"好、更好",
"good, excellent":"良、优","bad":"坏","bad, evil":"恶","evil, sin":"罪恶","sin, evil":"罪、恶",
"fast, quick":"快","poor":"贫","rich":"富","rich, wealthy":"富有","crooked, bent":"弯曲",
"lean, exhausted":"瘦弱、疲惫","difficult, hard, tough":"艰难","few, a little":"少许",
"few, scanty":"稀少","few, very little":"极少","a little, a few":"少许","very few":"极少",
"very, extremely":"非常","extraordinary, wonderful":"非凡、奇妙",
"holy, sacred":"神圣的","sacred, holy":"神圣的","holy, regal, reverend":"神圣、尊贵",
"fortunate, blessed":"有福的","happy, blessed":"幸福的","sated, full":"饱足",
"in disorder, disorderly":"紊乱","mixed; disorderly":"杂糅；紊乱",

# --- things / culture ---
"arrow":"箭","bow":"弓","quiver":"箭袋","lance, spear":"矛","wall":"墙",
"city":"城","city, fortress":"城、堡","town, city":"城镇","stronghold, town":"要塞、城镇",
"house":"房屋","roof":"屋顶","palace":"宫殿","a royal camp, palace":"牙帐、王宫",
"camp, camping-site":"营地","camping-site":"营地","throne":"御座","grave":"墓",
"funeral":"葬礼","funeral service":"丧仪","sculpture":"雕像","inscription":"碑铭",
"road":"路","road, way":"道路","gold":"金","gold, golden":"金、金色","silver":"银",
"copper":"铜","silk":"丝绸","pearl":"珍珠","treasure":"宝物","clothing":"衣物",
"outfit, clothing":"衣装","wine":"酒","milk, dairy product":"乳、乳制品",
"meal, dish":"餐食","provisions":"粮秣","salt lake":"盐湖","lime":"石灰",
"smell, musk":"香气、麝香","smell, musk, scent":"香气、麝香","oath":"誓",
"glory":"荣光","praise":"颂扬","reputation, rank, fame":"声名、位望","power":"权力",
"strength":"力","order":"命令","profit, earnings":"利、所得","suffering":"苦难",
"lie, deceit":"谎言","battle, war":"战争","war":"战争","hunt":"狩猎","hunt, chase":"狩猎、追逐",
"hunt, hunting":"狩猎","hunger, famine":"饥荒","hungry, famished":"饥饿","sleep":"睡眠",
"by foot":"徒步","on foot":"徒步","south, southward":"南、向南","east, eastward":"东、向东",

# --- verbs ---
"to be":"是、存在","to become":"成为","to become, to happen":"成为、发生","to be able, capable":"能够",
"to be full":"满","to be satiated":"饱足","to be saturated":"充盈","to be lost":"迷失",
"to become lost":"迷失","to be separated":"被分离","to be overwhelmed":"被压倒",
"to be poured":"被倾注","to become lean":"消瘦","to become sick":"患病",
"to come":"来","to go":"去","to walk":"行走","to walk, go":"行走","to walk, move":"行进",
"to walk, to trot":"行走、小跑","to run":"奔跑","to fly":"飞","to flee":"逃",
"to follow, pursue":"追随","to follow; to conform":"追随；顺从","to approach":"接近",
"to reach":"到达","to rise up":"起身、兴起","to cause to ascend":"使升起",
"to outweigh; to rise up":"胜过；兴起","to mount":"骑乘","to sit":"坐","to sit, to settle":"坐、定居",
"to stand":"立","to lie down":"卧","to turn":"转","to roll":"滚","to spin":"旋",
"to spin, surround":"旋绕、环围","to shake":"摇","to stir":"搅动","to throw":"投掷",
"to take":"取","to take, to buy":"取、买","take":"取","take, buy":"取、买",
"to catch":"捕","to catch, grasp, hold":"捕捉、执持","to grasp":"执","to tie":"系",
"to tie, fasten":"系缚","to join":"连接","to unite":"联合","to unite, reunite":"联合、重聚",
"to separate":"分离","to separate from":"与……分离","to break, tear":"破、撕",
"to break, tear, demolish":"破坏、拆毁","to tear; to upset":"撕裂；扰乱",
"to open":"开","to close":"闭","to close, block":"闭塞","to press":"压",
"to press, collapse":"压塌","to squeeze":"挤压","to reduce, squeeze":"缩减、压榨",
"to bend":"弯","to dig":"掘","to pour":"倾注","to overflow":"溢出","to vaporize":"蒸腾",
"to scatter":"散布","to scatter, sprinkle":"散播","to scatter, put to rout":"驱散、击溃",
"to raise, put to flight":"驱起、使溃逃","to pillage, plunder":"劫掠",
"to send out a raid":"发兵劫掠","to conquer, to capture":"征服、攻取",
"to earn, conquer, win":"获取、征服","to win":"取胜","to fight, battle, war":"作战",
"to pierce, to war":"刺、征战","to frighten":"使惧","to fear":"惧","to hurt":"伤",
"to die":"死","to die, to pass away":"死去","to kill":"杀","to hunt":"狩猎",
"to hunger":"饥饿","to nourish":"养","to nourish, to feed":"哺养","to load":"装载",
"to bring":"带来","to carry, bear":"负载","to send":"遣送","to present, offer":"奉献",
"to organize, make":"组织、制作","to finish, complete":"完成","to find":"寻得",
"to find, to attain":"寻得、获致","to lose":"失去","to mistake":"错","to mistake, err":"错谬",
"to gather":"聚集","to know":"知","to know, to understand":"知晓","to understand":"理解",
"to think understand":"思、悟","to think, remember":"思、忆","to say":"说",
"to say, to tell":"说、告","to see":"见","to see, look":"看","to see; to look at":"见；观",
"to listen":"听","to listen, hear":"听闻","to write":"书写","to write, to inscribe":"书写、刻写",
"to praise":"颂扬","to rejoice":"欢喜","to rejoice, be happy":"欢喜","to wish":"愿",
"to approve":"许可","to approve, agree with":"许可、赞同","to deceive, trick":"欺骗",
"to worship, serve":"奉事","to live":"活",
"to order":"命令","to order, to request":"命令、请求","work, service":"工作、职事",
}
