#!/usr/bin/env python3
"""Chinese for the Old Turkic inscription passages (part C, 1/2).

These are quotations from the Orkhon corpus (Kültegin, Bilge Khagan, Tonyukuk)
and the Yenisei stones. Proper names follow the conventional Chinese forms used
in Chinese Türkological literature (于都斤, 黠戛斯, 暾欲谷, 阙特勤 …); the
rendering otherwise follows the English translation carried in the source, not a
published Chinese edition.
"""
G = {
"'Join me!' he said.":"他说：「随我来！」",
"'Let us reunite atop the Altai Mountains!\" he said.":"他说：「让我们在阿尔泰山上再会合！」",
"'We used to be people who had their own khagan. Where is our khagan now? To which khagan are we giving our services?' they said.":"他们说：「我们本是有自己可汗的百姓。如今我们的可汗何在？我们又在为哪一位可汗效力？」",
"'What (else) shall I say to you?' he said.":"他说：「我还能对你们说什么呢？」",
"(My father, the Khagan), profoundly glorified and praised the Turkic lords and people.":"（我父可汗）深深褒扬称颂突厥的诸匐与百姓。",
"(My father, the khagan), profoundly glorified and praised the Turkic lords and people.":"（我父可汗）深深褒扬称颂突厥的诸匐与百姓。",
"(Of you), those who survived there, utterly exhausted, were marching in every direction.":"（你们当中）在那里幸存下来的人，力竭至极，四散奔走。",
"(Of you,) those who survived there, utterly exhausted, were marching in all directions.":"（你们当中）在那里幸存下来的人，力竭至极，四散奔走。",
"(Then) I ordered them to ascend upward on foot, towing the horses after them, and holding onto the trees.":"（于是）我命他们徒步而上，牵马随行，攀树而进。",
"(Therefore) you, Chinese, attack them from the south, and you, Khitan, attack them from the east, and I shall attack them from the north.":"（因此）你们汉人自南面攻之，你们契丹自东面攻之，我则自北面攻之。",
"(They) held my father Ilterish Khagan and my mother El Bilga Khatun at the top of heaven and raised them upwards.":"（上天）将我父颉跌利施可汗与我母一利毗伽可敦擎于天顶，举而升之。",
"(Thus) we attacked and plundered (their camp).":"（于是）我们进击并劫掠了（他们的营地）。",
"...(they) held my father, Ilterish Khagan, and my mother, El Bilga Khatun, on top of heaven's hill and raised them upwards.":"……（上天）将我父颉跌利施可汗与我母一利毗伽可敦擎于天丘之上，举而升之。",
"...Arabs, Tocharians...":"……大食人、吐火罗人……",
"...Having feared the Arabic tribes and Tocharians...":"……既已畏惧大食诸部与吐火罗人……",
"...Prince Kül's gold and silver, his treasures and possessions...":"……阙特勤的金银、财宝与产业……",
"...Thirty Tatars, Khitans, Tatabi...":"……三十姓鞑靼、契丹、奚……",
"...a few of the people had fled...":"……有少数百姓逃散……",
"...and blue squirrels I gained for my Turkic people.":"……我为我突厥百姓取得了青鼠皮。",
"...and fell upon the Kyrgyz people while they were asleep.":"……趁黠戛斯人熟睡时袭之。",
"...and he had said that the Turkic people were in disorder.":"……他曾说突厥百姓已陷于紊乱。",
"...and how you would (otherwise) perish by making mistakes, this, too I have recorded here.":"……而你们如何会因失误而覆亡，此事我亦记于此。",
"...and since envy touched their galls...":"……又因妒意侵其肺腑……",
"...at the Year of Dragon...":"……于龙年……",
"...for the sake of the Turkic people, I did not sleep by night and I did not relax by day.":"……为突厥百姓之故，我夜不成寐，昼不得安。",
"...he campaigned all the way to the emperor of the Goguryeo Empire...":"……他一直征伐至高句丽之王……",
"...heavy stones and thick wood...":"……沉重的石料与粗大的木材……",
"...my people who have not been seen by eye and have not been heard by ear...":"……我那目所未见、耳所未闻的百姓……",
"...my relatives, my common Tölberi people, my Külik relatives, ownerless Elišim man, Ögüš man, Oγulan man, my sons in law, my daughters in law, I couldn't stay.":"……我的亲族、我的托勒别里众庶、我的库力克亲族，无主的埃利希姆人、厄居什人、奥古兰人，我的诸婿、我的诸媳——我不能久留了。",
"...or is there a lie in my word?":"……抑或我的话中有虚言？",
"...settled as far as the Iron Gate.":"……一直定居到铁门关。",
"...the soldiers of my father, the khagan, were like wolves and, his enemies were like sheep.":"……我父可汗的兵士如狼，其敌如羊。",
"...their lords fled.":"……他们的首领逃散。",
"...this many important rules...":"……如此众多的要则……",
"...under the presidency of the great general Li Quan, the father of ... came five hundred men.":"……以大将军李佺为首，……之父率五百人前来。",
"...your bones heaped up like a mountain.":"……你们的白骨堆积如山。",
"A land better than the Otuken mountains does not exist at all!":"没有比于都斤山更好的地方了！",
"After such people have settled close to them, they are said to plan their ill will there.":"据说这等人一旦迁居近旁，便在那里图谋不轨。",
"After they had numbered seven hundred men, (my father, the khagan), organized and ordered the people who had lost their state and khagan, the people that had turned into slaves and servants...":"待人数满七百之后，（我父可汗）整饬并统领那些失去国家与可汗、沦为奴仆的百姓……",
"At his fourth fights at Bish-Balyk, Kul-Chur made sudden attacks (on the enemy) and disordered...":"在别失八里的第四战中，阙啜突袭（敌军）并使之溃乱……",
"At the age of sixteen, for the sake of the realm and laws of my uncle, the khagan, he accomplished the following:..":"十六岁时，为我叔父可汗的国家与法度，他成就了如下之事：……",
"At the age of thirty-eight, in winter, I went on a campaign against the Khitan Empire.":"三十八岁那年冬，我出征契丹。",
"At the age of thirty-nine, in spring, I went on a campaign against the Kumo Xi.":"三十九岁那年春，我出征库莫奚。",
"Deceiving by means of their sweet words and soft materials, they are said to cause the remote people to come close in this manner.":"据说他们以甘言与柔软的财物行骗，如此诱使远方的百姓迁居近旁。",
"Drop off your carriages [loaded onto] she-camels [and hand them] to your younger and elder brothers.":"卸下驮在牝驼上的车辆，交与你们的兄弟。",
"Eastwards, to the sunrise, southwards to the midday, westwards as far as the sunset, and northwards to the midnight...":"东至日出之处，南至日中之地，西迄日落之所，北达夜半之乡……",
"First, we fought at the city of Toghu.":"我们首战于托古城。",
"From Tibet's emperor came a minister.":"吐蕃赞普遣一大臣前来。",
"From my divine realm, my provider, my son, my beloved son, my six thousand horses (alas, I have been separated).":"我的神圣邦国、我的养者、我的儿子、我所钟爱的儿子、我的六千匹马（呜呼，我已与之相离）。",
"General Zhang Quyi, the nephew of the Chinese emperor, came in order to build the mausoleum, to make sculptures, to paint and to prepare the insription stones.":"唐帝之侄张去逸将军前来，为营建陵寝、雕造石像、绘饰彩画并备置碑石。",
"Having arrived at an arid land...":"抵达一处旱地之后……",
"Having become a khagan in the company of the Wise Tonyukuk Boila Bagha Tarkhan, Ilterish killed in great numbers the Chinese to the south, the Kihtans to the east and the Oghuz to the north":"颉跌利施在智者暾欲谷保义巴伽达干的辅佐下称可汗，南破汉人、东破契丹、北破乌古斯，杀获甚众。",
"Having become utterly bored, the khagan said: 'Ride fast!'":"可汗厌倦已极，说道：「疾驰！」",
"Having carved our way through the lance-deep snow, we marched up over the Sayan Mountains and ambushed the Kyrgyz in [their] sleep.":"我们凿开没矛之深雪开道，翻越萨彦岭，趁黠戛斯人熟睡时掩袭之。",
"Having gone around the Sayan mountains, we came.":"我们绕过萨彦岭而来。",
"Having heard these words, you unwise people went close to them and were killed in great numbers.":"你们这些无知的百姓听信此言，迁居其旁，遂遭大批杀戮。",
"Having marched down along the Selenga, I destroyed their residences there, at the Qarghan glen.":"我沿色楞格河而下，在喀尔干山谷摧毁了他们的居所。",
"Having opened our way through the lance-deep snow...":"我们凿开没矛之深雪开道……",
"Having sat down twenty days, I, Prince Yollug, inscribed on this stone and on this wall.":"我药利特勤坐镇二十日，将文字刻于此石此壁之上。",
"Having succeeded to the throne, I gathered all the poor and destitute people together.":"我即位之后，将一切贫苦无依的百姓聚集起来。",
"He fought a great battle, we were told.":"据说他打了一场大仗。",
"He had said that the tribes were uneasy again.":"他曾说诸部又不安定了。",
"He hit one man with an arrow and stabbed two men through their thighs.":"他一箭射中一人，又刺穿两人的大腿。",
"He made the poor rich and the few numerous.":"他使贫者富，使寡者众。",
"He stabbed one man (with a lance) and stroke nine men surrounding them.":"他（以矛）刺倒一人，又击退围拢的九人。",
"He stabbed two men and buried them into the mud.":"他刺倒两人，将其埋于泥中。",
"He took the governor's brother-in-law prisoner while he had weapons in his hands, and presented him.":"他在总管的姊夫手持兵器时将其生擒，献了上来。",
"He went on campaigns forty-seven times and engaged in twenty battles.":"他出征四十七次，亲历二十战。",
"How you should live and dominate (other) tribes, I have recorded here; and how you would (otherwise) perish by being unfaithful, this, too, I have recorded here.":"你们当如何生存并统御（他）部，我记于此；而你们如何会因不忠而覆亡，此事我亦记于此。",
"I am brave against quick game.":"我对疾走的猎物勇猛不惧。",
"I conquer.":"我征服。",
"I fought six times.":"我交战六次。",
"I got them to build an extraordinary mausoleum.":"我命他们营建了一座非凡的陵寝。",
"I had its inside and outside decorated with wonderful paintings and sculptures (stones).":"我使其内外皆以精美的绘画与石雕装饰。",
"I killed a blue wolf, a black ermine and a buck.":"我猎杀了一只苍狼、一只黑貂和一头牡兽。",
"I killed seven wolves, but did not kill leopards or stags.":"我杀了七只狼，却未杀豹与牡鹿。",
"I killed skewbald goats [and] camels!":"我猎杀了花斑山羊与骆驼！",
"I made the poor people wealthy...":"我使贫苦的百姓富足……",
"I mounted my old horses.":"我骑上了我的老马。",
"I myself, wise Tonyukuk, was born in the country of China.":"我，智者暾欲谷，生于汉地。",
"I put their army, which had come assaulting and spreading, to flight.":"他们的军队铺开来袭，我将其击溃。",
"I ruled over a poor and miserable people who were foodless on the inside and clothless on the outside.":"我所统御的是内无食、外无衣的贫苦百姓。",
"I ruled over a poor and miserable people who were starving and ragless.":"我所统御的是饥馑而无衣蔽体的贫苦百姓。",
"I ruled over the Tardu people as their shad at the age of fourteen.":"我十四岁时以设的身份统御达头部众。",
"I said to myself and I thought: If lean bulls and fat bulls kick one another at a distance, one cannot distinguish between lean bulls and fat bulls, they say.":"我自忖道：据说瘦牛与肥牛在远处相抵，人便分不出何者为瘦、何者为肥。",
"I scatter my white froth.":"我洒开我的白沫。",
"I scatter.":"我散开。",
"I subjugated them and caused (their tribute) to be brought around.":"我使其臣服，并令（其贡赋）纳来。",
"I tied my gilded quiver onto my waist. I couldn't be satisfied of my holy country what pain! Alas!":"我将鎏金箭袋系于腰间。我未能饱览我神圣的国土，何其痛哉！呜呼！",
"I went on campaigns eastwards up to the Shandong plain; I almost reached the ocean.":"我东征直至山东平原，几乎抵达大海。",
"I, myself, was his advisor and commander.":"我本人是他的谋臣与统帅。",
"I, the God-like and Heaven-born Turkic Bilge Khagan, succeeded to the throne at this time.":"我，如天而生、受命于天的突厥毗伽可汗，于此时即位。",
"If the sky above did not collapse and if the earth below did not give away, O Turkic people, who would be able to destroy your state and institutions?":"若上天不塌、下地不陷，突厥百姓啊，谁能毁灭你们的国家与法度？",
"If you become hungry, you do not think of being satiated again, if you become satiated, you do not think of hunger again.":"你们饥饿时便不再想到饱足，饱足时便不再想到饥饿。",
"If you intend to settle on the Yin mountains and on the Hetao region's plain in the south, O Turkic people, you will die!":"突厥百姓啊，你们若打算迁居南方的阴山与河套平原，你们必将灭亡！",
}
