#!/usr/bin/env python3
"""Chinese for the Old Turkic inscription passages (part D, 2/2). See part C."""
G = {
"If you would throw it, you were the hero; if you would hold it, you were the power itself.":"你若掷出，你便是英雄；你若执守，你便是力量本身。",
"In order to frighten them, I started a campaign.":"为震慑他们，我兴兵出征。",
"In the day and the night I perished [over the loss of my wife and my master.]":"日日夜夜，我为失去妻子与主君而形销骨立。",
"In the year of Pig, on the twenty-seventh day of the fifth month...":"猪年五月二十七日……",
"Mankind were always created to die when heaven assigns the time.":"人生而有死，天定其期。",
"May golds as yellow as pebbles, my dromedaries that are fat and brown, my colt/gelded camel carrying silk clothes.":"愿我那砾石般焦黄的金子、我那肥硕棕褐的骆驼、我那驮载丝衣的骟驼……",
"My colts/gelded camels...":"我的骟驼……",
"My eyes which have always seen became as if they were blind, my mind which has always been conscious became as if it were unconscious.":"我一向能视的眼睛如同盲了，我一向清醒的心智如同失了知觉。",
"My father, as the first order of business as a khagan, erected a consecratory monument for [the late] Baz Khagan.":"我父为可汗后所办的第一件事，便是为已故的巴兹可汗立起祭碑。",
"My gold that is yellow like gravel...":"我那砾石般焦黄的金子……",
"My lords, lo!":"我的诸匐啊！",
"My mother the queen regent and my [step-]mothers, my elder sisters, my daughters-in-law, my ladies […]":"我摄政的母后与诸位庶母、我的诸姊、我的诸媳、我的诸夫人……",
"My mother, the khatun, and my (step-)mothers, my elder sisters, my daughters-in-law, my princesses this many people who were going to survive would have become slaves, and those of you who were going to be killed would have been left lying at the camp and on roads.":"我母可敦与诸位庶母、我的诸姊、我的诸媳、我的诸公主——这许多本可存活的人将沦为奴婢，而你们当中本将被杀者，则会横尸于营地与道旁。",
"My wife, the princess, at hearth became a widow, alas!":"我的妻子，那位公主，在炉边成了寡妇，呜呼！",
"Now, since I, wise Tonyukuk, cause (the Turkic armies) to reach as far as those lands, they brought (home) the yellow gold and the white silver; girls and women; crooked camels and treasures in abundance.":"如今，因我智者暾欲谷使（突厥大军）远抵那些地方，他们带回了黄金白银、女子妇人、驼峰高耸的骆驼与丰足的珍宝。",
"O my sworn and unsworn comrades, o my good companion! I departed!":"我那结盟与未结盟的同伴啊，我的良友啊！我去了！",
"O, my foal with a white forehead!":"我那白额的马驹啊！",
"On the second day, I killed their foot soldiers in great numbers.":"第二日，我大量杀伤他们的步卒。",
"One half of their army marched off in order to plunder our residences, the other half of their army came in order to fight.":"他们的军队一半开去劫掠我们的居所，另一半前来接战。",
"Or was there any lie in what I said?":"抑或我所说的话中有虚言？",
"Our army horses were lean and army had no provisions":"我们的战马消瘦，军中没有粮秣。",
"Prince Kül put their army, which had come assaulting, to flight and we surrounded and killed a Tongra squad consisting of ten champion warriors at the funeral of Prince Tonga.":"阙特勤击溃了前来进攻的敌军；在同俄特勤的葬礼上，我们围歼了由十名勇士组成的同罗小队。",
"Since God gave them power, my father's, the kaghan's, army was like wolves, their enemies were like sheep.":"因上天赐其力量，我父可汗的军队如狼，其敌如羊。",
"Since their envoys, their good news and their blessings stopped coming to us, I went on a campaign in the summer.":"因他们的使者、佳音与祝祷不再传来，我于夏日出征。",
"Since they didn't send a caravan, I sent an army.":"因他们不遣商队前来，我便发兵。",
"That which is thin is easy to bend, they say; that which is tender is easy to break. If thin becomes thick, it is hard to bend it, they say; and if tender becomes tough, it is hard to break it, they say.":"据说，细者易折，嫩者易断；细者若变粗，便难以弯折；嫩者若变韧，便难以折断。",
"That year, during autumn, I marched forward […]":"那年秋天，我挥师前进……",
"The Elteber of Uyghurs fled towards and regrouped in the east, with around a hundred men.":"回鹘的俟利发率百余人东逃并重整队伍。",
"The Heaven above and the sacred Earth [below] approved the heavenly favor of my uncle, the khagan.":"上天与神圣的大地嘉许我叔父可汗所受的天佑。",
"(literally, “ […] his heavenly favor [they] did not curse.”)":"（直译：「……他们未曾诅咒他所受的天佑。」）",
"The Turkic lords (and) people worshipped (me), loved (me) and raised their eyes up.":"突厥的诸匐与百姓敬奉我、爱戴我，举目仰望。",
"The Turkic lords abondened their Turkic titles. Those lords who were in China held the Chinese titles and obeyed the Chinese emperor and gave their services to him for fifty years.":"突厥的首领们弃去了突厥的官号。身在汉地的那些首领受汉家官号、听命于唐帝，为其效力五十年。",
"The Turkic people's feet tottered and were about to be put to rout.":"突厥百姓步履踉跄，几近溃散。",
"The governor of the Uyghurs, together with about one hundred men, fled toward the east...":"回鹘的长官率百余人向东逃走……",
"The great irkin, ran away together with very few men.":"大俟斤仅率寥寥数人逃走。",
"The khagan of the Ten Tribes was our enemy.":"十姓部落的可汗是我们的敌人。",
"The people's throats were full.":"百姓的喉咙都是饱足的。",
"Their ministers, too, were presumably wise and tough.":"想必他们的大臣也是明智而强悍的。",
"Their officers, too, were presumably wise and tough.":"想必他们的将官也是明智而强悍的。",
"They brought scent[ed candle]s for the funeral and set them up for us. […]":"他们为葬礼送来香烛，并为我们设置妥当。……",
"They brought scented (candles) for the funeral and set them up for us.":"他们为葬礼送来香烛，并为我们设置妥当。",
"They brought their good saddle-horses, their black sables and blue squirrels in an uncountable number and left them all.":"他们带来良骑、黑貂与青鼠，数不胜数，尽数留下。",
"They gift us gold, silver and silk in abundance like so.":"他们如此这般以丰厚的金银与丝帛相赠。",
"They give us gold, silver and silk in abundance.":"他们以丰厚的金银与丝帛给予我们。",
"They hit (him) with more than a hundred arrows on his armor and caftan; (but he did not let the enemy hit him) even once on his face or head.":"他们在他的甲胄与外袍上射中百余箭，却未曾（让敌人）射中他的面部与头颅一次。",
"They made bow those, who had heads and made kneel those, who had knees.":"他们使有头者俯首，使有膝者屈膝。",
"Thirdly, he mounted Lord Yegen Silig's dressed bay horse and attacked.":"第三次，他骑上叶根·思力匐披挂整齐的赤褐马冲杀。",
"This many peoples cut out their hairs and tore their ears.":"这许多百姓割发裂耳（以志哀）。",
"Thus we stayed at the Altai Mountains.":"我们就这样驻留于阿尔泰山。",
"To my thousand horses with no owners":"致我那千匹无主之马。",
"Together with my younger brother, Prince Kül, and together with two shads, dying and getting lost, I won.":"我与我弟阙特勤、并两位设一同出战，虽死伤离散，终获胜利。",
"Tun Yegen Erkin.":"敦·叶根·俟斤。",
"Turkic people were famished.":"突厥百姓陷于饥馑。",
"Turkic warlords lost their Turkic names and titles, [while] Chinese warlords kept their Chinese titles and served the Chinese emperor.":"突厥的将领失去了突厥的名号，而汉家将领仍保有汉家官号，为唐帝效力。",
"We are few.":"我们人少。",
"We are going to stay.":"我们将留下。",
"We descended rolling.":"我们翻滚而下。",
"We finished his mausoleum, statues and paintings, and his inscription stone on the twenty-seventh day of the seventh month, on the Year of Monkey.":"猴年七月二十七日，我们完成了他的陵寝、石像、彩画与碑石。",
"We fought five times in a year.":"我们一年之内交战五次。",
"We fought with their kagan at the Songa mountains.":"我们在松阿山与他们的可汗交战。",
"We ordered (the army) to carry out a raid, while we left Prince Kül at home to command (the camp).":"我们下令（大军）出击劫掠，而留阙特勤在后统领营地。",
"We surrounded and killed a Tongra squad consisting of ten champion warriors at the funeral of Prince Tonga.":"在同俄特勤的葬礼上，我们围歼了由十名勇士组成的同罗小队。",
"We tied horses to the trees.":"我们把马系在树上。",
"We went on a campaign in the direction of six Sogdian states.":"我们朝六个粟特邦国的方向出征。",
"We went on campaigns up to the land of Kyrgyzes, beyond the Tannu-Ola mountains.":"我们出征直至唐努乌拉山以北的黠戛斯之地。",
"We were but a few [people], we were in bad shape.":"我们人数寥寥，处境窘迫。",
"Westwards I went on campaigns up to the Iron Gate beyond Syr Darya...":"我向西出征，直抵锡尔河以远的铁门关……",
"When I heard that there is only one road to the Sayan Mountains, and it is (now) closed (by snow), I said: 'If we go that way, it will not be good (for us)'.":"我听说通往萨彦岭只有一条路，而这条路（此时）已被大雪封闭，便说：「若走那条路，于我们不利。」",
"When I was seventeen years old, I went on a campaign against the Tangut.":"我十七岁那年出征党项。",
"When he fought seven times against the Nine Oghuzes, he poured them (on the river).":"他与九姓乌古斯交战七次，将他们（尽数）倾覆于河上。",
"When my father, the khagan, passed away, I was at the age of eight.":"我父可汗辞世时，我年方八岁。",
"When my oldest son died of being sick, I readily had Qu, the general, erect him a balbal.":"我的长子病故时，我即命曲将军为他竖立杀人石。",
"When there is valor, there is no sorrow, and when there is sorrow, then I am the hero Ezeru":"有勇则无忧；忧至之时，我便是英雄埃泽鲁。",
"When you are famished, you do not think of being full, [likewise,] you do not think of hunger once you get full [either.]":"你饥饿时不会想到饱足；同样，你饱足之后也不会想到饥饿。",
"Why should we feel overwhelmed because of being few?":"我们何须因人少而气沮？",
"Without having found their khan, the Turkic people were parted from the Chinese, and got themselves a khan.":"突厥百姓尚未寻得自己的可汗便与汉人分离，随后自立了一位可汗。",
"You are stubborn.":"你很固执。",
"You will be wrong.":"你将有错。",
"You will die.":"你将死去。",
"[It is said that] they have created [it].":"据说是他们造的。",
"[The Chinese] do not let the people who know well and the people who are valiant tire themselves.":"（汉人）不让明智者与勇武者自劳其身。",
"[While] thinking that I shall feed [the people] […]":"我一面思量着要养活（百姓）……",
"[…] and served under them for fifty years.":"……并在他们麾下效力五十年。",
"[…] once you get full, you would not think of famishing again.":"……你一旦饱足，便不会再想到饥馑。",
"bars:beg:erti":"bars:beg:erti（巴尔斯匐也）",
"...it was Bars Bek.":"……那是巴尔斯匐。",
"b¹:b¹l¹as¹r¹":"b¹:b¹l¹as¹r¹",
"/ab:ablasar/":"/ab:ablasar/（若行猎）",
"While hunting...":"行猎之时……",
# kaikki joins a translation with its appended literal note using a newline;
# the combined string is what the entry actually displays.
"The Heaven above and the sacred Earth [below] approved the heavenly favor of my uncle, the khagan.\n(literally, \u201c […] his heavenly favor [they] did not curse.\u201d)":"上天与神圣的大地嘉许我叔父可汗所受的天佑。\n（直译：「……他们未曾诅咒他所受的天佑。」）",
"bars:beg:erti\n...it was Bars Bek.":"bars:beg:erti\n……那是巴尔斯匐。",
"b\u00b9:b\u00b9l\u00b9as\u00b9r\u00b9\n/ab:ablasar/\nWhile hunting...":"b\u00b9:b\u00b9l\u00b9as\u00b9r\u00b9\n/ab:ablasar/\n行猎之时……",
}
