#!/usr/bin/env python3
"""Chinese for the longer Old Turkic glosses (part B). Merged by merge_glosses.py.

The letter definitions are formulaic and are rendered on one pattern:
    A letter of the Old Turkic runic script, representing /X/, used with Y vowels.
    古突厥卢尼文字母，表 /X/，用于 Y 元音词。
"""
G = {
# --- alphabet ---
"A letter of the Old Turkic runic script, representing /bɑʃ/":"古突厥卢尼文字母，表 /bɑʃ/。",
"A letter of the Old Turkic runic script, representing /itʃ/.":"古突厥卢尼文字母，表 /itʃ/。",
"A letter of the Old Turkic runic script, representing /lt/":"古突厥卢尼文字母，表 /lt/。",
"A letter of the Old Turkic runic script, representing /m/.":"古突厥卢尼文字母，表 /m/。",
"A letter of the Old Turkic runic script, representing /nt/":"古突厥卢尼文字母，表 /nt/。",
"A letter of the Old Turkic runic script, representing /ntʃ/.":"古突厥卢尼文字母，表 /ntʃ/。",
"A letter of the Old Turkic runic script, representing /p/.":"古突厥卢尼文字母，表 /p/。",
"A letter of the Old Turkic runic script, representing /t͡ʃ/.":"古突厥卢尼文字母，表 /t͡ʃ/。",
"A letter of the Old Turkic runic script, representing /ŋ/.":"古突厥卢尼文字母，表 /ŋ/。",
"A letter of the Old Turkic runic script, representing /ɑʃ/.":"古突厥卢尼文字母，表 /ɑʃ/。",
"A letter of the Old Turkic runic script, representing /ɯq/.":"古突厥卢尼文字母，表 /ɯq/。",
"A letter of the Old Turkic runic script, representing /ɲ/":"古突厥卢尼文字母，表 /ɲ/。",
"A letter of the Old Turkic runic script, representing /ʃ/.":"古突厥卢尼文字母，表 /ʃ/。",
"A letter of the Orkhon script":"鄂尔浑文字母。",
"A letter of the Orkhon script.":"鄂尔浑文字母。",
"A variant letter of the Orkhon script":"鄂尔浑文字母的变体。",
"A letter of the Old Turkic runic script, representing /b/ and /v/ used with front vowels.":"古突厥卢尼文字母，表 /b/、/v/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /b/ and /v/, used with back vowels.":"古突厥卢尼文字母，表 /b/、/v/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /d/ and /ð/, used with back vowels.":"古突厥卢尼文字母，表 /d/、/ð/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /d/ and /ð/, used with front vowels.":"古突厥卢尼文字母，表 /d/、/ð/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /j/, generally used with front vowels.":"古突厥卢尼文字母，表 /j/，一般用于前元音词。",
"A letter of the Old Turkic runic script, representing /j/, used with back vowels.":"古突厥卢尼文字母，表 /j/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /j/, used with front vowels.":"古突厥卢尼文字母，表 /j/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /k/, used with front vowels.":"古突厥卢尼文字母，表 /k/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /l/ with back vowels.":"古突厥卢尼文字母，表 /l/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /l/, used with front vowels.":"古突厥卢尼文字母，表 /l/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /n/ with back vowels.":"古突厥卢尼文字母，表 /n/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /n/, used with front vowels.":"古突厥卢尼文字母，表 /n/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /ot/ (Irk Bitig and Yenisei Kyrgyz)":"古突厥卢尼文字母，表 /ot/（见于《占卜书》与叶尼塞黠戛斯文献）。",
"A letter of the Old Turkic runic script, representing /q/ used with back vowels.":"古突厥卢尼文字母，表 /q/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /r/, used with back vowels.":"古突厥卢尼文字母，表 /r/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /r/, used with front vowels.":"古突厥卢尼文字母，表 /r/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /s/, used with back vowels.":"古突厥卢尼文字母，表 /s/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /s/, used with front vowels.":"古突厥卢尼文字母，表 /s/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /t/, used with back vowels.":"古突厥卢尼文字母，表 /t/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /t/, used with front vowels.":"古突厥卢尼文字母，表 /t/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /uq/, /oq/, /qu/, /qo/, used with back vowels.":"古突厥卢尼文字母，表 /uq/、/oq/、/qu/、/qo/，用于后元音词。",
"A letter of the Old Turkic runic script, representing /yk/, /øk/, /ky/, /kø/ used with front vowels.":"古突厥卢尼文字母，表 /yk/、/øk/、/ky/、/kø/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /yp/, /øp/, /py/, /pø/ used with front vowels.":"古突厥卢尼文字母，表 /yp/、/øp/、/py/、/pø/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /z/, used in both vowel types.":"古突厥卢尼文字母，表 /z/，前后元音词通用。",
"A letter of the Old Turkic runic script, representing /ø/ or /y/.":"古突厥卢尼文字母，表 /ø/ 或 /y/。",
"A letter of the Old Turkic runic script, representing /ɡ/, used with front vowels.":"古突厥卢尼文字母，表 /ɡ/，用于前元音词。",
"A letter of the Old Turkic runic script, representing /ɣ/, used with back vowels.":"古突厥卢尼文字母，表 /ɣ/，用于后元音词。",

# --- morphology ---
"-less; a suffix denoting the lack of something":"表「无……」的后缀。",
"Alternative form of 𐰜 (ök) after back vowels":"𐰜（ök）在后元音后的异体。",
"Denotes \"to be\" for first person plural":"表第一人称复数的系动成分。",
"Denotes \"to be\" for first person singular":"表第一人称单数的系动成分。",
"Denotes \"to be\" for second person plural":"表第二人称复数的系动成分。",
"Denotes \"to be\" for second person singular or plural":"表第二人称单复数的系动成分。",
"Denotes first person plural after certain verb tenses.":"接于某些动词时态后，表第一人称复数。",
"Denotes first person singular after certain verb tenses.":"接于某些动词时态后，表第一人称单数。",
"Denotes second person plural after certain verb tenses.":"接于某些动词时态后，表第二人称复数。",
"Denotes second person singular or plural after certain verb tenses.":"接于某些动词时态后，表第二人称单数或复数。",
"Forms adjectives or nouns out of verbs":"由动词构成形容词或名词。",
"Forms dative-locative case":"构成与位格。",
"Forms deverbal negative verbs.":"由动词构成否定动词。",
"Forms non-evidential past tense":"构成非亲见过去时。",
"Forms past tense of verbs":"构成动词过去时。",
"Forms reflexive verbs from intransitive or transitive ones":"由不及物或及物动词构成反身动词。",
"Forms reflexive verbs from nouns":"由名词构成反身动词。",
"Forms simple present tense and aorist tense":"构成一般现在时与泛时。",
"Forms the accusative case":"构成宾格。",
"Forms the collective of numerals":"构成数词的集合形式。",
"Forms the comitative case":"构成共同格。",
"Forms the future tense of verbs":"构成动词将来时。",
"Forms the locative-ablative case":"构成位从格。",
"Forms the ordinal of numerals":"构成序数词。",
"Forms transitive or causative of verbs":"构成动词的及物式或使动式。",
"Forms verbs with the sense of being ordered to do them":"构成表「被命令去做」的动词。",
"Forms objects out of transitive verbs; forms subjects or action nouns out of intransitive verbs":"由及物动词构成受事名词；由不及物动词构成施事名词或动作名词。",
"Forms transitive verbs from intransitive ones; forms causative verbs from transitive ones":"由不及物动词构成及物动词；由及物动词构成使动动词。",
"Makes converbs and adverbs out of verbs yielding \"by, ...-ing\"":"由动词构成副动词与副词，义为「以……、正在……」。",
"Marks a superlative degree (-est).":"表最高级。",
"Suffix creating a verb from a noun":"由名词构成动词的后缀。",
"Suffix forming first person plural imperative":"构成第一人称复数命令式的后缀。",
"Suffix forming first person singular imperative":"构成第一人称单数命令式的后缀。",
"Suffix forming nouns from verbs":"由动词构成名词的后缀。",
"Suffix forming second person plural imperative":"构成第二人称复数命令式的后缀。",
"Suffix forming second person singular imperative":"构成第二人称单数命令式的后缀。",
"Suffix forming third person imperative":"构成第三人称命令式的后缀。",
"Used to form adverbs from adjectives":"由形容词构成副词。",
"first person plural possessive suffix":"第一人称复数领属后缀。",
"first person plural suffix for certain verb tenses":"用于某些动词时态的第一人称复数后缀。",
"first person singular possessive suffix":"第一人称单数领属后缀。",
"first person singular possessive suffix for certain verb tenses":"用于某些动词时态的第一人称单数领属后缀。",
"second person plural possessive suffix":"第二人称复数领属后缀。",
"second person plural suffix for certain verb tenses":"用于某些动词时态的第二人称复数后缀。",
"second person singular possessive suffix":"第二人称单数领属后缀。",
"second person singular suffix for certain verb tenses":"用于某些动词时态的第二人称单数后缀。",
"third person possessive suffix":"第三人称领属后缀。",
"vocative particle, used for direct address; o, hey!":"呼语助词，用于直接称呼；啊、喂！",

# --- pronouns ---
"first person singular pronoun":"第一人称单数代词。",
"the first person plural pronoun":"第一人称复数代词。",
"the second person plural pronoun":"第二人称复数代词。",
"the second person singular pronoun":"第二人称单数代词。",
"third person singular pronoun":"第三人称单数代词。",
"he, she, it, they; third person general pronoun":"他、她、它、他们；第三人称通用代词。",
"that; distal demonstrative pronoun":"那；远指指示代词。",

# --- alternative spellings ---
"alternative spelling of 𐰋𐰃𐱁 (béš)":"𐰋𐰃𐱁（béš）的异写。",
"alternative spelling of 𐰋𐰤 (ben)":"𐰋𐰤（ben）的异写。",
"alternative spelling of 𐰢𐰤 (men)":"𐰢𐰤（men）的异写。",
"alternative spelling of 𐰾𐰋𐰤 (sebin-)":"𐰾𐰋𐰤（sebin-）的异写。",
"children (irregular plural of 𐰆𐰍𐰞 (uǧl¹ /⁠oɣul⁠/, “child”))":"子女（𐰆𐰍𐰞 uǧl¹ /oɣul/「子」的不规则复数）。",

# --- proper names / history ---
"Bilge Khagan, a khagan of the Second Turkic Khaganate":"毗伽可汗，后突厥汗国可汗。",
"Bumin, the first khagan and the founder of the First Turkic Khaganate":"土门，突厥第一汗国的开国可汗。",
"Tonyukuk, a tarkhan & adviser of the Second Turkic Khaganate":"暾欲谷，后突厥汗国达干、谋臣。",
"Tengri, the chief deity of Turkic mythology.":"腾格里，突厥神话中的至上神。",
"Turkic people, the Göktürks":"突厥人、蓝突厥。",
"Rome, Byzantium, eastern Romans":"罗马、拜占庭、东罗马人。",
"Shandong (a region of China)":"山东（中国地区名）。",
"Otuken, the capital of the First Turkic Khaganate and the Uyghur Khaganate.":"于都斤，突厥第一汗国与回鹘汗国的都城所在。",
"Shad, a title, usually considered to be one step below the khagan":"设，官号，一般视为仅次于可汗一级。",
"Tibet (a geographic region in Central Asia, the homeland of the Tibetan people)":"吐蕃（中亚地区名，藏人故土）。",
"A Tatar, a member of one of the major tribal confederations in the Mongolian Plateau (8th–12th centuries).":"鞑靼人，八至十二世纪蒙古高原主要部落联盟之一的成员。",
"General Zhang Quyi, the nephew of Emperor Xuanzong who was sent in order to attend to Kültegin's funeral":"张去逸将军，唐玄宗之侄，奉命参与阙特勤葬礼。",
"Li Quan, a Tang Dynasty general sent by the Chinese emperor for Bilge Khagan's funeral":"李佺，唐朝将领，奉唐帝之命参与毗伽可汗葬礼。",
"Lǚ Xiàng, a Chinese ambassador under the service of Emperor Xuanzong":"吕向，唐玄宗朝使臣。",
"Maharaja, a seal-keeper of a khagan of the Türgesh tribe who was sent in order to attend to Kültegin's funeral":"摩诃罗阇，突骑施可汗的掌印官，奉命参与阙特勤葬礼。",
"general, a male given name":"将军；亦用作男子名。",

# --- nouns ---
"a kind of male deer; moose, elk, maral":"一种牡鹿；驼鹿、马鹿。",
"a type of female ruler; khatun, queen, empress":"女性统治者；可敦、王后、皇后。",
"a type of large feline; panther, leopard, tiger":"大型猫科兽；豹、虎。",
"a type of nobility, seemingly close to the ruler; boyar, boila":"一种贵族称号，似为近臣；boyar、boila。",
"used for various titles; hero, champion, warrior, officer":"用于多种称号；英雄、勇士、武将。",
"head of a clan, chief, lord, beg":"氏族之长、首领、伯克。",
"sergeant; noncommissioned officer":"军士、士官。",
"one who acquires, obtains; provider; earner":"获取者、供给者、挣得者。",
"ancestor, father, forefather":"祖先、父、先人。",
"area covered with stones; shallow":"多石之地；浅滩。",
"craftiness, deception, magic":"狡诈、欺骗、巫术。",
"decoration, ornamentation":"装饰、纹饰。",
"decoration, ornamentation, flourish":"装饰、纹饰、藻绘。",
"distress, suffering, grief, melancholy":"苦楚、忧伤、愁郁。",
"district, state, area, region, zone":"州、地区、区域。",
"exterior, outside of something":"外部、外侧。",
"good fortune, happiness, joy":"福运、幸福、喜乐。",
"good fortune, happiness, joy; the favour of heaven":"福运、幸福、喜乐；天赐之佑。",
"ground, earth, land, place":"地、土地、处所。",
"herbivorous wild animals, game, prey, deer":"食草野兽、猎物、鹿。",
"house, dwelling-place; tent":"房舍、居所；帐幕。",
"hunt, hunting expedition, prey":"狩猎、田猎；猎物。",
"knowledge, information, will":"知识、消息、意志。",
"marked spot on animal's head":"兽首上的斑记。",
"white spot on an animal's head":"兽首上的白斑。",
"material, treasure, wealth":"财物、宝货、财富。",
"monument, consecratory statue for the deceased, usually for noblemen and rulers":"纪念碑、为逝者所立的祭像，多为贵族与统治者而设。",
"road, a way used for travelling between places":"道路，往来于各地之途。",
"stature, size; tribe, kin":"身量、体格；部族、亲族。",
"the interior of something":"某物的内部。",
"time (a point, or a period)":"时（时点或时段）。",
"a drink which is mixture of blood and koumiss that been used for taking an oath.":"血与马奶酒调和而成的饮品，用于盟誓。",
"year of the Pig, the twelfth year under the twelve-year lunar cycle.":"猪年，十二年周期中的第十二年。",

# --- adjectives / adverbs ---
"difficult, hard, brave; warrior":"艰难、刚强；勇士。",
"eternal, everlasting, forever":"永恒、长存、永远。",
"fortunate, blessed, happy":"有福的、蒙佑的、欢喜的。",
"having a ruler, independent":"有君主的、自主的。",
"important, worthy, expensive":"重要的、可贵的、昂贵的。",
"in order to, due to, since":"为了、因为、既然。",
"like that, so, in that way":"如彼、这样、以那种方式。",
"presumably, supposedly, certainly":"想必、据称、确然。",
"uneasy, difficult, hard to manage (of a person or animal)":"难驯、难以驾驭（指人或牲畜）。",
"white, light-colored (said of a coat of a horse)":"白色、浅色（指马的毛色）。",

# --- verbs ---
"to be (something, somewhere)":"是、在（某物、某处）。",
"to be able, to be capable":"能够、胜任。",
"to be caught on something":"被某物挂住、缠住。",
"to be hungry, to be famished":"饥饿、饥馑。",
"to be pleased by, to like, to allow":"喜悦于、喜爱、准许。",
"to like, to be pleased by":"喜爱、欢喜。",
"to become a male slave, servant":"沦为奴仆。",
"to become lean, be emaciated, become exhausted":"消瘦、羸弱、力竭。",
"to bother; to create disorder":"扰扰、生乱。",
"to count, consider, think":"计数、认为、思量。",
"to deceive; to cast spells":"欺瞒；施法。",
"to finish, to complete, to destroy":"完成、终结、毁灭。",
"to go astray, lose one's way":"迷途、失路。",
"to go astray, to lose one's way":"迷途、失路。",
"to go astray, to lose one's way; to die, perish":"迷途、失路；死亡、消亡。",
"to live (up to a certain age)":"活（至某年岁）。",
"to raid, attack, suppress":"袭掠、攻打、镇压。",
"to rejoice, be happy, be joyful":"欢喜、快乐。",
"to retreat, to take a step back":"后退、退让一步。",
"to return, to have a change of mind, to step back":"返回、改意、退步。",
"to rise, to ascend, to climb":"上升、攀登。",
"to sit, to settle; to rule, to be throned":"坐、定居；临御、即位。",
"to stand, stay, continue to exist":"站立、留驻、续存。",
"to stir, mix, disturb, cause trouble":"搅动、混杂、扰乱、生事。",
"to tell, to declare, to order":"告知、宣示、命令。",
"to think, think of, remember":"思、念、忆。",
"to earn wages by labour, to gain profits by trade, to strive for success":"以劳力得酬、以贸易获利、力求功成。",
"to produce a state of disorder, put in disorder, to disturb, to cause trouble":"造成混乱、扰乱、生事。",
}
