#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part D — 例句余部与词条释义之始.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_d.py; edit that.
"""
G = {
'Used to form adjectives or nouns denoting the non-possession of a thing or quality; -less':
    '构成表示不具某物或某性质的形容词或名词；相当于「无……的」',
'Uyghur, an extinct Turkic ethnic group who lived in the Tarim Basin, Eastern Central Asia and Western China between 8th and 15th century.':
    '回鹘，8 至 15 世纪居于塔里木盆地、中亚东部与中国西部的一支已消亡的突厥语族群。',
'We [once] lived in a joyful world.':
    '我们〔曾〕生活在一个欢乐的世界。',
"We do not commit what is contrary to the God's commands.":
    '我们不做违背神诫命的事。',
'We have secured the girl. We have received great favours and honours.':
    '我们已得到那女子。我们受了大恩宠与荣誉。',
'We nomadized, settled and set to make [a new place] our home.':
    '我们迁徙游牧，安顿下来，着手把〔新的地方〕当作家园。',
'We set up a trap.':
    '我们设下陷阱。',
'Wealthy people cannot acquire knowledge through wealth, strong people cannot acquire knowledge through hubris.':
    '富人不能以财富获得知识，强者不能以傲慢获得知识。',
'What happened? Why are you speaking like that? Speak distinctly [= clearly!]':
    '出了什么事？你为何这样说话？说分明些〔＝说清楚！〕',
'When dangers and perils, illness and infirmities come and will not go away […]':
    '当危难险厄、疾病衰弱到来而不肯离去〔……〕',
'Where will [unmarried] boys and girls go then?':
    '那么〔未婚的〕少男少女将往何处去？',
'Why should her pail get frozen? It sits in the sunshine.':
    '她的桶怎会结冰？它正放在日头下。',
'With a handful of […]':
    '以一把〔……〕',
'You did not attain the Path of Departure because of your vile deeds [and] your thoughts [that are] attached [to this material world.]':
    '你因自己的恶业〔与〕执着〔于此物质世界〕的念头，未能证得出离之道。',
'You have freed [all] the living beings in the five modes of existence from ignorance.':
    '你已使五趣中〔一切〕众生脱离无明。',
'You have made them grasp the [religious doctrine] distinctly [= clearly], [and] gathering them all under your guise, your sublime, merciful conscience , freed them from the cyclical modes of existence.':
    '你使他们分明地〔＝清楚地〕领会〔教法〕，〔并〕将他们尽收于你的形相、你崇高慈悯的心识之下，令其脱离轮回诸趣。',
'You have saved […] . Eight kinds of suffering […]':
    '你已救度〔……〕。八种苦〔……〕',
'You separated my teacher from me.':
    '你使我与我的师长分离。',
'Your older sisters and older sisters-in-law are cheerful.':
    '你的姊姊与嫂嫂们都很欢快。',
'Your physical ailments are painful [to endure.] Your possessions are scattered [among people.]':
    '你的身病〔难以〕忍受。你的财物散〔于人间〕。',
'[... Boiled] milk should be prepared for [a patient] suffering from a blood-bilious ailment [and/or a patient who has] consumed poison...':
    '〔……〕当为患血胆之疾者〔及／或〕中毒者备〔煮沸的〕乳……',
"[... or] accepting a bad companion's or friend's word [and] doing as they do, [or] being troubled for cattle and worldly property […]":
    '〔……或〕听信恶伴、恶友之言〔并〕效其所行，〔或〕为牲畜与世间财产所扰〔……〕',
'[... the condition] develops as a result of heavy, sour [and] salty foods, [as well as a result of] alcoholism caused by phlegm [buildup in the body.]':
    '〔……此症〕因厚味、酸〔与〕咸的食物而起，〔亦因〕体内痰〔积〕所致的酗酒而起。',
'[...for] the monks, and mothers and fathers; for they found and followed them, up to and through deserts and wastelands, and wild forests and woods […]':
    '〔……为〕僧众、为父母；因他们寻得并跟随之，直至穿越沙漠荒野、莽林深樾〔……〕',
'[07th day:] A good match.\n[08th day:] A bad match.\n[09th day:] A good match.\n[11th day:] Do not take [their hand in a relationship,] you will wilt away.\n[12th day:] They will support you.\n[13th day:] They will be detrimental for you.':
    '〔初七日：〕良配。\n〔初八日：〕恶配。\n〔初九日：〕良配。\n〔十一日：〕勿〔与之结亲〕，你将日渐憔悴。\n〔十二日：〕他们会扶助你。\n〔十三日：〕他们于你有害。',
'[4:] One copper [cup] of galbanum, two copper [cups] of crepe ginger […] if there is pain, [and] if hemorrhoids or rectal fistulas are present […]':
    '〔四：〕白松香一铜〔杯〕，红球姜二铜〔杯〕〔……〕若有疼痛，〔且〕若见痔疮或肛瘘〔……〕',
'[All this land for five thousand] miles, the soil was fertile, [the irrigation] was good. Apple, […] and various fruit trees were plentiful [there, but the capital] was destroyed.':
    '〔方圆五千〕里〔的这片土地〕，土壤肥沃，〔灌溉〕良好。苹果、〔……〕与各种果树〔在那里〕繁茂，〔然而都城〕已毁。',
'[And further we,] while we were fasting, had not fasted according to the Manichaean teachings and doctrines, then […]':
    '〔又我们〕守斋之时，未依摩尼教的教法与规诫而斋，那么〔……〕',
'[And he asked:] "Ah, who are you people?"':
    '〔他便问道：〕「啊，你们是什么人？」',
'[And] if we, saying: "[He is a] prophet," should have cherised and believed in a false doctrine […]':
    '〔而〕倘若我们说「〔他是〕先知」，因而珍视并信奉了伪教〔……〕',
'[And] on top of that, other diseases remain.':
    '〔而〕除此之外，尚有别的疾病未去。',
'[Away] from [certain] destruction […]':
    '〔远离〕〔必然的〕毁灭〔……〕',
'[Forgive my] sins! Eleventh month, on the twenty-fifth day.':
    '〔赦我〕罪！十一月二十五日。',
'[God] deigned her to be born and to appear through the power of the Holy Spirit with the body of the pure Virgin, Saint Mary, and for her we toiled […]':
    '〔神〕垂允她藉圣灵之力，以圣洁童贞女圣马利亚之身诞生显现，我们为她劬劳〔……〕',
'[I] have sent five […] obedient slaves into exile.':
    '〔我〕已将五名〔……〕顺服的奴仆放逐。',
'[If we are] unable to observe the Yimki fast, prayer and commandments in accordance with religion and the doctrine […]':
    '〔倘若我们〕不能依教法与规诫守 Yimki 斋、行祈祷与遵诫命〔……〕',
'[Let us] submit gifts before the reverence of our mothers and fathers. [Let us] be free of [worldly] nuisances and attain tranquility, and reach Buddhahood at the end of our lives.':
    '〔愿我们〕于父母尊前奉献供品。〔愿我们〕远离〔世间〕烦扰而得寂静，并于此生终时成佛。',
'[Many people] spin spinning wheels, wool and hemp. They beat the soft fabrics and weave harsh woolen fabrics [from those], and other craftsmen carry out their own crafts.':
    '〔许多人〕转动纺车，纺羊毛与麻。他们捶打柔软的织物，〔以之〕织成粗硬的毛织品，其余匠人则各操其业。',
'[Now,] if my elder brother go overseas and retrieve the gemstone he will be more important [to them,] and I will become less important [to them.]':
    '〔如今，〕若我兄长渡海取回宝石，他在〔他们〕心中便更为重要，而我便不那么重要了。',
'[Page 131:] In accordance with their morning routine, they washed their hands and faces. After picking and gathering together [various] flowers, they went back into their shack.':
    '〔第 131 页：〕依其晨间惯例，他们洗了手脸。采集〔各样〕花朵之后，他们回到自己的草屋。',
'[The Buddha] gave food to eat [to the paupers] as much as [he could hold in his] palms, [and] he held water [for paupers to drink] as much as [he could hold in his] handful; he made peaceful and harmonious the quarrelling and fighting folk, […]':
    '〔佛〕以掌〔所能盛的〕分量给〔贫者〕食物，〔并〕以一捧〔所能盛的〕分量为贫者掬水；他使争斗相攻的人们和睦安宁〔……〕',
'[The Path of Deliverance] necessarily disobeys the lower sphere, so it is named deliverance in numerous other realms.':
    '〔解脱之道〕必然违逆下界，故于诸多他界中名为解脱。',
'[The horse] was sent to pray for a mute...':
    '〔那马〕被遣去为一哑者祈祷……',
'[The one who] observes the pure fasts, invoking [me], is the one who adheres to the head of the intercessors, the Metropolitan Episcopus.':
    '〔那〕守持净斋、称念〔我〕名者，即是依附于代祷者之首、都主教的人。',
"[They,] healing the physical injuries [visible on] the Bodhisattva's body and making it look just like before, curtsied before him with their heads bowed in a reverend [and] wakeful [manner], [following] the Five Constant Virtues.":
    '〔他们〕治愈菩萨身上〔可见的〕伤损，使之复如往昔，随后垂首、以恭敬〔而〕警觉的〔仪态〕于其前行礼，〔遵〕五常之德。',
'[This book] is to be known and understood, clearly and completely, like this.':
    '〔此书〕当如是明白而完整地知晓与理解。',
'[Your] sons and daughters, male servants and female servants, fathers and mothers, worldly possessions, plots of land, gold and silver, [they surely] are beneficial [to you.]':
    '〔你的〕儿女、僮仆婢女、父母、世间财产、田地、金银，〔这些必定〕对〔你〕有益。',
'[he] will tumble from on top of the birds (...)':
    '〔他〕将自群鸟之上跌落（……）',
'[…] Both inner [and outer] [stars] [coalesce] into the first astronomical mansion, on Sunday […]':
    '〔……〕内〔与外〕之〔星〕于星期日〔会聚〕于第一宿〔……〕',
'[…] If all and all kinds of pearls, turquoise, jade, [gold] and silver, possessions and goods, all of them appear like so. […]':
    '〔……〕若一切种种珍珠、绿松石、玉、〔金〕与银、财产货物，尽皆如是显现。〔……〕',
'[…] If you want to do what is good for me, then ask for and bring me a lute now.':
    '〔……〕你若想为我做件好事，就现在去讨一把琵琶来给我。',
'[…] In the span of an hour, they [helped] other Buddhist monk communities preach, and remained [with them.] […]':
    '〔……〕在一个时辰之内，他们〔协助〕其他僧团宣法，并〔与之〕同住。〔……〕',
'[…] Then, the prince entered the city and he reached towards the Eastern gate. […]':
    '〔……〕于是王子入城，向东门而去。〔……〕',
'[…] You became a mother to the motherless and a father to the fatherless, but now […]':
    '〔……〕你为无母者作母，为无父者作父，可如今〔……〕',
'[…] [and then if it is so,] their body will be freed from the six kinds of sins, they will be said to be recluses, and their appearance will be like so […]':
    '〔……〕〔若果如此，〕其身将脱离六种罪，他们将被称为隐修者，其形貌如是〔……〕',
'[…] [and] even some mortals, my God, [try to ...] you!':
    '〔……〕〔而〕甚至有些凡人，我的神啊，〔竟要……〕你！',
'[…] [on the] fourth [day] of the second month':
    '〔……〕二月初四〔日〕',
'[…] [take] the medication for three or five days […]':
    '〔……〕服药三日或五日〔……〕',
'[…] [they] kiss you three times, but [they] do not arrive at [your] words.':
    '〔……〕〔他们〕吻你三次，却未领会〔你的〕话语。',
'[…] [they] once [again] emerged [from it] with a strong[er] voice […]':
    '〔……〕〔他们〕又一次〔自其中〕以更〔强〕之声而出〔……〕',
'[…] adorned with heavenly flowers.':
    '〔……〕以天花庄严。',
'[…] among [numerous] brave arhants and students, I am his [most] exalted and praiseeworthy student.':
    '〔……〕在〔众多〕勇猛的阿罗汉与弟子之中，我是他〔最〕尊贵可赞的弟子。',
'[…] and if the deviant people were to become attached [to the material world.]':
    '〔……〕又若偏邪之人执着〔于物质世界〕。',
'[…] and if we somehow tormented countless living beings without knowing it, caused them pain and or separated [them] from their warm essences... [= taken their lives...]':
    '〔……〕又若我们不觉之中折磨了无量众生，使其受苦，或使〔其〕与温热的精气分离……〔＝夺其性命……〕',
'[…] and since no-one had made a sound, on the seventh day the iron chains were unbound and the iron cables were untied.':
    '〔……〕又因无人出声，第七日铁锁得解，铁索得开。',
'[…] and the virtue [stemming from these] five kinds of pearls and stones […]':
    '〔……〕以及〔源自这〕五种珠石的德用〔……〕',
"[…] and thus, in the end, comes the sorrowful suffering of parting from one's beloved.":
    '〔……〕如是，终究要来的是与所爱者别离的忧苦。',
'[…] and when someone ponders them deeply, and later, when a suitable opportunity arises, shares them with others; the progeny of the Buddhas are never cut off until the end of time, diminished or altered by so much as the breadth of a hair, nor destroyed or annihilated; such a person is called the treasury of the Buddhas.':
    '〔……〕又若有人深加思惟，日后遇合宜之机而与人分享；则诸佛之种直至劫尽亦不断绝，不减不改分毫，不坏不灭；如是之人被称为诸佛之藏。',
'[…] being pleased, whilst holding power and strength, being as winsome and beautiful as Yausep, the light and shine of [us] Christians, […]':
    '〔……〕欢悦而持权柄与力量，如约瑟一般俊美可爱——〔我们〕基督徒的光与辉〔……〕',
"[…] by the balustrade, towards the parrot's nest […]":
    '〔……〕在栏杆旁，朝着鹦鹉的巢〔……〕',
'[…] by the virtue of our great merits':
    '〔……〕凭我们大功德之力',
'[…] by virtue of this good deed of mine; to rescue and liberate all the people of the Earth from the sorrowful and bitter sufferings inherent in their untamed [= ignorant] modes of existence.':
    '〔……〕凭我此一善业之力，救拔并解脱世间一切人，令其出离未调伏〔＝无明〕诸趣中固有的忧苦。',
'[…] date trees, trees yielding mango fruit […]':
    '〔……〕枣树、结庵摩罗果之树〔……〕',
'[…] even if it only appears for a brief moment […]':
    '〔……〕纵使它只显现片刻〔……〕',
'[…] frogs, however […]':
    '〔……〕然而蛙类〔……〕',
'[…] has taken the price of [= bought] [the lives of others] by selling [his own] life away […]':
    '〔……〕以卖〔己〕命的代价换取〔＝买下〕〔他人之命〕〔……〕',
'[…] have eulogised and revered the very highest, truly perfect enlightenment; the Buddhahood.':
    '〔……〕赞叹并崇敬那无上真正圆满的觉悟，即佛果。',
'[…] if there are [symptoms of] diarrhea and pain in the chest; […]':
    '〔……〕若有腹泻与胸痛〔之症〕；〔……〕',
'[…] if we should have inflicted on them the fourteen-fold wounds, if we somehow with the ten serpent-headed fingers [and] the thirty-two teeth should have tortured and pained the Living Self, the God, the divine of food and drink […]':
    '〔……〕倘若我们于其身加以十四种伤，倘若我们竟以十根蛇首般的手指〔与〕三十二颗牙齿，折磨并伤害了活的自我、神明、饮食之神〔……〕',
'[…] in this kingdom [of God], to the prince […] [even] your mother, [and] [our] father Jesus, even in this kingdom they were killed.':
    '〔……〕在〔神的〕这国度中，对那王子〔……〕〔连〕你的母亲，〔以及〕〔我们的〕父耶稣，就在这国度里也被杀了。',
'[…] is said so. This fruit of labor is called […] , and for the sake of […] , your [wisdom-]eye […]':
    '〔……〕如是说。此劳作之果名为〔……〕，又为〔……〕之故，你的〔慧〕眼〔……〕',
'[…] it was the [day of the] small fast.':
    '〔……〕那是小斋〔之日〕。',
'[…] our hearts, being vast open, like as if one steps in a lake […]':
    '〔……〕我们的心开阔无边，恰如人踏入湖中〔……〕',
'[…] praising in the Heavens, firm [yet] delicate […]':
    '〔……〕于诸天中赞颂，坚固〔而又〕细致〔……〕',
'[…] that [community of hundred thousand people] gave their benedictions as a whole and they [said] to the merchants: […]':
    '〔……〕那〔十万人的会众〕齐声祝祷，并对商人们〔说〕：〔……〕',
'[…] the beginning […] song […]':
    '〔……〕起首〔……〕之歌〔……〕',
'[…] the feather duster and the hand fan […]':
    '〔……〕拂尘与手扇〔……〕',
'[…] the meaning behind your words […]\n(literally, “ […] in your letters”)':
    '〔……〕你话语背后的含义〔……〕\n（字面义：「〔……〕在你的书信中」）',
'[…] the six teachers of the Buddhist faith […]':
    '〔……〕佛教的六师〔……〕',
'[…] then, spreading his wings and soaring through the sky; he clawed [at the Dragon,] seizing him, held him fast, and carried him away.':
    '〔……〕于是他展翅翱翔于天，探爪〔攫向那龙〕，将其擒住紧握，掳之而去。',
'[…] to come in the time of need, raining over, branching out above, blossoming and becoming perfect of a flower in seven kinds of […]':
    '〔……〕于急需之时而来，普降如雨，于上分枝，开花而成就七种〔……〕之花',
'[…] with a deeply reverend and meditative stance, not scattering [= wasting] our mindfulness, […]':
    '〔……〕以深切恭敬而入定的姿态，不散〔＝不虚耗〕我们的正念，〔……〕',
'[…] with butter and milk of a cow, [coupled with] honey and molasses.':
    '〔……〕以牛的酥油与乳，〔并佐以〕蜜与糖蜜。',
'[…] with the power of […] , the choler accumulates [in the body] from the radiant beams of the setting sun.':
    '〔……〕以〔……〕之力，黄胆因落日的光芒而〔在体内〕积聚。',
'[…] worthy of a thousand praises and ten thousand blessings […]':
    '〔……〕堪受千赞万福〔……〕',
'[…] your name, which is fit for a madame […]':
    '〔……〕你那配得上贵妇的名字〔……〕',
'a controlled regimen on the consumption of foodstuff, self-inflicted curfew on the act of eating':
    '节制饮食的规程，自我设定的禁食时限',
'a copper coin, copper currency':
    '铜钱、铜币',
'a deciduous shrub, most likely either white spiraea or purple willow':
    '一种落叶灌木，很可能是白绣线菊或紫柳',
'a female given name':
    '女子名',
'a kind of headgear worn by Mongol women':
    '蒙古妇女所戴的一种头饰',
'a kind of headwear for Mongol noblewomen':
    '蒙古贵族妇女所戴的一种头饰（罟罟冠）',
'a male given name':
    '男子名',
'a male given name, and very rarely, a female given name':
    '男子名，极少数情况下亦作女子名',
'a perfect and/or an appropriate thing':
    '圆满与／或恰当之物',
'a relative by marriage':
    '姻亲',
'a share of inherited property and goods':
    '所继承的财产与物品中的一份',
'a teacher in religious affairs':
    '教中之师',
'a type of plucked string instrument similar to a lute, komuz, cobza':
    '一种弹拨弦乐器，近于琉特琴、库姆兹琴、科布扎琴',
'a unisex given name':
    '男女通用的名字',
'a unit of measurement equal to the width of a hand':
    '一种长度单位，等于一掌之宽',
}
