#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part C — 祝祷、经文与福音书标题.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_c.py; edit that.
"""
G = {
'Let me write down in this book the words that begin with the [syllable] A-, those that come first in line, like this. The following is connected neatly, from beginning to end, so that none gets bogged down [in reading.]':
    '让我在此书中如是记下以〔音节〕A- 起首的词，即排在最前的那些。以下自始至终工整相连，使人〔读时〕不致滞碍。',
'Let the lame walk, let all the mutes speak!':
    '愿跛者能行，愿一切喑者能言！',
'Let us achieve the excellent and great enlightenment.':
    '愿我们成就殊胜广大的觉悟。',
'Let us read [these pages] clearly, and in detail!':
    '让我们把〔这些书页〕读得明白而详尽！',
'Like the moon rising from beneath the clouds.':
    '犹如月自云下升起。',
'Lions and tigers lay down on their sides […]':
    '狮与虎侧卧〔……〕',
'Mani (the founder of Manichaeism)':
    '摩尼（摩尼教创立者）',
'Manichaean electus':
    '摩尼教选民（electus）',
'Mary (Biblical figure)':
    '马利亚（圣经人物）',
'May [the] women [of this village] keep on stitching the mouths of [torn] sacks!':
    '愿〔此村的〕妇人们继续缝合〔破〕袋之口！',
'May all hunger, poverty, disease, infirmity, enemies [of people] and evil-doers in the state and the kingdom be neutralized and gone; may all kinds of crops and grain flourish and ripen to full fruition[;] may the wind and rain come true measurely and in time; may the whole state and the kingdom become relaxed and joyful.':
    '愿国中与王土内一切饥馑、贫穷、疾病、衰弱、〔民之〕仇敌与作恶者尽皆消弭；愿百谷丰茂，成熟圆满；愿风雨应时而适度；愿举国与王土安舒欢悦。',
'May his heavenly favour and blessings come at the right time and rest upon those living beings who, like Father Abraham, have become partakers of the blessing, and upon those who, like Father Jacob, the friend of the whole congregation, have attained perfection...':
    '愿其天恩与祝福应时而降，临于那些如亚伯拉罕父一般得与祝福有分的众生，以及那些如全会众之友雅各父一般臻于完全的人……',
'May the God of Light, the prophet Mani, be exalted.':
    '愿光明之神、先知摩尼被尊崇。',
'May the Uyghur seal be!':
    '愿回鹘之印长存！',
'May the concubine/prostitute who was left [alone] among the reeds, with whom the Heaven was not pleased, be a queen.':
    '愿那被〔独〕弃于芦苇之间、不为天所悦的姬妾／妓女成为王后。',
'May they attain the divine favour of the Buddha! My teachers, my lords, my brothers and sisters in faith of the five modes of existence, […]':
    '愿他们得佛之天恩！我的师长、我的主上、五趣中我的信仰弟兄姊妹们〔……〕',
'Men are sorrowful, the sky is overcast.':
    '人心忧伤，天色阴晦。',
'Moreover, let this meritorious good deed be a gift, let it be a gift for every single person for seven generations [from now on]. In this body […]':
    '复次，愿此功德善业成为布施，愿它成为〔自今〕七代之内每一个人的布施。于此身中〔……〕',
'Moreover, the fruits and shades of apple and other various trees would make any place lovely, and the songs of the newly arrived birds suit the life without the anxiety of death well.':
    '复次，苹果及种种树木的果实与荫凉使何处都变得可爱，而新来禽鸟的鸣唱，与无死亡之忧的生活正相宜。',
'Multi-colored fabric.':
    '杂色的织物。',
'My lord, my prince regent who is holy, my princess regent who is holy, for your heavenly favor!':
    '我的主上、我圣洁的摄政王子、我圣洁的摄政王女，为你们的天恩！',
'My sons-in-law, relatives and brother[s!]':
    '我的女婿、亲族与兄弟们！',
'My teachers, who have learned the unsurpassabl[y noble] teachings.':
    '我的师长们，他们习得了无上〔尊贵的〕教法。',
'Ninth [remedy]: For one who blanches at a [certain] time, and is unable to eat or digest food; blending […] and drinking [the blend] will dispel the blanching and prevent the appearance of [new] wounds.':
    '第九〔方〕：若人于〔某〕时面色发白，且不能进食或消化；调和〔……〕而饮〔此剂〕，可去其白，并防〔新〕疮生起。',
'Noble Maitreya! Just like how a guest returns to their own home after the autumnal reconnaissance trip, so have you wished it [to be true.]':
    '圣弥勒！正如客人于秋日巡行之后返归自家，你也如此愿其〔成真〕。',
'Now all you masters and teachers are [invited] to list all the good deeds you have accumulated thus far, [and] interpret [= divine] this dream distinctly [= in detail] so that everyone can hear it.':
    '如今请诸位大德法师历数你们迄今所积的一切善业，〔并〕将此梦分明地〔＝详尽地〕解说〔＝占断〕，使众人皆得听闻。',
'Now just like that, I drained the colour [from the faces of people,] laid in the wombs of every [mother], suckled on the milk of every [mother], and like that, I drank the blood of those very living beings.':
    '如今正是这样，我抽干了〔人们脸上的〕血色，卧于每一位〔母亲〕的胎中，吮吸每一位〔母亲〕的乳汁，就这样，我饮了那些众生的血。',
'O my son! [This] is [your] way. Now hear ye, the word of God! […]':
    '我儿啊！〔这〕就是〔你的〕道路。如今你们且听神的话语！〔……〕',
'Of the ones who interpret the commentary and explanation texts without deviating from the perfect and the appropriate [language...]':
    '那些解说论疏与释文而不违圆满恰当〔之语〕的人〔……〕',
'Oh, the evil creature! Why do you furrow your brows and sit down with a morose face?':
    '唉，你这恶物！为何蹙眉、面带愠色地坐着？',
'On [this] blessed day [of this] blessed month, may this wonderful start of the year begin and the auspicious tomorrows dawn...':
    '于〔此〕吉月〔此〕吉日，愿这美好的岁首开启，愿吉祥的明日破晓……',
'One of four modes of birth in Mahāyāna and Tibetan Buddhism':
    '大乘与藏传佛教四生之一',
'One should have a talisman inscribed and have it fastened between the thigh [region] of the undergarments of a woman; [then] in the eighth day [= after eight days] take the talisman back, apply fire on it and secure the [remaining] ashes […]':
    '当令人书符，系于妇人内衣的股〔间〕；〔然后〕于第八日〔＝八日之后〕取回此符，以火焚之，收其〔余〕灰〔……〕',
'One spiraea became a hundred, a hundred spiraeas became a thousand, and a thousand spiraeas became ten thousand.':
    '一株绣线菊变为百株，百株变为千株，千株又变为万株。',
'One who draws a poison-arrow, Śalyāhṛt (an epithet of the Buddha)':
    '拔毒箭者，Śalyāhṛt（佛之别号）',
'Opening his mouth, the sound of the laughter, ha-ha, [comes out; and his voice] echoes through. That is the sound of Vajra, equivalent to six [meditative] syllables.':
    '他一张口，哈哈的笑声〔便发出来；其声〕回荡不绝。那便是金刚之音，相当于六〔观想〕字。',
'Pratyekabuddhayāna priest':
    '缘觉乘的僧人',
'Relatives [and] in-laws visiting each other; feasting, drinking [and] indulging in pleasures […]':
    '亲族〔与〕姻亲互相往还；宴饮〔并〕纵情逸乐〔……〕',
'Reproductive cores of men (sperm) and women (menstrual blood).':
    '男女的生殖之精（精液与经血）。',
'River that ebbs and flows.':
    '有涨落的河。',
'Roots of vetiver grass.':
    '岩兰草根。',
'Saddharmapuṇḍarīkasūtra, Lotus Sutra':
    '《妙法莲华经》',
'Scorching and shoaly soil.':
    '灼热而浅瘠的土地。',
'Siting down on a beautiful rock, I look around.':
    '我坐在一块美石上环顾四周。',
'Small rivers with the scent of sandalwood and lotuses':
    '带着檀香与莲花气息的小河',
'Small slices of raw meat.':
    '生肉的细片。',
'So then, my Lord, we pray now to be liberated from sin. Man astar hirza!':
    '那么，我的主，我们如今祈求脱离罪。Man astar hirza！（愿赦我罪！）',
'Someone fettered a roan [horse] crosswise.':
    '有人将一匹沙毛〔马〕横向绊住。',
'Suleiman Khan of the Ilkhanates':
    '伊利汗国的苏莱曼汗',
'Take a [pauper] to your house, holding their hand. Whoever brings a pauper into their house, a bowl [of food] […]':
    '牵起〔贫者〕的手，带他到你家中。凡将贫者领进家门的人，一碗〔饭食〕〔……〕',
'Taking pity on all the living beings descended from Adam […]':
    '怜悯一切自亚当而出的众生〔……〕',
'That famished tigress again gave birth to a cub, and wandered for seven days straight.':
    '那只饥饿的母虎又产下一崽，连续游荡了七天。',
'The Buddha; in his desire for the feliticious, without resting for even a moment nor getting tired, cleansed the impure hearts - that is his duty.':
    '佛因求安乐之故，片刻不歇亦不疲倦，涤净不净之心——那便是他的职分。',
'The Gods above and the people below, they all wail and lament […]':
    '上界诸神与下界世人，无不哀号悲泣〔……〕',
'The Saint [Paul] went on to the city of the heretics, called Anzio, [and] when he said "I will teach the doctrine of the prophets […]':
    '圣〔保罗〕前往那座名为安齐奥的异端之城，〔并〕当他说「我要宣讲先知的教义〔……〕',
'The bear, the monkey, [and] the lion […]':
    '熊、猴〔与〕狮〔……〕',
'The beauty of the four continents of the world, The ferocity of the deep sea and rivers, The canopies of the mountains from the four corners of the earth, The high edge of the Earth below.':
    '世间四大部洲之美，深海大川之猛，大地四隅群山之华盖，下方大地之高缘。',
"The capability of [one's own] body […]":
    '〔自〕身之能力〔……〕',
'The desperate Mandari licks as it flows, the blood of the Prince, her beloved Lord. She laments thus, wailing [the following: ...]':
    '绝望的曼达丽舐着那流淌的血——她所爱之主、王子的血。她如此悲叹，哀号〔如下：……〕',
'The discerning and aware [level of] consciousness (eqv. Sanskrit मनस् (manas))':
    '能分别、能觉知的〔那一层〕识（对应梵语 मनस्，manas，即「意」）',
'The enemy with hateful thoughts...':
    '怀憎恨之念的仇敌……',
'The fire that cooks the food.':
    '煮食之火。',
'The flow [= stream] of the religious doctrine flowed eastwards, into the Chinese Empire...':
    '教法之流〔＝法流〕东注，入于中华之国……',
'The flying birds of the blue sky could fly no longer.':
    '青天中的飞鸟再也飞不动了。',
'The fortunes and belongings of this sort...':
    '此类的财运与产业……',
'The holy gospel of our lord, Jesus Christ, Messiah, according to John.':
    '我主耶稣基督、弥赛亚的圣福音，据约翰所记。',
'The merchant gave [her] a hundred gold coins, stamped [her documents] and sent that girl [abroad] with his hands and arms [= wholly.]':
    '商人给了〔她〕一百枚金币，在〔她的文书上〕盖印，亲手〔＝全然地〕将那女子送〔往异邦〕。',
'The moon is also a virile celestial body, the second man have said so. […]':
    '月亦是雄性的天体，第二人如是说。〔……〕',
"The old man's exhaustion was upon him […]":
    '老人的困乏袭上身来〔……〕',
'The reason that I am tormented by illness...':
    '我为疾病所苦的缘由……',
'The reverend and great gods, themselves bright [even] without [the aide of] the Moon and the Sun, cusping their hands...':
    '尊贵伟大的诸神，纵无日月〔之助〕自身亦放光明，合拢双手……',
'The road lies open before you in four corners [= every direction;] whatever joy you seek, you will find it perfectly [= to your liking.]':
    '道路向四方〔＝各个方向〕为你敞开；你所求何乐，必能圆满〔＝如意〕得之。',
'The skin of her chest is like the feel of a ten thousand snakes [writhing.] Her index finger is like a needle-snake […]':
    '她胸前的皮肤触之如万蛇〔蠕动〕。她的食指如一条针蛇〔……〕',
'The spring cold is very harsh.':
    '春寒甚烈。',
'The swan put him on its wings, and so it rose in the air and brought him to his parents.':
    '天鹅把他放在翅上，于是腾空而起，将他送到父母身边。',
"The truth [is in] barring the paths [leading up to] the vile things, [while] striving to open up the paths [leading up to] the good things, [and] to realize [one's own] perfection in merit.":
    '真谛〔在于〕堵塞〔通往〕恶事之路，〔同时〕力求开启〔通往〕善事之路，〔并〕成就〔自身〕功德的圆满。',
'The waters came from the heights, they gush out without [ever] drying up; they pour out without ever returning [= ebbing,] [and so] the creeks froze over.':
    '水自高处而来，涌流不竭；奔泻而不复返〔＝不退〕，〔于是〕溪流结冰。',
'The yak bull churned up the ground with its pointed horns and crushed the earth with its hooves, scattering it.':
    '公牦牛以尖角掀翻地面，以蹄碾碎泥土，扬撒四散。',
'The year of the horse':
    '马年',
'The year of the rooster':
    '鸡年',
'Then, she spoke to herself as follows: "I was reborn in [this] extremely bad reincarnation of a vixen, and my own physical strength is not adequate."':
    '于是她自言道：「我转生为牝狐这般极恶的轮回之身，而自己的体力也不足。」',
'Then; the Buddha, God of gods, spoke to the Brahmin as follows: O Brahmin! There is nothing better than alms-giving. […]':
    '于是，天中天佛对婆罗门说道：婆罗门啊！没有什么比布施更好。〔……〕',
'There were two novice monks under the service of Upananda.':
    '有两名沙弥侍奉邬波难陀。',
'Thereupon his father, the Khan, got suspicious of [the wellbeing of] his despised and misbehaving [= bad-mannered] son and said: "If my beloved son is killed, let me never see [that man\'s] face ever again!"':
    '于是其父可汗对那被厌弃、行止无状的儿子〔的安危〕起了疑心，说道：「倘若我爱子被杀，我此生再不愿见〔那人的〕面！」',
'Thereupon was a skillful and brave guide from the city of Benares.':
    '于是有一位来自波罗奈城、精干而勇敢的向导。',
'Thereupon, completely surrounded by boys [= students,] treading slowly...':
    '于是，被童子〔＝弟子〕们团团围绕，缓步而行……',
'Thereupon, the Heavenly ruler entered [= honoured] the celebratory feast and took the crown upon his head, donned his vermilion [robe, and] took his seat on his gold-trimmed throne.':
    '于是天王莅临〔＝光临〕庆宴，戴冠于首，披上朱色〔袍服，并〕升其饰金之座。',
'They believed the preachings of the true doctrine by the one with a mouth made of gold, and they held onto them firmly.':
    '他们信受那金口者所宣讲的正法，并牢牢执持。',
'They came without respite.':
    '他们接踵而至，不曾稍歇。',
'They cleansed [from] their grievous sins and misdeeds.':
    '他们涤除了自身深重的罪与恶业。',
'They enter into five [different] modes of existence, [yet] they are not attached, [nor] do they cling to them.':
    '他们入于五〔种〕趣，〔然而〕不着，〔亦〕不执取。',
'They fettered his hands and feet and incarcerated him.':
    '他们缚其手足，将他囚禁。',
'They reached the Tavġač realm, that is favored by heavens.':
    '他们抵达了受天眷顾的桃花石之国。',
'They ruin their bodies, [for] they love [= feel worldly attachment to] their beloved horses and stallions.':
    '他们毁坏自身，〔因为〕他们爱恋〔＝世俗执着于〕心爱的马与骏马。',
'They sought an opportunity.':
    '他们寻觅时机。',
'They stitch up dresses, o!':
    '她们缝制衣裳，哦！',
'They wore the wet clothing.':
    '他们穿着湿透的衣服。',
'Thinking of your divine bliss and good-natured merits in the holy mountains of the seven jewels of teachings, whole, incomprehensible, belonging to the good-natured merits that come in pairs.':
    '在教法七宝的圣山之中，思念你那神圣的安乐与善性的功德——完整、不可思议，属于成双而来的善性功德。',
'Thirdly: How do they not feel contempt for and endure the difficult, toilsome [and] painful paths, [thus] attaining the virtue of exertion?':
    '其三：他们如何不轻慢、且能堪忍艰难劳苦〔与〕痛楚之道，〔从而〕成就精进之德？',
'Those gold merchants […]':
    '那些金商〔……〕',
'Thus, this is a Pratyayadharma. It brings the religious doctrines to the fore and renders it visible [to the common folk, and] this is the nature of their mutual excellence.':
    '如是，此即缘法。它把教法推至前台，使之〔为常人〕可见，〔而〕这便是二者相互殊胜之性。',
'To compose an essay.':
    '作文。',
"To house anger, spite and hate in one's heart. (Ninth Kammapatha)":
    '心怀忿、恨与憎。（第九业道）',
'Trusting the sovereigns, understanding the objects of meditation.':
    '信任君王，了知所观之境。',
'Turkish, Old Uyghur':
    '突厥语、回鹘语',
'Twenty fifthly: A taste [= nectar] flows from his canine teeth, more exquisite and divine than other tastes [= nectars.]':
    '其二十五：自其犬齿流出一味〔＝甘露〕，较其他诸味〔＝甘露〕更精妙而神圣。',
'Twenty third: He has immaculate and uniquely white(Hend.) canine teeth.':
    '其二十三：他的犬齿洁净无瑕、独然洁白（重言）。',
'Two bars, used to separate long phrases, used interchangeably with \U00010f89':
    '双竖线，用以分隔长语段，与 \U00010f89 通用',
'Two dots, used to separate short phrases, used interchangeably with \U00010f86':
    '双点，用以分隔短语，与 \U00010f86 通用',
'Understanding the subtleties of the interpretation of the teachings is extremely difficult.':
    '通晓教法解释之微妙极为艰难。',
'Until their demise, [the human beings and Gods will] not differ from each other, if they hold [and preach] this religious doctrine […]':
    '直至命终，若持〔并宣〕此教法，〔人与神〕彼此便无差别〔……〕',
}
