#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part A (the short list)."""
G = {
"褐子":"褐子","ant":"蚁","big":"大","eye":"眼","god":"神","ice":"冰","id.":"同上",
"ink":"墨","man":"人、男子","red":"红","six":"六","ten":"十","wet":"湿","Mary":"马利亚",
"bear":"熊","body":"身体","cart":"车","damp":"潮湿","fire":"火","five":"五","flax":"亚麻",
"four":"四","girl":"女孩","hand":"手","hate":"憎恨","high":"高","holy":"神圣的",
"hoof":"蹄","hour":"时辰","king":"王","lady":"夫人","lake":"湖","leaf":"叶","meat":"肉",
"name":"名","nest":"巢","nine":"九","palm":"手掌","rock":"岩","root":"根","seam":"缝",
"self":"自己","ship":"船","sign":"记号","soul":"灵魂","star":"星","swan":"天鹅",
"trap":"陷阱","vein":"脉","west":"西","wind":"风","wine":"酒","arrow":"箭","black":"黑",
"blood":"血","brain":"脑","brown":"褐","chain":"链","cloth":"布","crane":"鹤","eight":"八",
"flame":"火焰","green":"绿","heart":"心","honey":"蜜","horse":"马","house":"房屋",
"light":"光","music":"音乐","paste":"糊","power":"力量","pulse":"脉搏","queen":"王后",
"realm":"疆域","seven":"七","south":"南","spoke":"辐条","stone":"石","three":"三",
"tribe":"部落","water":"水","wheel":"轮","white":"白","Buddha":"佛","Christ":"基督",
"Friday":"星期五","friday":"星期五","Uyghur":"回鹘","autumn":"秋","byssus":"细麻布",
"chakra":"轮（脉轮）","copper":"铜","desert":"沙漠","embers":"余烬","family":"家族",
"hoopoe":"戴胜","magpie":"喜鹊","melody":"曲调","memory":"记忆","needle":"针",
"one, 1":"一","planet":"行星","prince":"王子","spirit":"精神","stream":"溪流",
"to fan":"扇","two, 2":"二","yellow":"黄","yogurt":"酸奶","'Swan.'":"天鹅。",
"ability":"能力","concept":"概念","correct":"正确的","essence":"本质","five, 5":"五",
"foreign":"外来的","four, 4":"四","garment":"衣","harmony":"和谐","nine, 9":"九",
"old man":"老者","prophet":"先知","sibling":"兄弟姐妹","ten, 10":"十","to blow":"吹",
"to come":"来","to heed":"留意","to know":"知","to move":"动","to ride":"骑",
"to send":"遣","to sour":"变酸","to spin":"纺","to tack":"缝缀","to turn":"转",
"to walk":"行走","to yawn":"打呵欠","deserted":"荒废的","eight, 8":"八","fountain":"泉",
"hand fan":"手扇","religion":"宗教","seven, 7":"七","skillful":"精巧的","sun, day":"日",
"sunshine":"阳光","tent rib":"帐骨","thousand":"千","three, 3":"三","to drink":"饮",
"to shine":"照耀","to spoil":"败坏","a toponym":"地名","handiwork":"手工",
"hen, fowl":"母鸡、家禽","old woman":"老妇","one alone":"独一","road, way":"道路",
"sky, grue":"天、青","the Earth":"大地","to stitch":"缝","turquoise":"绿松石",
"you, thee":"你","Hui people":"回人","Me myself.":"我自己。","Syllable I":"音节 I",
"big, large":"大","blue-eyed.":"蓝眼的。","brown, red":"褐红","color, dye":"色、染料",
"earthquake":"地震","luck, fate":"运数","mute, deaf":"喑聋","sandalwood":"檀香",
"ship, boat":"船","sign, mark":"记号","soil, land":"土地","to squeeze":"挤压",
"twenty, 20":"二十","water well":"水井","word, noun":"词、名词","Buddha-King":"佛王",
"Russet hare":"赤兔","blue, green":"青、绿","bush, shrub":"灌木","custom, law":"习俗、法",
"front, east":"前方、东","honey, mead":"蜜、蜜酒","king, ruler":"王、统治者",
"oscillation":"摆动","queen, lady":"王后、夫人","rank, title":"位号","rust, grime":"锈垢",
"sky, heaven":"天","snare, trap":"罗网","soul, heart":"魂、心","tree branch":"树枝",
"wagon, cart":"车","Miriam, Mary":"米利暗、马利亚","[…] Pitying.":"……怜悯。",
"behind, back":"后方","bodily fluid":"体液","color, shape":"色、形","fall, autumn":"秋",
"female camel":"牝驼","female deity":"女神","flaxen cloth":"麻布","grayish blue":"灰蓝",
"prince, heir":"王子、嗣君","seed, kernel":"种子、核","sky, heavens":"天","sour, bitter":"酸苦",
"to look back":"回顾","vein, artery":"血脉","weave, braid":"编织","calm, relaxed":"安舒",
"clear, bright":"清亮","colour, paint":"颜色、颜料","domestic fowl":"家禽",
"dravya, vastu":"实体（dravya, vastu）","exterior, out":"外部","fowl, chicken":"鸡",
"glowing coals":"炭火","lamp, lantern":"灯","music, melody":"乐曲","name, epithet":"名号",
"page, leaflet":"页、单张","poison, venom":"毒","reddish brown":"赤褐","relative, kin":"亲属",
"rock, boulder":"岩石","self, oneself":"自己","spite, hatred":"憎恨","to understand":"理解",
"village, city":"村邑","-less, lacking":"无……的","Aureola, halo.":"背光、光轮。",
"a rhyming song":"押韵之歌","blackish brown":"黑褐","brown, piebald":"褐花","deaf, deafness":"聋",
"fat, oil, lard":"脂油","finger's width":"指宽","full, complete":"圆满","heavenly favor":"天佑",
"lucky, favored":"有福的","material world":"物质世界","object, device":"器物",
"piebald, brown":"花褐","red, vermilion":"朱红","revenge, anger":"复仇、忿怒",
"stallion, stud":"种马","stomach, belly":"腹","tent rib, pole":"帐骨、杆",
"to freeze over":"结冰","to move, shake":"摇动","to take a step":"迈步","younger sister":"妹",
"colour, stature":"色泽、身量","cotton clothing":"棉衣","cream, ointment":"膏",
"decree, yarligh":"敕令（yarligh）","deverbal suffix":"动词派生后缀","dog-meat vendor":"卖狗肉者",
"goods, property":"财物","handsome person":"美貌之人","mare, she-horse":"牝马",
"mountain stream":"山溪","poor, miserable":"贫苦","power, strength":"力量",
"road, way, path":"道路","shiny, luminous":"光亮的","spiraea; jujube":"绣线菊；枣",
"the Moon, month":"月","wind, gust, air":"风、气","Hateful thoughts":"憎恨之念",
"courage, bravery":"勇气","dust, dirt, soot":"尘垢","genuine, quality":"纯正的",
"heavenly, divine":"天上的、神圣的","male ruler, khan":"可汗","mastered, expert":"精通的",
"mutuality suffix":"互动后缀","other, remaining":"其余的","purple, dark red":"紫、暗红",
"to take, to hold":"取、执",
# --- 音节表（回鹘文音节字母名） ---
"Syllable Aa":"音节 Aa","Syllable Ke":"音节 Ke","Syllable Le":"音节 Le",
"Syllable Me":"音节 Me","Syllable Ne":"音节 Ne","Syllable Pe":"音节 Pe",
"Syllable Re":"音节 Re","Syllable Sa":"音节 Sa","Syllable Ta":"音节 Ta",
"Syllable Ve":"音节 Ve","Syllable Za":"音节 Za","Syllable Še":"音节 Še",
"Syllable Ḥa":"音节 Ḥa","Syllable Ḳa":"音节 Ḳa",
}
