#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part F — 词条释义 g–r.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_f.py; edit that.
"""
G = {
'good, excellent, auspicious':
    '好的、优良的、吉祥的',
'good, excellent, auspicious; superior, appealing':
    '好的、优良的、吉祥的；上等的、动人的',
'goods, riches, stuff':
    '货物、财物、东西',
'goods, wares, riches, valuables':
    '货物、商品、财富、贵重物品',
'gray, brownish gray':
    '灰的、褐灰的',
'guru, siddha; religious teacher and instructor':
    '上师、成就者；宗教之师与教授者',
'guru, spiritual teacher':
    '上师、精神导师',
'halo, aureola, nimbus':
    '背光、光轮、头光',
'hand (of a clock, more specifically, of a water clock or a sundial)':
    '（钟表的）指针，尤指漏刻或日晷之针',
'handful, a handful of sth.':
    '一捧、一把（某物）',
'handworker, master, expert':
    '手工匠人、能手、行家',
'hard, difficult; brazen, brave':
    '难的、艰苦的；胆大的、勇敢的',
'hatred, disgust, grudge':
    '憎恨、厌恶、宿怨',
'hatred, revenge, enmity, anger, thirst for revenge':
    '憎恨、复仇、仇怨、忿怒、复仇之心',
'healthy, beautiful':
    '健康的、美好的',
'healthy, safe and sound':
    '健康的、安然无恙的',
'heavy, weighty; severe (literal and figurative senses)':
    '重的、沉的；严重的（本义与引申义）',
'heavy, weighty; severe (literal and figurative senses); difficult, troubling; grievous, painful (negative figurative senses)':
    '重的、沉的；严重的（本义与引申义）；艰难的、令人困扰的；深重的、痛苦的（负面引申义）',
'heavy, weighty; severe (literal and figurative senses); reverend, laudatory, important; valuable, precious (positive figurative senses)':
    '重的、沉的；严重的（本义与引申义）；尊贵的、可赞的、重要的；宝贵的、珍贵的（正面引申义）',
'heterodoxical, apocryphal':
    '异端的、伪经的',
'heth, sixth letter of the Uyghur script':
    '赫特，回鹘文第六字母',
'hey!, ah! exclamation used to summon someone or to get attention':
    '喂！啊！用以呼唤他人或引起注意的感叹词',
'his trough and pail for catching fish':
    '他捕鱼用的槽与桶',
'holy, consecrated':
    '神圣的、被祝圣的',
'holy, godlike, charismatic':
    '神圣的、如神的、有神恩的',
'honorific title for minor deities':
    '小神的尊号',
'hoof, nail (of horses, cattle, deer, etc.)':
    '蹄、爪（马、牛、鹿等的）',
'house, dwelling-place':
    '房屋、居所',
'hunger, desperation, destituteness':
    '饥饿、绝望、赤贫',
'hungry, famished; gluttonous, greedy':
    '饥饿的；贪食的、贪婪的',
'husband, male partner':
    '丈夫、男伴',
'hut, shack; lodging made of branches and scrap material':
    '茅屋、草棚；以枝条与杂料搭成的居所',
'ice, frozen water':
    '冰',
'idol, specifically pagan idols; heathen prophets':
    '偶像，尤指异教偶像；异教先知',
'illuminated, bright':
    '被照亮的、明亮的',
'joint; pivot, enarthrosis':
    '关节；枢轴、杵臼关节',
'kaph, eighth letter of the Uyghur script':
    '卡夫，回鹘文第八字母',
'king, ruler, a Terken of the Uyghur Khaganate':
    '王、统治者；回鹘汗国的 Terken 尊号',
'knowledge, cognition, reason':
    '知识、认知、理性',
'lamedh, ninth letter of the Uyghur script':
    '拉梅德，回鹘文第九字母',
'lapis lazuli, lazurite':
    '青金石',
'law, rule, doctrine':
    '法、律、教义',
'lesh, eighteenth letter of the Uyghur script':
    '莱什，回鹘文第十八字母',
'light (not heavy), brisk':
    '轻的（不重）、轻快的',
'light gray, grayish blue (of eyes)':
    '浅灰的、灰蓝的（指眼睛）',
'liver; flank, side':
    '肝；胁、侧',
'lotus, water lily (Nelumbo nucifera)':
    '莲、荷（Nelumbo nucifera）',
'loved, caressed, deeply cared for':
    '被爱的、被抚爱的、深受珍视的',
'loved, lusted after':
    '被爱的、被贪恋的',
'lucky, favored; happy, bestowed':
    '有福的、蒙眷顾的；欢喜的、受赐的',
'maiden, slavegirl':
    '侍女、婢女',
'man, adult male human':
    '男子、成年男性',
'mango, mango tree':
    '庵摩罗（芒果）、芒果树',
'mark of auspiciousness, Lakshana':
    '吉相（Lakṣaṇa）',
'mark, sign (on property)':
    '记号、标记（用于财物）',
'master, craftsman':
    '匠师、工匠',
'masterfully, expertly':
    '精熟地、内行地',
'material, substance':
    '材料、物质',
'meat, flesh (both of human and of game)':
    '肉（人肉与猎物之肉皆可）',
'melody, tone, tune':
    '曲调、音调',
'mem, tenth letter of the Uyghur script':
    '梅姆，回鹘文第十字母',
'memory; appearance, physical quality':
    '记忆；外貌、体质',
'menstrual discharge, period blood':
    '月经、经血',
'mindless, dumb, unconscious':
    '无心的、痴呆的、无意识的',
'minister, confidant, amātya, śreṣṭhi':
    '大臣、近臣（amātya、śreṣṭhi）',
'miserliness, being short on money, skimpiness, stinginess':
    '吝啬、拮据、悭吝',
'miss, lady, mistress, dame':
    '小姐、夫人、女主人',
'misspelling of \U00010f70\U00010f76\U00010f77\U00010f76 (ʾyky)':
    '\U00010f70\U00010f76\U00010f77\U00010f76（ʾyky）的误拼',
'mitzvah, good deed, virtue':
    '善行、功德',
'month, a complete revolution of the Moon spanning either twenty-nine or thirty days':
    '月，月亮一个完整的运行周期，为二十九或三十日',
'mother-of-pearl, nacre':
    '螺钿、珍珠层',
'motherless, orphan':
    '无母的、孤儿',
'mouth, a mouthful; (by extension) a opening (of a wound, a hole, or an estuary, etc.)':
    '口、一口；引申为开口（伤口、洞口、河口等）',
'mute, dumb (p. unable to speak)':
    '喑哑的（不能言者）',
'nervation, trace, streak':
    '脉络、痕迹、条纹',
'nest, lair, shelter, den':
    '巢、穴、藏身处',
'night, nighttime, evening':
    '夜、夜间、晚',
'nomadic migrations':
    '游牧迁徙',
'nun, eleventh letter of the Uyghur script':
    '努恩，回鹘文第十一字母',
'oil, fat, butter, ghee':
    '油、脂、酥油、醍醐',
"one of seven jewels representative of the Buddha's and or Maitreya's allure in Mahāyāna Buddhism":
    '大乘佛教中表征佛与／或弥勒庄严的七宝之一',
'open; clear, easy to understand':
    '敞开的；清楚的、易解的',
'opportunity, chance':
    '时机、机会',
'orderly, neat, potent, influential':
    '有序的、整齐的、有力的、有影响的',
'other, different, stranger; abnormal, heretic, deviant, pertaining to the other side':
    '他者、不同的、外人；反常的、异端的、偏邪的、属于彼方的',
'outer side, exterior':
    '外侧、外部',
'pain, ache, twinge; illness, ailment':
    '痛、酸痛、刺痛；疾病',
'painting, drawing; flourish, decoration ornamentation':
    '绘画、图画；纹饰、装饰',
"palm, inside part of one's hand":
    '手掌，手的内侧',
'pe, thirteenth letter of the Uyghur script':
    '佩，回鹘文第十三字母',
'penis (of little children)':
    '阳物（幼儿的）',
'princess, female regent, empress, queen':
    '公主、女摄政、皇后、王后',
'product, manufactured goods; fabrics, woven fabric products':
    '制品、产品；织物、纺织品',
'product, manufactured goods; textile goods':
    '制品、产品；纺织货品',
'product, manufactured goods; weaves, weaving products':
    '制品、产品；编织物',
'purple, violet, redbud, mulberry, pink, rose, dark red':
    '紫、堇紫、紫荆色、桑色、粉、玫瑰色、暗红',
'quality, well made product':
    '上品，做工精良之物',
'queen, empress, queen consort, wife of an emperor':
    '王后、皇后，帝王之妻',
'quest, seeking; challenge':
    '寻求、探求；挑战',
'raw, unprocessed (of meat)':
    '生的、未加工的（指肉）',
'red, vermilion, cinnabar':
    '红、朱、丹',
'red-hot, searing-hot':
    '炽红的、灼热的',
'reddish-grey, roan':
    '微红的灰色、沙毛',
'reel of books, compiled books':
    '成卷之书、汇编之书',
'reel of books, scroll, fascicle':
    '成卷之书、卷轴、分卷',
'reflection (of light)':
    '（光的）反照',
'regal, reverend, venerable':
    '尊贵的、可敬的、可尊的',
'relative (especially one related by blood)':
    '亲属（尤指血亲）',
'relative, close family friend':
    '亲属、通家之好',
'religion; Manichaeism, true religion':
    '宗教；摩尼教、真教',
'religion; false teachings, heterodoxy':
    '宗教；伪法、异端',
}
