#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part E — 词条释义 a–g.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_e.py; edit that.
"""
G = {
'a year of the horse, seventh year in the twelve-year solar-cycle, corresponding to the horse (馬) of the Chinese zodiac':
    '马年，十二年周期中的第七年，对应生肖之马',
'aleph, first letter of the Uyghur script':
    '阿列夫，回鹘文第一字母',
'all the children of the five modes of existence':
    '五趣中的一切子民',
'all, whole; every-':
    '一切、全部；每一',
'allotment, personal garden, region':
    '份地、私园、地界',
'alms-giving of valuable goods':
    '以贵重财物行施',
'aloe; agarwood, eaglewood':
    '沉香；伽罗木',
'an emphatic particle, used with pronouns for emphasis and referral back to a previous subject':
    '强调小品词，与代词连用以示强调并回指前文主语',
'any written material; letter, grapheme; syllable; alphabet':
    '一切书写之物；字母、字位；音节；字母表',
'any written material; text, written work, a body of work; book, written document, letters, edicts, etc.':
    '一切书写之物；文本、著述、作品；书籍、文书、书信、敕令等',
'anything written; text, inscription':
    '一切书写之物；文本、铭文',
'apple, apple tree':
    '苹果、苹果树',
'auspicious, holy, praised; praiseworthy':
    '吉祥的、神圣的、受赞颂的；可赞的',
'awakeness, waking state':
    '醒觉、清醒状态',
'aware, open-minded, responsive to new ideas':
    '有觉知的、开明的、能接纳新见的',
'beasts of burden, mount and farm animals brought along during such nomadic migrations':
    '驮畜，游牧迁徙时随行的坐骑与牲畜',
'beloved person, friend':
    '所爱之人、友',
'beloved, dear, desired':
    '亲爱的、心爱的、所欲的',
'beth, second letter of the Uyghur script':
    '贝特，回鹘文第二字母',
'bile; choler, yellow bile':
    '胆汁；黄胆',
'bird (generic name for any avian species)':
    '鸟（禽类的通称）',
'black colour[ed] […]':
    '黑色〔的〕〔……〕',
'black, swarthy, dark':
    '黑的、黝黑的、暗的',
'blade, knife, any offensive equipment':
    '刃、刀，泛指攻击性器械',
'blessing, inauguration; abhiṣeka':
    '加持、灌顶（abhiṣeka）',
'blood, one of the four bodily humors':
    '血，四体液之一',
'blue (said of eye color)':
    '蓝（指眼睛的颜色）',
'blue or gray of eyes':
    '眼睛的蓝色或灰色',
'body, corporeality':
    '身、色身',
'book, book scroll, published works, oeuvres':
    '书、书卷、著述、全集',
'boy, unmarried man, young male human':
    '少年、未婚男子',
'boyfriend or a girlfriend, romantic partner':
    '情人、恋人',
'branched?/pointed? The meaning of this term is uncertain.':
    '分叉？／尖锐？此词词义未定。',
'brook, stream, river':
    '溪、涧、河',
'buttermilk, airan':
    '酪浆、艾兰',
'buttermilk, airan, ayran, doogh, etc.; a non-alcoholic, fermented milk-drink':
    '酪浆、艾兰、都格等；一种不含酒精的发酵乳饮',
'calm, quiet; equable, even-tempered':
    '安静的、沉静的；性情平和的',
'chakram, a kind of disk used as a melee weapon':
    '战轮，一种用作近身兵器的圆盘',
"chamber of concubines, women's quarters":
    '姬妾之室、内闱',
'chestnut, bay (said of the color of a horsecoat':
    '栗色、枣红（指马毛色）',
'child \U0010203fof any gender\U00102040; son':
    '孩子（不分性别）；子',
'cleric, pastor, religioner; monk, cleric, priest':
    '教职人员、牧者、修道者；僧、教士、司祭',
'cleric, pastor, religioner; pastor, electus, priest':
    '教职人员、牧者、修道者；牧者、选民（electus）、司祭',
'cleric, pastor, religioner; priest, monk':
    '教职人员、牧者、修道者；司祭、僧',
"co-in-law, a father- or mother-in-law of one's child":
    '亲家，即子女配偶的父亲或母亲',
'color, form, shape, appearance':
    '色、形、状、貌',
'color, form, shape, appearance; face color, skin tone':
    '色、形、状、貌；面色、肤色',
'commentary, explanation (of a text)':
    '论疏、释文',
'common and vulgar, plebeian':
    '寻常粗俗的、平民的',
'common and vulgar, plebeian; simple, basic':
    '寻常粗俗的、平民的；简单的、基本的',
'concept, thought; figment of imagination, object of meditation':
    '概念、思念；想象之物、所观之境',
'concubine, prostitute':
    '姬妾、妓女',
'congratulation, benediction; eulogy, praise':
    '祝贺、祝祷；颂词、赞美',
'consciousness, idea':
    '意识、观念',
'constellation, mansion':
    '星座、宿',
'copy, written copy of a work':
    '抄本，著作的手写副本',
'corporeality, body, human body, appearance':
    '色身、身体、人身、形貌',
'correct, true, honestly, fitting':
    '正确的、真实的、诚实地、合宜的',
'correct; effective':
    '正确的；有效的',
'country, realm, nation':
    '国、疆域、邦',
'creek, valley, river':
    '溪、谷、河',
'crop, fruit, harvested goods':
    '庄稼、果实、收获物',
'danger, threat; hindrance, obstacle, nuisance':
    '危险、威胁；障碍、阻难、烦扰',
'dapple, freckle; red spots on the skin, eczema, leprosy':
    '斑点、雀斑；皮肤红斑、湿疹、麻风',
'dappled, mottled, spotted, parti-coloured':
    '有斑的、杂色的、花的',
'daughter, female offspring':
    '女儿',
'day, daytime, the span of a day, times when sun is visible during a day':
    '日、白昼，一日之长，日间见日之时',
'decoration, flourish':
    '装饰、纹饰',
'delicious, hearty':
    '美味的、丰盛的',
'desert, snowy wasteland':
    '沙漠、雪原荒地',
'despised, hated; bad, vile':
    '被厌弃的、被憎恨的；坏的、卑劣的',
'difference, distinction; clarity, distinguishing remark':
    '差别、区分；清晰、区别性的说明',
'different, better than the rest; excellent, crème de la crème':
    '与众不同、胜于其余的；卓绝的、上上之选',
'dirt, soil, earth, land':
    '尘土、壤、地、土地',
'dish, plate, trough':
    '盘、碟、槽',
'done in a good way':
    '做得好的',
'double, pair; twinned (of things)':
    '双、对；成对的',
'dun, sallow, faint, blond':
    '土黄的、灰黄的、淡的、亚麻色的',
'ego, self; puruṣa, ahaṃkāra':
    '我、自我（puruṣa 神我、ahaṃkāra 我慢）',
'elder sister, sister':
    '姊、姊妹',
'ember, burnt and used coal':
    '余烬，烧过的炭',
'emphatic particle':
    '强调小品词',
"end, terminal point; end of one's life":
    '终点、末端；命终',
'essence, core, pith, existence, being':
    '本质、核心、精髓、存在',
'excluding, not including':
    '不包括、除外',
'existence, mode of existence (eqv. गति (gati)); reincarnation, life, lifetime':
    '存在、趣（对应梵语 गति，gati）；轮回、生、一生',
'expensive, precious; miserly':
    '昂贵的、珍贵的；吝啬的',
'fame, reputation, renown':
    '名声、声誉',
'fame, reputation, renown; luck, good omen':
    '名声、声誉；福分、吉兆',
'fast, the act of fasting; religious and/or ritualistic abstinence from food and drinks':
    '斋、守斋；宗教与／或仪式性的禁食禁饮',
'fastening rope (of a tent)':
    '（帐篷的）系绳',
'female camel, she-camel':
    '牝驼',
'fever, abnormally high body temperature':
    '发热、体温异常升高',
'file, filed papers':
    '卷宗、归档文书',
'flow, rush, current; creek, stream':
    '流、涌、水流；溪、川',
'foot; (and by extension) leg, root, stalk, end, estuary':
    '足；引申为腿、根、茎、末端、河口',
'for your bones and joints':
    '为你的骨与关节',
'foreleg (of animals)':
    '（兽的）前腿',
'forgive my sins! spare us!':
    '赦我罪！饶恕我们！',
'fortune, wealth, treasury, imperial storage; silk brocade':
    '财富、库藏、内帑；织锦',
'friend, comrade; retinue':
    '友、同伴；随从',
'friendly; saving, rescuing':
    '亲善的；救护的',
'friendly; virtuous':
    '亲善的；有德的',
'friendly; welcoming, helping':
    '亲善的；好客的、助人的',
'frog, toad; turtle':
    '蛙、蟾；龟',
'generation, lifespan':
    '世代、一生',
'generous, liberal':
    '慷慨的、大方的',
'gently, slowly, quietly; leisurely, peacefully':
    '轻缓地、慢慢地、静静地；从容地、安然地',
'gimel, third letter of the Uyghur script':
    '吉梅尔，回鹘文第三字母',
'girl, unmarried woman, young female human':
    '少女、未婚女子',
'gold; gold coin, precious metal':
    '金；金币、贵金属',
}
