#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part B — 例句为主，兼收组合符与分隔符.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_b.py; edit that.
"""
G = {
'(by extension) to be attached to material world':
    '引申义：执着于物质世界',
'(by extension) to understand; to sense, to conceptualize, to perceive (a concept)':
    '引申义：理解；感知、概念化、觉知（某一概念）',
'(literally, “rock of merit, a male given name”)':
    '字面义：功德之石，男子名',
'(please add an English translation of this quotation)':
    '此引文原文未附英译',
'... [thus] entering the kitchen stealthily, she becomes a platter [the size] of a mouthful.':
    '……〔于是〕她潜入厨房，化作一只一口大小的盘子。',
'A bar, used to separate short phrases, used interchangeably with \U00010f88':
    '单竖线，用以分隔短语，与 \U00010f88 通用',
'A boy found a dung of a falcon. May the flesh of his penis be blessed!':
    '一男童拾得隼粪。愿其阳物之肉得福！',
'A downy, soft fabric.':
    '绒软的织物。',
'A full handful of […] in your […]':
    '你〔的……〕中满满一把〔……〕',
'A green rock is my summer quarters. […]':
    '青石是我的夏营地。〔……〕',
'A nobleman checked on his horses. His white mare had given birth to a foal.':
    '一贵人查看马群。他的白牝马产下一驹。',
'A pair of white clothes.':
    '一套白衣。',
'A white horse, having chosen its adversary in three quests, sent it to pray to/for a mute.':
    '一匹白马三度择敌，遣之为哑者祈祷。',
'According to the truthfulness, …, integrity and the interpretation of the written law; [they preach] clearly and surely, that [the dharmas are] impermanent and always serene - [teaching] the suffering, the non-existence and the selflessness.':
    '依真实、〔……〕、正直与成文律法之解释；〔他们〕明白而确凿地宣讲：〔诸法〕无常而恒寂——〔开示〕苦、空、无我。',
'Adam (Biblical figure)':
    '亚当（圣经人物）',
'After having found [its prey], [the tiger] comes back to its den, rejoicing and happy.':
    '〔虎〕捕得〔猎物〕后，欢喜而归其穴。',
'All his strength left him, and he died whilst [still] pretending to be the sovereign, [with nothing but] half an apple [in his possession.]':
    '他气力尽失，仍佯作君王而死，〔身边只余〕半只苹果。',
'Amidst the void [of the firmament,] by drawing pictures and applying paint […]':
    '于〔苍穹的〕虚空之中，绘图敷彩〔……〕',
'An ice-cold drink.':
    '冰冷的饮品。',
'An old hoopoe sang before [the new] year dawned.':
    '一只老戴胜在〔新〕年破晓前啼鸣。',
'An old ox was being eaten by ants, gnawing around its belly.':
    '一头老牛正被蚂蚁啃食，蚁群绕其腹而噬。',
'And bluish-white stones are Mercurian in nature. […]':
    '青白之石属水星之性。〔……〕',
'And inadvertently, they meditated over deserts and wastelands.':
    '而他们不经意间于沙漠荒野中入观。',
'And so; stars, the sky, lights and illusory images are all, for an eternity, analogues for the perfected religious teachings. The causes for and the consequences of the impure knowledge.':
    '于是，星辰、天空、光明与幻象，永劫以来皆为圆满教法之譬喻。此即不净之识的因与果。',
'Arid, dry, dark and concentrated clouds.':
    '干燥、暗沉而浓密的云。',
'As long as there are folks in distress and need; [folks who are] destitute and poor, hungry and naked, wretched and pitiable, let them all come [hither], and I will give them everything they need.':
    '但凡有困厄穷乏之人——赤贫、饥而无衣、可怜可悯者——尽可前来〔此处〕，我必给予其一切所需。',
"As they themselves sorrow and suffer from [physical] pain; they still manage to dispel from their minds the sufferings of illness, aging and death [they suffered,] alongside the worry of separating from [= leaving behind] one's beloved.":
    '他们自身正忧苦、受〔身〕痛之际，仍能从心中遣除所受的病、老、死之苦，以及与所爱者别离之忧。',
'Be wary! The swan flew away, it will not settle down on a lake. The men will not return to their mother.':
    '当心！天鹅飞走了，不会再落于湖上。那些人也不会回到母亲身边。',
'Because their entrails have spilled out, a foul, stinking odour rises from [all of them,] from their bellies right up to their mouths. Some of them have [their abdomen] burst open, and their jet-black [hair] lies [scattered] all over the ground.':
    '因其肠脏流出，〔他们〕自腹至口皆腾起腐臭。其中有些〔腹部〕迸裂，漆黑的〔头发〕散落满地。',
'Being born there, they will not face hurdles for if they want to attain Nirvana; wandering in higher planes of existence, they are reincarnated [like so.]':
    '生于彼处者，若欲证涅槃则无障碍；游于上界，如是受生。',
'Brilliant wisdom was hampered by the patterns on turtle[-shells.]':
    '明智为龟〔甲〕之纹所碍。',
'Buddhacharita, chapter twelve:\nWith a body like a golden banner, [possessing] wisdom for eternity; with lips [plump] like mango fruit, with a disposition like pure quartz and pearls.':
    '《佛所行赞》第十二品：\n身如金幢，智慧永恒；唇〔丰〕如庵摩罗果，性如净水晶与珍珠。',
'Build a boat and a bridge out of [good] deeds […]':
    '以〔善〕业造舟与桥〔……〕',
'Building with two doors.':
    '有两扇门的建筑。',
'By and by, [in] all the different nations [of the world, in] each one of them there are statues of the ones that have became the Buddhas.':
    '渐次地，〔世上〕各个邦国之中，处处皆有成佛者的造像。',
'By not thinking about it [properly,] bothering ourselves with knowledge and conceptualizing it, we severed our ties with the search of the Path of Departure.':
    '因未〔如实〕思惟，徒以知见自扰、妄加分别，我们断绝了寻求出离之道的因缘。',
'By teaching the true doctine clearly and in depth, they become worthy of attaining perfect things.':
    '因明白而深入地宣讲正法，他们堪得圆满之果。',
"Can't you see that the great [and] mighty God-kings are coming, with their own retinues following us?":
    '你难道看不见，大威神的天王们正携其眷属随我们而来吗？',
'Cinnamon, nutgrass, aloe, sandalwood, [and] basil […]':
    '肉桂、香附、沉香、檀香〔与〕罗勒〔……〕',
'Clarifying [the instructions] for the people under the food alms laws...':
    '为受食施之律的众人厘清〔仪轨〕……',
'Climbing my mountain, which is my summer residence, I spend my summer there.':
    '我登上作为夏营地的山，在那里度夏。',
'Combining dot above, used to distinguish visually similar letters in connected writing':
    '上加点（组合符），用以在连写中区别形近字母',
'Combining dot below, used to distinguish visually similar letters in connected writing':
    '下加点（组合符），用以在连写中区别形近字母',
'Combining two dots above, used to distinguish visually similar letters in connected writing':
    '上加双点（组合符），用以在连写中区别形近字母',
'Combining two dots below, used to distinguish visually similar letters in connected writing':
    '下加双点（组合符），用以在连写中区别形近字母',
'Crown prince and his wife wandered through the corridors of the palace.':
    '太子与其妃在宫廊间徘徊。',
'Decorating [his] throne with pearl beads and strings, draping multifarious banners and parasols [on top...]':
    '以珠玑璎珞庄严〔其〕宝座，其上悬垂种种幢幡宝盖〔……〕',
'Dispelling and eradicating the nine defilements from the very beginning, and to the very end […]':
    '自始至终遣除并断尽九种烦恼〔……〕',
'Ducks, ruddy shelducks, partridges, hoopoes, sparrows and woodcocks.':
    '鸭、赤麻鸭、鹧鸪、戴胜、麻雀与丘鹬。',
'Dàyúntáng (大云堂), a certain Manichaean monastery in Dunhuang':
    '大云堂，敦煌的一所摩尼教寺院',
'Eucharistical cleric':
    '主领圣餐的教士',
"Even if you come here once, what difference does it make? Who is it who looks after your sons and daughters? Don't you think of your sons and daughters at all?":
    '你便是来这里一趟又能如何？谁在照看你的儿女？你竟一点也不挂念自己的儿女吗？',
'Even though one does entertain oneself with jewelry and make-up, that is not to last.':
    '纵以珠宝妆饰自娱，亦不能长久。',
'Fame and good tidings.':
    '名声与佳音。',
'For all [the people] knew [the unfair] skills and subterfuge [= were tricky,] only the [...-]ers [could] become religious masters.':
    '因〔众人〕皆通〔不正的〕伎俩与诡计，唯有〔……〕者〔方能〕成为教中之师。',
'For because of [our unyielding stand against] the insatiable and shameless Demon of Greed; we, in thought, word and deed; looking with our eyes, listening with our ears, telling words with our tongue, oblating with our hands, treading with our feet, we incur constant and permanent agony [upon ourselves].':
    '因〔我们不屈地抗拒〕那贪得无厌、无耻的贪魔；我们在意、语、身三业中——以眼观、以耳听、以舌语、以手献供、以足行走——为自身招致了恒常不断的苦楚。',
'For how many ways out the deer knows, the hunter knows just as many tricks.':
    '鹿知多少条脱身之路，猎人便知多少种伎俩。',
'For the divine favour of the Buddha, for the benefit of all living beings in the five modes of existence […]':
    '为佛之天恩，为五趣一切众生之利益〔……〕',
'For when one gets hungry or gets thirsty, just a cup of cold water should suffice.':
    '人饥渴之时，一杯冷水便已足够。',
'Forms denominal nouns denoting association, mutuality or a common possession.':
    '构成名词派生词，表示关联、相互或共有。',
'Forms deverbal nouns and adjectives.':
    '构成动词派生的名词与形容词。',
'Four dots, used to separate long phrases, used interchangeably with \U00010f87':
    '四点，用以分隔长语段，与 \U00010f87 通用',
'Generous people who give alms are scarce, stingy people who do not give alms are plenty, my God!':
    '慷慨布施者少，吝啬不施者多，我的神啊！',
'Give them [to me] without qualms or clamor. You said "I will ship you four pints of paint and lacquer," but once again you did not.':
    '请痛快地给〔我〕，不要迟疑喧嚷。你说过「我会送你四品脱颜料与漆」，可你又一次失约。',
'Greedy [and] desirous mind is like a poisonous snake.':
    '贪〔与〕欲之心犹如毒蛇。',
"Guru Anaṅgavajra (eqv. Tibetan ཡན་ལག་མེད་པའི་རྡོ་རྗེ (yan lag med pa'i rdo rje))":
    "上师无支金刚（对应藏文 ཡན་ལག་མེད་པའི་རྡོ་རྗེ，yan lag med pa'i rdo rje）",
'Having been led astray by ignorance and greed as a result of their evil deeds, the three men have received a bitter reward in this life.':
    '三人因恶业为无明与贪欲所惑，今生受此苦报。',
'Having not seen it, those very Muslims always say this: Without seeing the real physical form of the god itself, who [can claim to] have heard the true words of the god? Can [then] the teachings of heathenous prophets be [ever] verified? Wise people, now you know this.':
    '那些穆斯林不曾亲见，却总是这样说：不亲见神本身的形体，谁〔敢自称〕听闻过神的真言？异教先知的教义又如何〔能够〕证实？智者们，如今你们明白了。',
'He checked on his camels. His white she-camel had given birth to a colt.':
    '他查看驼群。他的白牝驼产下一驹。',
'He deigned, in an instant, to shatter our boundless misdeeds. Through the Four Immeasurable Minds, he deigned to destroy the defilements that might pose hurdles to the seed of the root of the future bodhis.':
    '他于刹那间垂允粉碎我们无边的恶业。以四无量心，垂允摧毁那些可能障蔽未来菩提根种的烦恼。',
'His back and shoulders will be plagued by cramps. His sides and feet will ache. His mouth will dry out. He will be constantly vomiting.':
    '其背肩将为痉挛所苦。其胁与足作痛。其口干燥。将不住呕吐。',
'His majesty Mani, the prophet-God.':
    '摩尼陛下，先知之神。',
'Hour hand that moves clock-wise.':
    '顺时针转动的时针。',
'How are its fastening ropes? — They fasten it [= the tent] well.':
    '它的系绳如何？——把〔帐篷〕系得很牢。',
'I am a male maral with a nine-branched/pointed antler.':
    '我是一头生着九叉角的公马鹿。',
'I am the God of Roads on a dappled horse.':
    '我是骑花马的道路之神。',
'I bow before the holiness of the Bodhisattva of inexhaustible awareness.':
    '我礼敬无尽意菩萨之圣德。',
'I bow down before the likeness of the divine lake.':
    '我于神湖之影前顶礼。',
'I love you like so, like these two pearl beads in [my] palm […]':
    '我如此爱你，就像〔我〕掌中这两颗珍珠〔……〕',
'I venerate, my Goddess, and will always venerate your steadfast and distinguished_((Hend.)) wisdom.':
    '我的女神，我敬奉，并将永远敬奉你那坚定卓越（重言）的智慧。',
'I want to curse the cycles of thoughts regarding the vile and inauspicious things, the thoughts of [worrdly] attachment, the inamicable lust, […] turning […]':
    '我要诅咒那些关于卑劣不祥之事的念头轮回，〔世间〕执着之念，不善的贪欲，〔……〕转〔……〕',
'I was reborn into this extremely miserable life of a vixen, [and] my physical strength is not particularly great either.':
    '我转生为牝狐这般极其苦厄的一生，〔且〕我的体力也并不强健。',
'I was separated from my dear son.':
    '我与爱子分离。',
'I went under the overgrown reeds via a raft.':
    '我乘筏行至茂密的芦苇之下。',
'I will [count] how much reverence I have shown and blessings I have given in one lifetime […]':
    '我将〔细数〕一生中所行的敬礼与所施的祝福有多少〔……〕',
'I, me; first person singular pronoun':
    '我；第一人称单数代词',
"If one comprehends the meanings of these words intimately, wouldn't they be distinguished in wisdom? If through meditation, one eliminates all elements of worldly attachment, then they'll taste the marrow [= core] of being.":
    '若能亲切领会这些话语的义理，岂不智慧卓绝？若藉禅观断尽一切世间执着，便能尝到存在之髓〔＝核心〕。',
'If one feels a twitchy feeling in the root of their ear, [it is said that] they will receive gifts and honour from the nobility.':
    '若耳根处发痒跳动，〔占云〕将从贵人处得赏赐与荣宠。',
'If one feels a twitchy feeling on their legs or on their head, [it is said that] they will become very wealthy.':
    '若腿上或头上发痒跳动，〔占云〕将大富。',
'If there is a fleshy nub inside the nasal cavity, [and one] cannot take a breath [= breathe] through it, [and] it hurts; take copper dust and rock salt, grind them finely, mix them with honey and apply the mixture to your nose; and so it will heal.':
    '若鼻腔内生肉赘，〔以致〕不能由之呼吸〔且〕作痛；取铜屑与岩盐细研，和蜜涂鼻，即可痊愈。',
'If they speak based on the commentary texts, if they speak based on various other reasons […]':
    '若依论疏而说，若依种种他因而说〔……〕',
'If they were to ruminate on [these verses, and] if they were to [think] with heretical causes […]':
    '若于〔此诸偈〕反覆思量，若以外道之因〔思惟〕〔……〕',
'If we, either because of distress, or being miserly about giving alms, should have not been able to give the sevenfold alms to its full extent to our religion; […]':
    '若我们或因困厄，或因吝于布施，未能向本教圆满行七种施〔……〕',
'If you [wish] to ward off [spirits that bring with them] abuse and disgrace, you should place this amulet under your doorsill; this amulet is [also the one] that boys and girls are supposed to lick, lest they lose their way [back home.]':
    '若〔欲〕驱避〔招致〕辱骂与羞耻〔的邪祟〕，当将此符置于门槛之下；此符〔亦是〕男童女童当舐之符，免其迷失〔归途〕。',
'If you carry that [gem]stone [with you,] strangers cannot harm [you.]':
    '若〔随身〕佩带那〔宝〕石，外人便不能伤〔你〕。',
'In an open plain, [the tiger] came across a wild goat.':
    '在旷野上，〔虎〕遇见一头野山羊。',
'In day and night, I amble along.':
    '日夜之间，我缓步而行。',
'In each of [those] lotus flowers, there is a poisonous snake hiding inside, and they appear from a distance like so […]':
    '〔那些〕莲花之中，每一朵里都藏着一条毒蛇，远望之状如是〔……〕',
'In every sense, with all [their] strength...':
    '在一切意义上，竭尽〔其〕力……',
'In my earlier battle against Ahura Mazda, I was defeated. Since then, in the hands of the Demon of Lust, I have risen, fallen, died, and been reborn. Within the Earth, the God has sustained [me.]':
    '我先前与阿胡拉·马兹达交战，为其所败。自那时起，我落入淫魔之手，起而复堕，死而复生。于大地之中，神维系着〔我〕。',
'In the Heavenly realm above and in the corporeal [realm] of the people below, the feastings and pleasures do not end.':
    '上界天域与下界人间的形色〔之域〕，宴乐不绝。',
'In the case of someone contracting leprosy, they must tear up parts of star anise, grind the pieces and then rub the [leftover] juice into the spotted area. The leprosy will fade away.':
    '若有人患麻风，当撕碎八角，研为细末，以其汁揉搓斑处。麻风即消。',
"It destroys the mind, [one's] peaceful existence [and] beautiful and youthful body; leaving them as withered as a patch of lotus flowers struck by hail [and heavy snowstorms.]":
    '它毁坏心识、〔人的〕安稳存在〔与〕美好年轻的身体，使之枯萎如遭冰雹〔与暴雪〕摧折的一片莲花。',
'It has been exactly seven months [and seven] nights since [they] have achieved salvation.':
    '自〔他们〕得救以来，恰好七个月〔零七〕夜。',
'It is said that, these religious doctrines written on the perception of the dual characteristics [of the nature of being] do not exist at all.':
    '据说，这些依〔存在之性的〕二相之见而撰的教义，根本不存在。',
'It is so that the people who have not made sacrifices or vows to the gods - they will feel pain in their heads and eyes. They will feel their hands and feet ache, their hearts, waist and armpits cramp.':
    '凡未向诸神献祭或许愿者，即会头目作痛。手足酸痛，心、腰与腋下痉挛。',
'Jesus, Aryaman, Adam […]':
    '耶稣、阿利耶曼、亚当〔……〕',
'Khan; king, ruler, emperor':
    '可汗；王、统治者、皇帝',
'Kitchen. (Literally, “Food-house.”)':
    '厨房。（字面义：「食屋」。）',
'Knitted and weaved sweater.':
    '编织的毛衣。',
'Let [him] dictate our traditions accordingly, even when inconvenienced [or] sorrowful.':
    '纵有不便〔或〕忧伤，亦让〔他〕依此口授我们的传统。',
}
