#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part H — 词源中的词根释义.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_h.py; edit that.
"""
G = {
'Adam':
    '亚当',
'Christian fast':
    '基督教的斋期',
'Hey!, O!':
    '喂！啊！',
'I, me':
    '我',
'a horse with a roan or reddish brown coat':
    '沙毛或赤褐毛色的马',
'a thing that gives enjoyment and pleasure; concubine':
    '供享乐之物；姬妾',
'adjectival suffix':
    '形容词后缀',
'agarwood':
    '沉香',
'aloe, agarwood':
    '沉香、伽罗木',
'antidote; medicine':
    '解毒药；药',
'apple':
    '苹果',
'awake; sober':
    '醒觉的；清醒的',
'bird':
    '鸟',
'birth; existence':
    '生；存在',
'bond; tent gear':
    '束缚；帐具',
'bottom, underside':
    '底、下侧',
'bronze':
    '青铜',
'camel colt':
    '驼驹',
'comfort of heart':
    '心之安慰',
'congratulation, benediction':
    '祝贺、祝祷',
'copper, brass':
    '铜、黄铜',
'crotch, the space between the thighs':
    '胯、股间',
'danger; hindrance':
    '危险；障碍',
'dapple, freckle; variegated':
    '斑点、雀斑；杂色的',
'daughter of a monarch, princess':
    '君王之女、公主',
'denominal suffix':
    '名词派生后缀',
'derivative suffix':
    '派生后缀',
'deverbal nominal suffix':
    '动词派生名词后缀',
'deverbal noun suffix':
    '动词派生名词后缀',
'device; trick, subterfuge':
    '手段；伎俩、诡计',
'difference':
    '差别',
'different, other, separate':
    '不同的、他者的、分离的',
'difficult; brazen, brave; heroic warrior':
    '艰难的；胆大的、勇敢的；勇士',
'diminutive suffix':
    '指小后缀',
'elder sister':
    '姊',
'embellishment, flourish':
    '装饰、纹饰',
'eulogy, praise':
    '颂词、赞美',
'evil, wicked; foul':
    '邪恶的、恶劣的；污秽的',
'famished':
    '饥饿难耐的',
'flow, current, stream':
    '流、水流、溪',
'foot':
    '足',
'frog, turtle':
    '蛙、龟',
'god, heaven':
    '神、天',
'gold':
    '金',
'goods, riches':
    '货物、财富',
'heavy':
    '重的',
'hungry':
    '饥饿的',
'hungry, famished':
    '饥饿的',
'idem':
    '同上',
'inauguration, abhiṣeka':
    '灌顶（abhiṣeka）',
'joint of finger, knots in a cane':
    '指节，竹节',
'knife, blade':
    '刀、刃',
'large tent':
    '大帐',
'liver':
    '肝',
'load, difficulty':
    '负荷、难处',
'mare':
    '牝马',
'master; person with a particular skill; learned person, polymath':
    '师；有一技之长者；有学问者、博学之士',
'meat, flesh':
    '肉',
'mendicant; Buddhist monk':
    '乞士；比丘',
'minister, śreṣṭhi':
    '大臣（śreṣṭhi）',
'mouth':
    '口',
"nomad's hut":
    '游牧者的棚屋',
'nomadic tent':
    '游牧帐篷',
'nominal derivative suffix':
    '名词派生后缀',
'open, clear; intimate':
    '敞开的、清楚的；亲密的',
'pain, ache; illness':
    '痛、酸痛；疾病',
'palm of the hand; handful':
    '手掌；一捧',
'penis of little children; a kind of variegated sparrow':
    '幼儿的阳物；一种杂色麻雀',
'poison':
    '毒',
'praise, blessing':
    '赞美、祝福',
'purpose, intention':
    '目的、意图',
'quiet, peaceful':
    '安静的、平和的',
'reciprocative suffix':
    '互动后缀',
'red, crimson':
    '红、绯红',
'self, spirit':
    '自我、精神',
'separate, divided':
    '分离的、分开的',
'slowly, peacefully':
    '缓慢地、安然地',
'sour, bitter; worry, sorrow':
    '酸的、苦的；忧愁、悲伤',
'spiritual guide or teacher':
    '精神导师',
'stallion':
    '种马',
'sun':
    '日',
'sunny place, sunshine':
    '向阳处、阳光',
'tent':
    '帐篷',
'to be aware, to understand, to listen':
    '觉知、理解、听',
'to be occupied with something in mind':
    '心中萦怀某事',
'to be quiet, mild, calm; to be amicable':
    '安静、温和、平静；亲善',
'to be separate':
    '分离',
'to become bitter or sour; to feel pain, to lament; to worry; to feel compassion':
    '变苦或变酸；感到痛苦、哀叹；忧虑；心生怜悯',
'to bless':
    '祝福',
'to compose a text, to pen':
    '撰文、书写',
'to curse':
    '诅咒',
'to endanger; to hinder, to seduce':
    '危及；阻碍、诱惑',
'to exalt':
    '尊崇',
'to fan, to blow wind':
    '扇、吹风',
'to fast':
    '守斋',
'to feel pain':
    '感到疼痛',
'to find':
    '寻得',
'to flow':
    '流',
'to flow; to surge':
    '流；涌',
'to grasp, to clutch':
    '抓、握',
"to hold in one's hand":
    '执于手中',
'to know, to understand':
    '知晓、理解',
'to open':
    '开启',
'to paint':
    '敷彩、绘',
'to praise, to exalt':
    '称赞、尊崇',
'to praise, to revere':
    '称赞、崇敬',
'to rise':
    '升起',
'to rise, to elevate':
    '上升、提升',
'to rise; to climb':
    '升起；攀登',
'to separate':
    '分开',
'to separate, distinguish':
    '分开、区别',
'to shine, to illuminate':
    '照耀、照亮',
'to stick, to destroy, to split etc.':
    '刺、毁、劈等',
'to take':
    '取',
'to talk with a murmur, to be tongue-tied':
    '含糊而语、结舌',
'to tie':
    '系、缚',
'to unite, tie; to join two thing together':
    '联结、系；把两物接合',
'to wake up; to sober up':
    '醒来；醒酒',
'to waste away, to use up time':
    '虚耗、消磨时光',
'to write':
    '书写',
'white; bright':
    '白；明亮的',
}
