#!/usr/bin/env python3
"""Chinese for the Old Uyghur glosses, part G — 词条释义 r–z 及动词条目.

Generated by tools/emit_ou_gloss.py from tools/ou_zh_g.py; edit that.
"""
G = {
'religious teachings, scriptures':
    '教法、经典',
'religious, pious person':
    '虔信之人',
'resh, fifteenth letter of the Uyghur script':
    '雷什，回鹘文第十五字母',
'respectful; expressive, emotional, vivid,':
    '恭敬的；富于表现力的、动情的、生动的',
'river, body of water':
    '河、水体',
'road, way, path; method':
    '道路、途径；方法',
'royal favour, prestigious gift, gratuity':
    '王恩、殊赏、赏赐',
'ruler, master, beg':
    '统治者、主、伯克',
'sadhe, fourteenth letter of the Uyghur script':
    '萨德，回鹘文第十四字母',
'samekh, twelfth letter of the Uyghur script':
    '萨梅赫，回鹘文第十二字母',
'sandalwood (Santalum album)':
    '檀香（Santalum album）',
'savior, the Messiah':
    '救主、弥赛亚',
'seminal fluid, sperm':
    '精液',
'share, margin; gift':
    '份额、余裕；馈赠',
'shin, sixteenth letter of the Uyghur script':
    '申，回鹘文第十六字母',
'shy, reserved, modest; peaceful, at ease; concentrated, meditating':
    '腼腆的、内敛的、谦逊的；安宁的、自在的；专注的、入定的',
'sight, view, glance':
    '视、景象、一瞥',
'skill, labor, expertise':
    '技艺、劳作、专长',
'skill, trick, subterfuge':
    '伎俩、诡计',
'skin, skin color, appearance':
    '皮肤、肤色、外貌',
'son, male offspring':
    '儿子',
'son, male offspring; embryo, unborn child':
    '儿子；胚胎、未生之子',
'son, male offspring; nestling, chick':
    '儿子；雏鸟',
'song, melody, hymn':
    '歌、曲调、赞歌',
'sorrowful, (emotionally) painful':
    '忧伤的、（心中）痛苦的',
'sound, intonation; singing voice':
    '声、语调；歌声',
'sour, bitter, acidic, tart':
    '酸的、苦的、涩的',
'special, different; select, extraordinary, excellent':
    '特别的、不同的；精选的、非凡的、卓越的',
'sperm, male reproductive fluid':
    '精液',
'star sign Libra, eqv. Sanskrit तुला (tulā)':
    '天秤宫，对应梵语 तुला（tulā）',
'stitch, seam; thin film, membrane':
    '缝、缝合处；薄膜',
'stream, brook, fountain':
    '溪流、小溪、泉',
'string, thread, (and by extension) silk':
    '线、丝；引申为绸帛',
'sufficient, appropriate, fit, apt':
    '足够的、恰当的、合适的',
'tastefully decorated carriages drawn by horses and stallions':
    '由马与骏马牵引、装饰雅致的车驾',
'tau, seventeenth letter of the Uyghur script':
    '陶，回鹘文第十七字母',
'teacher, (religious) leader, master and/or preacher':
    '师、（宗教）领袖、导师与／或宣道者',
'teacher, master; learned person, polymath':
    '师、导师；有学问者、博学之士',
'tent, family unit':
    '帐篷；一户',
'the Anointed one, Messiah':
    '受膏者、弥赛亚',
'the Buddha, the Tathāgata':
    '佛、如来',
'the Buddha, the Tathāgata; a statue or an image of Buddha':
    '佛、如来；佛像',
'the Moon, sole natural satellite of the Earth':
    '月，地球唯一的天然卫星',
'the Sun, the star at the center of the Solar System':
    '太阳，太阳系中心的恒星',
'the aromatic pith and essence procured from such trees, sandalwood oil, sandalwood paste':
    '自此类树木取得的香心与精华，檀香油、檀香膏',
'the bitter and sour fruit of [my] deeds':
    '〔我〕业行的苦涩之果',
'the one that the black birds snatched away (...)':
    '被黑鸟攫去的那一个（……）',
'the space between the thighs':
    '股间',
'the toil of having to leave the ones you love behind (eqv. Priyaviprayoge-duḥkha)':
    '不得不舍别所爱者之苦，即爱别离苦（Priyaviprayoge-duḥkha）',
'the world, the Earth':
    '世界、大地',
'thus, this is so; but, on the other hand':
    '如是、正是如此；但另一方面',
'title (of a book)':
    '（书的）题名',
'to be hungry, to starve':
    '饥饿、挨饿',
'to be stingy, to be miserly':
    '吝啬',
'to become bitter or sour; to ferment':
    '变苦或变酸；发酵',
'to blow (of wind), to exhale':
    '（风）吹；呼气',
'to break, to tear':
    '破、撕裂',
'to catch, to hold':
    '捕、执',
'to come across, to meet':
    '遇见、遭逢',
'to console, to solace':
    '安慰、宽解',
'to destroy; to end, to finish':
    '毁灭；终结、完成',
'to dominate, to rule':
    '统御、统治',
'to encircle, to siege':
    '围绕、围困',
'to enjoy oneself, to comfort':
    '自娱、慰藉',
'to explain, to clarify, to commentate (a passage)':
    '解释、阐明、注解（文段）',
'to feel (physical) pain, to ache; to lament, to grieve; to worry':
    '感到（身体）疼痛；哀叹、忧伤；忧虑',
'to fight one another':
    '相斗',
'to flow, to surge (both of water etc.; metaphorically also for people)':
    '流、涌（既指水等，亦喻指人群）',
'to follow, to trace':
    '跟随、追踪',
'to give birth to a colt':
    '产驹',
'to hate, detest, loathe':
    '憎恨、厌恶',
'to hinder, to endanger; to harm (sb.)':
    '阻碍、危及；伤害（某人）',
'to insert, to beat':
    '插入；捶打',
'to issue a decree':
    '颁敕',
'to know, to recognize':
    '知晓、辨识',
'to love, to desire; to be quiet':
    '爱、欲；安静',
'to open; to undo (a bind)':
    '开启；解开（束缚）',
'to pity, to commiserate':
    '怜悯、同情',
'to praise, to exalt; to curse':
    '称赞、尊崇；诅咒',
'to reach a destination':
    '抵达目的地',
'to rise, to elevate (both literal and figurative senses)':
    '上升、提升（本义与引申义）',
'to separate, to distinguish (chiefly figurative senses, seldom literal)':
    '分开、区别（多用引申义，少用本义）',
'to shake, to tremble':
    '摇动、颤抖',
'to shine (said of a mirage)':
    '闪耀（指海市蜃楼）',
'to twitch, to flail (said of sick men)':
    '抽搐、乱动（指病人）',
'to walk, to amble, to tread':
    '行走、缓行、踏',
'tree, wood, plank':
    '树、木、板',
'under, low, below':
    '下、低、在下',
'under, lower, below':
    '下、较低、在下方',
'uninhabited, desolate area':
    '无人烟的荒芜之地',
'unweather, strong wind, hurricane, borea, snow storm, blizzard':
    '恶劣天气、狂风、飓风、北风、暴雪',
'venerable, respectable':
    '可尊敬的',
'veranda, corridor, hall, lobby of a building':
    '廊、走廊、厅、门厅',
'warrior, brave and heroic youth':
    '武士，勇武的少年英豪',
'water; (by extension) any inviscid liquid':
    '水；引申为一切稀薄的液体',
'waw, fourth letter of the Uyghur script':
    '瓦夫，回鹘文第四字母',
'wet, damp, moist':
    '湿的、潮的',
'wetness, dampness, humidity, moisture':
    '湿、潮气、湿度',
'white; clear, light, bright':
    '白；清亮的、浅的、明亮的',
'wine, reddish brown':
    '酒；赤褐色',
'with the body of the blessed virgin, Saint Mary':
    '以蒙福童贞女圣马利亚之身',
'woman, adult female human':
    '女子、成年女性',
"women's quarters":
    '内闱',
'woolen fabric, cloth used for sewing sacks, a kind of rough fabric reminiscent of a felt':
    '毛织物，用以缝制口袋的布，一种类似毡的粗织物',
'wrongly, falsely':
    '错误地、虚妄地',
'year of the chicken; tenth year in the twelve-year solar-cycle, corresponding to the rooster (雞) of the Chinese zodiac':
    '鸡年，十二年周期中的第十年，对应生肖之鸡',
'yodh, seventh letter of the Uyghur script':
    '约德，回鹘文第七字母',
'yogurt, a dairy dish made from curdled milk':
    '酸奶，以凝乳制成的乳制品',
'you, thee; second person singular pronoun':
    '你；第二人称单数代词',
'zayin, fifth letter of the Uyghur script':
    '扎因，回鹘文第五字母',
}
