#!/usr/bin/env python3
"""
Turn the crest into the masthead's opening sequence.

The homepage draws the archive's seal as text first — one row at a time, the way
a plate used to come off a line printer — and then dissolves into the real
image. Both halves are produced here so nothing has to be computed in the
browser: the rows are baked into a module, and the 4648px original is resized
to something a masthead can actually afford to load.

    python3 tools/ascii-head.py

Writes src/data/head-ascii.js and public/persona/head-plate.webp.
"""

import os

from PIL import Image, ImageChops

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "public", "persona", "logo.png")
ASCII_OUT = os.path.join(ROOT, "src", "data", "head-ascii.js")
PLATE_OUT = os.path.join(ROOT, "public", "persona", "head-plate.webp")

# Columns of type across the masthead. Wide enough that the seal's linework and
# the two birds survive as shapes rather than smudges.
COLS = 176

# Monospace cells are taller than they are wide, so rows have to be scaled by
# the advance width or the crest comes out stretched. Space Mono sits at 0.6em.
CELL = 0.60

# Dark to light. The page renders this pale-on-black, so an unlit pixel is a
# space and the brightest part of the seal is the densest glyph.
RAMP = " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"


# The crest was drawn to glow on black, so brightness is the wrong measure of
# where the ink is: the birds are deep blue at a luminance of about 37 and the
# title is charcoal, both darker than the seal's rim yet just as much a part of
# the mark. Ink density is taken as whatever is furthest from black — luminance
# or saturation — which picks up the birds and the lettering as readily as the
# highlights.
FLOOR = 10
GAMMA = 0.55
CHROMA_WEIGHT = 0.85

# Ink level that counts as "the mark" when deciding where to crop. A faint
# rule left in one corner of the artwork otherwise drags the crop box out to
# the edge of the canvas and shoves the seal off to one side.
BBOX_THRESH = 110


def crop_band(im):
    """Trim the black surround away from the emblem on all four sides.

    The mark sits off-centre in a large black field. Left alone that field
    becomes empty margin the masthead has to reserve, and the seal ends up
    small and off to one side; cropped to the artwork it can be centred and
    given the full width of the plate.
    """
    box = ink_map(im).point(lambda p: 255 if p > BBOX_THRESH else 0).getbbox()
    if not box:
        return im
    padx = round(im.size[0] * 0.02)
    pady = round(im.size[1] * 0.02)
    return im.crop((
        max(0, box[0] - padx), max(0, box[1] - pady),
        min(im.size[0], box[2] + padx), min(im.size[1], box[3] + pady)
    ))


def ink_map(im):
    """How much ink each pixel carries, as an L image.

    max(luminance, saturation·weight) rather than luminance alone, so a deep
    blue bird counts as ink instead of as background.
    """
    lum = im.convert("L")
    sat = im.convert("HSV").getchannel("S")
    sat = sat.point(lambda v: round(v * CHROMA_WEIGHT))
    return ImageChops.lighter(lum, sat)


def darken_highlights(rgba, ceiling=200):
    """Compress the brightest ink so it still registers on white paper.

    Anything above the ceiling is scaled down toward it; darks are untouched.
    Without this the seal's pale rim prints as almost nothing.
    """
    r, g, b, a = rgba.split()
    curve = [v if v <= ceiling else round(ceiling + (v - ceiling) * 0.35) for v in range(256)]
    return Image.merge("RGBA", (r.point(curve), g.point(curve), b.point(curve), a))


def build_rows(im):
    im = crop_band(im)
    w, h = im.size
    rows = max(1, round(COLS * (h / w) * CELL))
    small = ink_map(im).resize((COLS, rows), Image.LANCZOS)

    span = 255 - FLOOR
    small = small.point(lambda v: 0 if v <= FLOOR else round((((v - FLOOR) / span) ** GAMMA) * 255))

    px = small.load()
    out = []
    top = len(RAMP) - 1
    for y in range(rows):
        line = []
        for x in range(COLS):
            line.append(RAMP[round(px[x, y] / 255 * top)])
        out.append("".join(line).rstrip())
    # Blank leading and trailing rows would just be dead time in the reveal.
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return out


def main():
    im = Image.open(SRC)
    if im.mode == "RGBA":
        flat = Image.new("RGB", im.size, (0, 0, 0))
        flat.paste(im, mask=im.split()[3])
        im = flat

    rows = build_rows(im)
    with open(ASCII_OUT, "w", encoding="utf8") as fh:
        fh.write(
            "// Generated by tools/ascii-head.py — do not edit by hand.\n"
            "// The archive seal as %d columns of type, one array entry per row.\n"
            "// The grid metrics travel with the rows so the masthead can size the\n"
            "// type to land exactly where the photographic plate does.\n"
            "export const HEAD_COLS = %d\n"
            "export const HEAD_ROWS = %d\n"
            "export const HEAD_CELL = %s\n"
            "export const HEAD_ASPECT = %.4f\n"
            "export const HEAD_ASCII = [\n%s\n]\n"
            % (COLS, COLS, len(rows), CELL, (COLS * CELL) / len(rows),
               ",\n".join("  " + _js(r) for r in rows))
        )

    # Same band as the type version, so the dissolve lands the seal in place
    # instead of jumping.
    plate = crop_band(im)

    # Lift the mark off its black field. The page it lands on is white, and the
    # crest is mostly dark blue and charcoal, so on paper it reads as printed
    # ink — where sitting on black had buried it. The ink map doubles as the
    # alpha channel, which keeps the birds' soft edges instead of cutting a
    # hard silhouette around them.
    alpha = ink_map(plate).point(lambda v: 0 if v <= FLOOR else min(255, round(((v - FLOOR) / (255 - FLOOR)) ** 0.62 * 255 * 1.15)))
    plate = plate.convert("RGBA")
    plate.putalpha(alpha)

    # The seal's rim is pale, and pale ink disappears on white paper. Pull the
    # lightest parts down toward the archive's ink so the whole mark holds.
    plate = darken_highlights(plate)

    plate.thumbnail((1600, 1600), Image.LANCZOS)
    plate.save(PLATE_OUT, "WEBP", quality=90, method=6, lossless=False)

    print("rows        %d x %d cols" % (len(rows), COLS))
    print("ascii       %.1f KB  -> %s" % (os.path.getsize(ASCII_OUT) / 1024, os.path.relpath(ASCII_OUT, ROOT)))
    print("plate       %s  %.1f KB (was %.1f KB) -> %s"
          % ("x".join(map(str, plate.size)), os.path.getsize(PLATE_OUT) / 1024,
             os.path.getsize(SRC) / 1024, os.path.relpath(PLATE_OUT, ROOT)))


def _js(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


if __name__ == "__main__":
    main()
